#ENC[AES256_GCM,data:tiywI4QXIJO5y0aGGp9z52nwddtB+aAJFo2hiPb+WrtA1m85rxpgyl7SP9vDoT0cvV4onqGMPK5lZZap6EhFTyMu/Q8wJOc0,iv:43C4z8rj2D9bJkJCOGaS/N0ZR6hYfGtwoLasfKZWxV0=,tag:QAvLVkpYC3lAohZ0mReMhQ==,type:comment]
#
#ENC[AES256_GCM,data:Nn6SnmtP6ur1l/9Ern4vB5k7aY2vhqot0ige9l3WJkNvCasUuxmuuZ0doo7cAihmG0DnIxhJzuIp0AiTa4vEkpadDteGh27OBe4iUw==,iv:EbmoQvCEl3zohENRTqzB63xZFUBrLiO84/JMjGymmEE=,tag:rVGNxu8HDqf+GhuezI65iQ==,type:comment]
#ENC[AES256_GCM,data:oaZpLKd2yFYWpmnECzk6m4HLmryNAEnRqEkoqCfUkQwsVinNbHzE+4FFwgacfOf4RVqBSNWBCP5jh7lEARNczo7cHRci/vX4,iv:WCi0JcQBEfWQ++Chd7Ev8Ka8fc3C9E6BOz53MRCt2AM=,tag:H+XSR0AFDgOxZtqjgZZInA==,type:comment]
#ENC[AES256_GCM,data:FQEGf8fJHpDRFYGOzwednKik4pElEt6g9KY65l7AJHHjMn6+XFi/9TV1ydJRXa7o8CvgPtpbvLDCaebnVHwlhk5TNDiHROg=,iv:jijk+Myd4yEtqGkwezzHYXj69Su3b+TR7cYIuRW5c+0=,tag:dH26VodlQuiA+AbzszqMbA==,type:comment]
#ENC[AES256_GCM,data:nQ1q9im/pkBVFosNX784PNi6mC6jJgJJfFCAvINheYHcgEaq0JylIK7qjaQyWJrSyooWGPioF86vvw==,iv:JJyIiIkTW1Gwedu0xN7tHvqKBb4/pRjdmIdNETpHlM4=,tag:S5Zi2unNWPIPflOwPStVRg==,type:comment]
#
#ENC[AES256_GCM,data:l3XtP0hlM3Thkzy8uo5uiWAZX26J4spm/+l4d2zG+o9gG7NTzQnvjFQ85FCvtw7brRMLhqGjvIzwiJ+4gBEG6o4XI4XL,iv:ZHt/5FalmLxLpUirBahUZ262yw+S43ejhJk4G4py6UA=,tag:hSa29znXY6hMD2kIScYz8w==,type:comment]
#ENC[AES256_GCM,data:vc9FirGDrGnrO6tUeERUDGc+y7RGYW790WnKHtgu,iv:RL7GfwgbbwW78S5rQqFPYs/Cgs6P6qJeROcWp+B/X2g=,tag:KbST+qJ1KyEVgxfe5dyt5A==,type:comment]
#ENC[AES256_GCM,data:TXNifeecFIVaQunwZfLkQgpYCy+Epq6RKj81twk843O6WIti2psIAYwhgpCvD8v3uVgxRRD6HyX/awcpzHuCqcoKcXLTDyMR,iv:xiR1Ooz0nFO1hUBglGLUf8iJHWdkM+Lmjw3DcGAG5Iw=,tag:kEewyqvoi80beUBGGLXZRQ==,type:comment]
#ENC[AES256_GCM,data:4/zYkgp0hu89uRBwHWCx1EQpBxK0LxUkGhGNv0q4xjyigf/adS1nUnXYOvWcOw==,iv:NbBeqaK1eNLMMzIn5MGsDfnu7Wws05VlvAu+J77OKNc=,tag:Y3rhbPuh4KxbmeZQHegtMQ==,type:comment]
#
#ENC[AES256_GCM,data:b4dMEcRi3SZg4xdaHapBIwBLcngp6sahULFSSuXLoB7EuCAxIgdBy0Axqo7ElBDvGDGcA3hwRF7qwSGm3bAgFaCL/w==,iv:mHmsyKrp932c56LKEAF26wFGpG4BQAwcD8u1/wkxSdY=,tag:3qO/WDt8dD+Fwxz6rI3aiQ==,type:comment]
#ENC[AES256_GCM,data:HufYFTF9kmx2Z0AnAw1gzBMngVhUse7ZY9Yw/VaRCV6i9IUu7DwdO3sysWLaVzF5eUzkg9ibFI3B1Wy4JYfU8HXZ,iv:pUtOfgeot1rCUyuKOCEvuP76a88AfAe4IgyjdeQDEG0=,tag:LAF2Rv9Mx+EmKGJBJkHwBw==,type:comment]
#ENC[AES256_GCM,data:+X47+DGZ4K3w+/1tzPLGEj/J0bcYo/KdgT1241cSUntSI5AIk2GOYUxJrS/6mNhZ8Q==,iv:vBQ+M6AIpYxdi84Hc2fF2uznFLIFyUqV2V0Lo7/dYJ8=,tag:gSHzoUxIjkAO6DGcUm3+CQ==,type:comment]
#
#ENC[AES256_GCM,data:CgqhGHwpQuN+5LqFFcEi8eYRpaqfLFjkks7KnsLMQGYCLANiupDVdg==,iv:RAErRNGFbttjGsi930bWfSHKf07G7YVQFPeV12OzlIU=,tag:hdew3db3mq3JsekZ7ygehg==,type:comment]
#ENC[AES256_GCM,data:C+Z5EcyRp6k689t52lHRNMzMxh0fiBUSflpIOZHd7r1VICkIV+H7a74M0PUy4ffsQF7Itlfg/noK1ls8KJVq4GdmwR9T,iv:HWjKtxdv5jmkrMGOqPGDDsaeVNZDTQDIEOkcSpsv9xk=,tag:qgGvxOjWpAJe4wJujn+d4Q==,type:comment]
#
#ENC[AES256_GCM,data:D8rA9q6K30m+kcz9lu2F1ZUyyHgpmIQvZ29pKC01Cc6i77hJ,iv:3XCKg+YR3dMnNDK8c/YDTVnwCL3weLT46GVFaWe+3Qc=,tag:qjPxJht88frahcgIbJBPVQ==,type:comment]
#ENC[AES256_GCM,data:i53WCqfQwvveUt33FLzfmt6dZxs3ORy8FDJPe4lPb3siZAVQ954+xFCsxCuao8m4tF//C2t2IqfI+LsbMENd6KpRAH3HrHtyVzE=,iv:rjPqIPqUjWn2mOuwU+ar+rkzOS5c1h9ae3UTpLozGxE=,tag:hrsfEVdb6mdeifZ6NT299A==,type:comment]
#
#ENC[AES256_GCM,data:b1AW4La/jWDuU9qBfcZOHfRxIrNkrC+9Nbxuxj8R4jNOkPAZ6NYH/tlm/B4Yo4OlWhBauq/W+T9ev3Zs9qcqfWLxFRNrhbUio4ge,iv:rWuciiI9sU7RYFceo1LqR1i9zfOVFYxke7FwxMgrD2o=,tag:gpvn3Cuc8JpU+V3LhA/M6w==,type:comment]
#ENC[AES256_GCM,data:52sqePzvC6z/UinHcJDPn4Tuy1iuDIB14UrocwAUziuUvuEz8AqDZV19mkWkG0Ttwbdx/zQ1imgPaFY09pix/2Q6sYCVkZwDYso0,iv:NNBc5ZUzgZeXxMVfcDjwcI91cvo3y1M1OrfeVXhjJv4=,tag:lm5rLYLIPOpkOcPCSRYqxw==,type:comment]
#ENC[AES256_GCM,data:ob0w2d+N7N6+50qK5g9GQyBSmDv1qH4O7ImmxDj0I2BiyD2oLiSX+TteHA==,iv:vC6AIJT5+EcKbEKuq4W9yhY4+N07mKI5XAKYNLKKcWA=,tag:imJGQE58w8MLjRd5/tmr/g==,type:comment]
#ENC[AES256_GCM,data:QthCUta2Xu2ZG/Tk341reRViq3HbMeUn8tfdXvZpmf7z33gGLwSzqpzPHPvEVADu6vU8ZBqn6pv/NBTg5IgnedgmBJzJRIoOwMbbBQ==,iv:FXGlHdnzXZOb0paIOu25UPZ+ZTRhxyVKiPxTqWb+8lg=,tag:ILBebG90Xeb0lCfG+3RKuQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:gU4=,iv:ap5X1svEeIYVi7KAJlKx/x7eLjlr1O2PKm2Xxcw+9f0=,tag:p1AiWsdYv/lJ2XWJzab5cQ==,type:str]
kind: ENC[AES256_GCM,data:K+Q6xNPT,iv:oM8RnGHKH6qtOEtLSGxJ3zHpIl+O0i9uB/guPWhkgAE=,tag:2PwdjLa31ToKPIft9ATvZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5GforqZO1KvQba2GS8Nz2I7g3g==,iv:J+4MlG9Okl3ZY9cKNPjKlHakKDyQoJKkZ6W30Ue0W2M=,tag:wYSesmT0YOVzOwPOV6qTYQ==,type:str]
    namespace: ENC[AES256_GCM,data:mY3uJdPXcg==,iv:OTlerAfn0VhGfzLC9XNzAukmyHTdKUr4+1ImUWW7KOQ=,tag:Ga0UkDOUpadQy7xVVk8V7A==,type:str]
type: ENC[AES256_GCM,data:yfxuuaM7,iv:Q/hWzP+/UFU7xIAFHBIhhtTdozB0TzeWSYbDP+4nUR4=,tag:ziyMyQkbjaomxtudOskjIQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:zLJJ33qIBm6dYYy5ztA/Mg==,iv:I/QP0NFe0D5Z+HeI2gUvZe17TVBM5Tco5dJxWpLH8lY=,tag:aizDaF5KDnEWcgEt6m7wGA==,type:comment]
    clientId: ENC[AES256_GCM,data:XLmKdomNA5GxbipycV0eIEzq4HOjPYuEesEh+kl/8XuXI+4J,iv:l/VNN5JiEE4mYM4rwqLwYXiZTCp3tuIlR14QbYz8jzw=,tag:Zk00loSunYrdBG2RggIXRw==,type:str]
    clientSecret: ENC[AES256_GCM,data:0pjGEKaEBYcDv3C95h0oAPKRtfp7SA+aPOgtPOs5gNY=,iv:fV9MkOgyYGhvnZt88PoYWUUL6+UTjD4xupDk88PDYrQ=,tag:swKBdGUxId9BDmv9lHdTbg==,type:str]
    #ENC[AES256_GCM,data:gpHEK/ywZV4pOrlh/wjk6BTNl+d4eCiADoj4dV/nKmNdJ4eEF/3V2fdR,iv:jFu/D5LZ3z/zS64Mp6xdg4qixfog/8NHNTxiiuFidEY=,tag:dRLd13UDTyICc2V0cs7+iA==,type:comment]
    cookieSecret: ENC[AES256_GCM,data:PYWk5bDgiGF4Rz7UPjUy/fWxyT7aYXDky1tyUgoJ6Pe+5oIJoJg3/NzhH7E=,iv:ntjUuKFTxS+btFMlvTFlXQsGp6CWmsq/fShx6xUqJWM=,tag:jmVFPIS3v7WG/qgbJWfqfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL0tuQU5YN3QyLzRUL2V2
            ckRyK1BZRE5HYnV4OVJXMlJ5Qno3bW1TVkRvCm5vU0RhRXd6UWdSMWxVeXZEVHVs
            eFdSWHRPUmZzQ0V3L2RvbWp1Z1JYZGsKLS0tIGFwVDhtWDZadWJrVDB0TmhzN0pZ
            U2pMMHAwc1Q0dSsvSW1sRGd1ek1ORFEK5b3sCQQjPzRnGEKi01EIntpn2HzIhGPB
            ePUHCYO6QNtCni74LcF/DWIPX213ZEUlUxWaY4DBGQjqllAnw+zmrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-09-10T20:00:25Z"
    mac: ENC[AES256_GCM,data:AMhyBEELOPVPDwnLOdaXRSTw5/j5JrC9v4i0tbKwCehcRVlShB9ci9zPKph+I3wv2arocupBMJjvSWtvDOaq4DMVwGPWzpMjENweg7XAhpnDAAlPz+BX27G909YPL98rOmm4j2u+d70vBNcoTkXQg+X7Hq/tGyqdFj42bEc2ZoM=,iv:ED0ibPODBlH1e5agQzE81UQXmEZeNbvxQmKm4tkamMw=,tag:fGEBkeAmIThBBxfqF3uGYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
