apiVersion: ENC[AES256_GCM,data:sMQ=,iv:IXoe68xWKcj/fiZeQ9nM6ORoQhzdwHAdgqSCGqf7sQU=,tag:RvCUtDpINTOnjn5qSz/31g==,type:str]
kind: ENC[AES256_GCM,data:pfNflc4A,iv:kDL8M+ftuO8HV4Ni2TdXIXhFiLd5RwzpsX1EALwaE7o=,tag:lJLNMzspe2VP8onFR3jj0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9bJaBALVi0OXU6arax1E,iv:g86OBcPfTf23j2BPGSOJCp1XPcw6YV5x3UyJSt33OW8=,tag:jXozzekTPJoWTexORRHeUg==,type:str]
    namespace: ENC[AES256_GCM,data:gJ4ZA6gJTg==,iv:dsgcg1jRpU2MyeQ+InWr/MvBSLhDnFPZD2IMBy5xvwo=,tag:lpXLf7PHHoa0XIvUbcjy5g==,type:str]
type: ENC[AES256_GCM,data:N9Fnd7bf,iv:aX1nND7bV8QAHFwOfkgUGp+bCUuA+hJY+0TvR9FN88U=,tag:k1GHKYLn1I6cHqWIkPyxjw==,type:str]
stringData:
    #ENC[AES256_GCM,data:NRHd9D4HbbnGBJ7UWQHVZLgS+LtG1gozAav+eEhGO1wtx/pq/ePD/gzOP0ljv23YI6YmyhWj,iv:2b9m88wcRRsyQqXQCRv6sUHnF2SSbxKFQRUxWNIsnZs=,tag:ysSmvVwk7b6AuaYbl24saw==,type:comment]
    #ENC[AES256_GCM,data:fCADMykKF25RQg0kZ30Dko3kshTOq30/kx4P3f/PwlWjtxiVDSTq1M9kP0PLEQlVj4zjHfdBaedZx9U=,iv:bCOqJ9chhSbWw2/csYJ98RRQUl+kTlm1ej2h+Yuh8wQ=,tag:f4CDjM8v1CMkzfKTafCZRw==,type:comment]
    #ENC[AES256_GCM,data:VtJcoby1aLcbfoF5Z0orTdaTWPNYQ+tMwnctonFQyfOUE5DNuLMzKzosw+oA6cOlAkMwIeiDFjxxyl9V1FzR,iv:nf9uN+meyijwPUmiD11czIqcHVH9ti9BJMmoCEhhsxo=,tag:QcG1nZWw4kCKHlPybEs7cA==,type:comment]
    #ENC[AES256_GCM,data:uUttY7ajXCy+vUeX2KfrAcRz2u1c19afdwuFZHaGFgrzY92NTR3yB//Lgr2IVk2nf7Qz6EyYQ3eV,iv:A8Yd/vxZd8r05/NTCOxZeyMMrZYF+aa3cAfjrM0fVpw=,tag:gt/sSasYwRstOeuBtWelGQ==,type:comment]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:RgwqQZ5jSPN+zA9K88uZlUrctTfoaBtzBCmNE/rGxzo=,iv:DS3cMxQg0pFtd6ESo9WiuwLPZsCM5mtV/ufNhmaC0Xc=,tag:NGSDBUZ9YJvPY1t2RQ9zOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y3kxY3RDZW9qWmdOU2Nw
            UmVWNk5iSENyYnEvWnA0aVdaRXFDN1BJWWdNCjlmVGNUblVOMzhMYkFTejlUU0Yx
            VHRtSTdqTlFSMUljUE1iKzdZVkpESTgKLS0tIFQyUVdZaTd5eFM4TnJZdk1CeGll
            MXhJMlNTRjhZUFllR0Z6N3g5VmNUMjgKrZ4evK+wQl03n+012VkGlpAtQawMQMHU
            5P5zJ0jveegR85WXQxwUQ8ODRpXSLdrzB4tTO6Bw5VqLqanAWH5N+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T09:23:47Z"
    mac: ENC[AES256_GCM,data:YIHgAJMtfSs8XfBqZV+k1IV4Jmr7xZeVkCikump2HmAmnq4/Vv5Wy5/gQR/sc5mwYMfjrhxpLOGtKLdknVANZra2EAFgFZDgNdK6F/uWs5v8cd1Ngd8URdIkB/SyCjbiUapOpA25zgDVN+jOpEyjDGh2IGHUTpw1pamKwM+ddX0=,iv:dMGCXuIdSbbVm3dwcPJ3x7ycdy3QLjadWjldBeh/d2k=,tag:W9VwIDgMsbXvwsZCjVkFIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
