apiVersion: ENC[AES256_GCM,data:ciM=,iv:TOYiPHWFROQBEYnGw1hGpmu+IpYHn/PRGIm+NkTFDAc=,tag:bU3iNE2kHYapYTinmTrydw==,type:str]
kind: ENC[AES256_GCM,data:wgegRdIT,iv:EOOenkhwWaG76rYahV/ULWtpdQDUuDCJ5o40l3EMyig=,tag:lOyF2M+Yo66sk+7BeDh9vg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:97mo8kc9pQmeNfVz8dIQNyLEO+e2,iv:IGwk/mnUx46gQHzVIkaCEn/9Rby0iwRaHXBZlSih2Lk=,tag:G2p9BezpaL0ws7WfJmleog==,type:str]
    namespace: ENC[AES256_GCM,data:W36qGKfqbw==,iv:81pmIOgqxyuY9pXfq7ximC0kbu+kj09GJdvj6Fu/ERk=,tag:zvKPgM9ZTgA7dvO/4Oihew==,type:str]
type: ENC[AES256_GCM,data:deSkNSSV,iv:+BhSpe82Bf3XBetCITA/uVA7IffBF7dQu5K8SS+orgY=,tag:okC09W3SQlsgfGMcCY5rxg==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:nlHvRmq54edWHPQPGCjteCMMaYaT7Q8u14VDsSI/sjR/aBW9Zux2eLw+cKrPf1WcQw9Tw09Ve8GCrmN1mDvRAmOm7wY1LAWpuyiyw4XkIq9fX+qt71aqiMWrZB8BniFe2o0wVf7Vf/LprfMUxG5H7D/YqJmyqEQuVwF10CLt8H2RbUfaLQH9XiH7xM4oqSZTj+l7rlzt5+P1ty0l+zi9P8senliAwq0RUm48DVEcyETLThGLUcHNjqOJeUus6z2oX8NMniu+qeYRsTcPSw1sv1MWdLgMEKdNHgqxfkMFCDoQCVY3GnDzfOyEFGTMqm92j2Vi5NJ/NUE+w8fQ5WQOTrAsT/6WRORCN05Fi3Jk0OrcYrj94ipesvhyrggWvo2GsEPrlQkuhINGTPT1ArhEsc3+c+rPkHn2J2r/tVkdqmYUMfA6pHFSukGupc0asIeCtpKObPyQJDD3eNkaZUoGGyJ6K4Sbpj3Pn0U81V08WlGpi5bT4UlKDvAK+86FpsLvP3POeuox7dBZPVMlf60pRqbq0BTOzA1ktA03zp0Upn44tbKznikXb3Ja73yDurns6EPooih3se/nYrzbNtRbZq9GcSI1sDKxZosysep92rkrQQpTf39ItWnyZZsFa9suWAAoB8VSmQosUVmUvngxkM9j/h88VmdlD+jIhjmMA4rqG1UUs/RwslegRKCjCCo+dyU4zt1OKiNI3F+R8fdAGw4NTZjymexd8sJLcWo2qu6SN5V+xO9zrQpNaQfy8BQ3D7sY60OciIELNA1aVjVESO6ciNfsJQ1AXlAIPXONFCP594syesW0MaLOYknQdRzN46l6bLnF6hI0ogmuuYcZA2fGO/DJRgH0i6rjw6prGJKdfCcHBsqvYnotW0EOXSA17+2xc/BveBaN05YkF6r9BhIudk3rSR96rp3+lYrLwQ2J+KXQ2rZtKS5y1Is4S69gXwbUrUXCJ4Ao+VoyFunE/dy3BjGbuXHSqqBdvr+vstInLZzFQ/wjsxCcUyJUGDxbUE9XkhqS7XH42L4Ih5yfM5+fv1ewf10Ong6YPb8RHy8dVECyQONpfxWfWdgmcKTX3LK+ZdqyKTqWwsvKPtR3fDDCjw0HRW7Wq5B8C9r7aH8fOoREyHof31VnBa7/,iv:obdy2+TTcWqo9OIVxn8SR3lbNplxrauc7TtFqtWtxi4=,tag:tDjHE4H/5Z2OaVRx5S6/9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUHVpV2VTZEppcEgxNFMr
            WGVkRjI1VTdDY1dhd1U2MEwvY1lvVlFyUVRFCnNNSHNJZEEzb21iS3JIU0NDZmhF
            ODN2RHVjVjNxTHRVaC9pejdrS3YwNXcKLS0tIHdhbW9vZGtpYXBBcmloNGhNSTE2
            bjBkaTRpM3dPemphK0hNSlpucG91M0EKItLgfZ4isuJI/vFR0VSVa0criM0llIRL
            GeBVoiG0k8idNb77aPsEojtrWQYIQhlzY1zHJwpgiLx0Pm93yaZeXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T13:36:39Z"
    mac: ENC[AES256_GCM,data:otDqGfeNQh8u8sEyQ3pea+lAyAVO+FLGdFX2e1n9VzNCLJvjQgUfy7i+fOzM1yNLKE1RsRzK/Sx/UA0bPFoRtWAgEXR7JA+BKSycZ3UAU7LzsHS1v1HP6d5SzYV+jAY2KWJXv+GINqb1+xHnlHs/W1EsVxVuG9Fq0lrRNpCIGwQ=,iv:zuLk8t2UyjbbPh8glVm18HnIvdtnnmiUzwRU7R7fToA=,tag:F8XqZlcQz21e8i1B/pR47A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
