apiVersion: ENC[AES256_GCM,data:uCg=,iv:opPncHglSArrAptCmTmv3/1Exb16NtDtTpmBAwVswxs=,tag:4OKjjnsyODg1UG3z8i7VcQ==,type:str]
kind: ENC[AES256_GCM,data:yaqxvl8J,iv:WW88KoY9nK4QqenzmrkvSlisBhhzAy40rwm1AN/6tHo=,tag:SvlE5525Dq7khqKxEPZAgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hZrFWoutB5WbyCwyj0h1pIgtu5rw,iv:g9FBv/HNJIzRnztxJbicAm1YuAz/MsaS/KkQkPFNo0A=,tag:0Jo4L+hmaMof/tslZBCdEg==,type:str]
    namespace: ENC[AES256_GCM,data:FqLq9xQNrg==,iv:+wdNvxpgDFSPbhOrxd5FTy9JCKMBUq5UbwV/E87nMng=,tag:Nl6DvYDorC9FUt2XR6VM3g==,type:str]
type: ENC[AES256_GCM,data:D9/is+/Q,iv:znRfYJ9x0xIYEvaEo/J31BA+GYjDh7RPWFc3EEDJz0s=,tag:o5C3GV4indhYMxKasNsOIw==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:YAXfAeaQjsWSJdzoc4BEpuUr9C7N5596F4v/TbiRfb5hPMcjyyYGGX6OW+kQ2MuWaGlTLBYKtvrFTA9N3ZxXcRN2tmVRP6YQEtYFpJn2+mdIAOLcPkZn3pfOM9ac7+r4VNwjb5r+uk7Ukt0QwTigbiM5Lbu0ZDouvqpUj9FXzIsg1n3tFi99W3ZrB0QUTkwwy9g6AZrDoll/SxCS6Ozfd93f93Q7+B+jJRruxIPWymKCYz0g/CU6OhGWNBpsBoLHIvxrnyjHFitJ9mLF8EgWS/pfx1V5FKTP0+4jB5YS6JHajSUTawgG3BcaaTBZXnmnspQ+lAlHdxxuEWrC5jieyTpPfmvRJFTbbvtfe6QY/o/Gec07iaTSJnSfRbdCedboOPbgae64h6m6MvV/uEoTMDCPkaAKz02k1bZ3qZAs8XcvVAvQGlrV8IDk7nzgsBDmSYINRWl3Q0MMoVYgCXvJN6Xatz9jysyCRCuY8A2QfcAvYHicP67MquoAQHFhs7m7KxMxhzXSouCCA0MgUycI1LbAG98nTb5MxZ/0lnyjoox7wnU3apWcxZ68eIiL3D55IvG5Kar74IZMnr0jFEPg+ElKXdloF380P0qtOa9h+/wWfPu2/0wNwPHMg1OghB307sog29prTcfWKkm3lFkJnp+NovLsXLY3SzCSb/QQVUmNtVsBGcxdn0QRag8zMl4eLUaGnEE3K3LK1OBuJmR6xUZqL7Oo1ZpxFvXowD7oZ3rsZYGTzbDmuy0a+E06NKa1u8i8zu5aptwUZ44YJ0mANvq1S3rVHVN1cPznr82k1UD04IQAXlj4rhhnfPuK1Dhj90Pan69K9S58mRT9kOfxSZBq7tILJrv3Rag4HuuUe/7qAFd1bm3fwQU/KAank0fxAeGDA1WUrYke1XFKQRhfjOWY1xVm7bZoUjEV61B/bZZDsx6/l9kE3pI8pRaRqaEYKfUw0tanMYkJkGEn/T4akih0UWVaGCkDuilhZsVAGjs7vUk2qHCBnp5Bi/BqINs3jQ8sttRKi1TylqMcvnkGbagWv/fYQdprgjcy9EUp+jwmKNzl72fSM/r/fHzLJJ3yYv+5mqnx8ZQbZciY0Jg2plAFtOHlUcTW+byYOwryciGHp6jp8EXXC/1joQ==,iv:mDtMvkl9GjxVffojCYfVXtmRVQJWMQOUM9ixFn2iQd8=,tag:z/WFnfGjRigrS0n+isKujg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WUlWTTlyQ3k2TDYyRW40
            c1RuVm94SllsRzJrcHVxNmd6VnBTaEhadkNrClBmSFB1eW83QXlyN0VqUjNkR0lT
            aS9QZ3ZYN3Y1OWlDYjhhSlFPYUtPYmMKLS0tIFlhbnpJMVlRZnFReW12QTJUbmZR
            dlJjdlgzRHBDcXRHbFYxOFBqMm1waE0KXym9M+f6qIBpqrO0tJ+XX1Uq8d6dSykM
            xbdaHU/i9Gns4W31O8dwxo7OGdaTZyvi7KV4kiManBYbJuuwJhWWLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T13:30:03Z"
    mac: ENC[AES256_GCM,data:PmQ7Sk9ZbDTii7IIkx043tX3sZyCJ84JuKL5wxdEf5DgbpaLj1gfaXCWp7ST79OlJNO7CdQKO3q2CTyy87aJOMSh1pTRwiOdJEbqRaQ6d5sif+O3JBQcGtuVnLFBUbpCOlLDzvJnxCsN3Ik0GvJ4kwSAiO1BHM5BrE4VtYCH2fQ=,iv:01FuTKl8xeZ3p38wIsmnCBoMe1hocfIn2A4+MkkXvA8=,tag:VRWJ99pj0wM1dBqJWc2aXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
