apiVersion: v1
kind: Secret
metadata:
    name: kavita-oidc
    namespace: media
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:adLhhjT9,iv:2+b2bElN/NhNREWBGK3csd6XoO2IYR5b/B63gARxOfU=,tag:OH5yYFkJ0U+FDmTUIikCaA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ECKQuZ3JXTpSKGKT4PIVouRcoFAF3VK+jnmKp/l4lFM=,iv:Fktc2erm3MO8PpaNSFZFpwMYA3CkybgyF8EftWg5Mtw=,tag:Qca+92IZM1/ManOd/2UGUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV0F2WGpKbHhuM1RMdVll
            WnhNcFJiTmw5YVh5dTVYakxnUWgvcmdQM2xnCmU0L1M5RG5QcXZOZGRuYVVTemtv
            MDVVdWI0cUZvOFZvVzNnVWhGNG5LQUEKLS0tIGJYMUdRNzRQVXV2ZGdaM1A5V2pX
            RlJZcHJKUWdTOXlxTndlSWxUTVlXc0EK2wGM8zvtuuo8Tw+Pkl+zESPZdC3yO8GK
            zI0EhD+IJL7BXdpAx2B3yq6uHXNeO9GWiPQgpYNMoH+tm+l+zT/VAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T11:45:12Z"
    mac: ENC[AES256_GCM,data:mP2RBI+W7GiayenEbNQ9rZiesaYYHVrXPl4ZvTc96nVj36Fp5mm76euTfBfY+uDM1phaxxddWZQVVlWOg+Cm9y4rQ93V+JO8plb7Pbd8agGIgvrQSTMKOnYYbGZrCwfwFyLKF58Xuz8GW1hONRZFOhwm1NG89hQGiWD8DWRCQj8=,iv:yM8jkngosLdEEfOS34R6wmnbfkKB/ZJ7exDdzifs0kU=,tag:/jfV5eg5g++0eIgeBEIwgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
