apiVersion: ENC[AES256_GCM,data:VDA=,iv:1i/1DlFPWitkcNSUZ0ke8gheX8q5Gr6I+/IGTYghi1E=,tag:hNl35fVIk/3aH8AmTioc2A==,type:str]
kind: ENC[AES256_GCM,data:Ye0ZjR5f,iv:XzG31GlWiLKWMqOvlgNQ5QwGiXZRcziL1w2NXKLHGuw=,tag:1Ney8qUNeVJFrglcSXrcYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pgUrDSWnaetvJZw=,iv:DfHMVYHVRXPLAkGV8IggF83FOUh41tm3FmYopitAImA=,tag:9/QXkzk1cN0uzLLZ1qcqXA==,type:str]
    namespace: ENC[AES256_GCM,data:Bt53aoU=,iv:aN3r5l8l8c46xbTleSJtbHYEFX0Qc1VI5RAn23N7QI4=,tag:jAv1InkXV36yYquaa17Sig==,type:str]
type: ENC[AES256_GCM,data:Dgjw4g/M,iv:5BrzyuXlqRXkj8FFl0fvtsNePIMPuZt7QvdB5gSpVPc=,tag:Me7yHSpzmRge/yYH6/jiZQ==,type:str]
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:CPqh35i+,iv:+AhJ0HsObUCKtkp7Ti0eJG1CcSWec9hv5sS4JTLd15U=,tag:f620MtYs1rvViiayo4mUVg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:dl7kA402gYgutEd3WnOK6YBP3KBcKrTjYhP96Y5CRJg=,iv:pcG9v+NXILDh9XKbXbvxdb6Y0OjKozt8cruynZbrar8=,tag:NuAtDybGj9NIUdqffzyFYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMWplVDZ6MnlDMG9kM2RY
            Zlg0a1NUWkx1TzZReXVYNmtsK1VvRHdXdlR3CjNrOEI3ZEN3Y0ZnT0RsSm40RWJl
            WG9MSktuOGJ2c2tnZUFFM3ZiY1pKYU0KLS0tIG9Od2FGNFJZOFlzNVJUMnZjWmNp
            YjJXSDlUTE8wWDFjZUdxSTBvY3hET2cK//IYGJ0v5eYFA8Z6KNOBG0MBoltn+AMx
            7i/8/WYWjTEf2nYV7OWB3oNhD1oz5tMhOae8GUDZZ8cYtEHFsYBbcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T11:28:05Z"
    mac: ENC[AES256_GCM,data:qPE16yLUVz7wlYKWR/X6BMPO1F2E9u4ivcb/H6e8s47K0E40FEoYcazm8GlO5xA9WeAfR7hZo9IzEUlH4QlLiztFCdTs/ijvLMWgVhjnXU1kT89FOPQYwG62Zd2P3M5B3fdOR4rfN/EVu3Z6p4kEIDNleOIaGlfaQakCKcUTkWI=,iv:aApz011VMJMb2Kx45nqSzh2H85TjenDtVeHHHuSFz5Q=,tag:tMe6vXnsRSFitz0W0T7yvQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
