apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbird
resources:
  - namespace.yaml
  - netbird-sops.yaml
  - server.yaml
  - dashboard.yaml
  - ingress.yaml
  - timeouts.yaml
