apiVersion: ENC[AES256_GCM,data:6yk=,iv:j266LUxBd0EhKkwABmsVonJ+CvKFGYdLGdHI8V1zCZs=,tag:6BasK9VBtfIssu/I5oq/Ng==,type:str]
kind: ENC[AES256_GCM,data:9YB89CTe,iv:Z4AqIjU9TheKip0LdYQc/4Fzh5WDsGwwvU6WSOGS1oI=,tag:5FcJtxUclR42hpwPfNA6wA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NQwlzd+wiILWXjrl,iv:sjJiTgehJAbiOwNK9dRxO399GlWC3R23PrTH3DcPH3E=,tag:S3ukUJ3tzGAobImMR62+sg==,type:str]
    namespace: ENC[AES256_GCM,data:e8qLaLty,iv:OMwNEP8fAyQgYU5lhScnTe38x8KQoHTumTFIjSa1qFk=,tag:TiNyS+bNzx1tSLDfZA/jyw==,type:str]
type: ENC[AES256_GCM,data:lXGTMBeu,iv:FmFMoGweV4ko5vvO4GwA6uSNcL+S1GunJMkNtHZT0Mc=,tag:cnLriJx9zumRep9wEmAIuw==,type:str]
stringData:
    #ENC[AES256_GCM,data:Mr5hrOOWCaWes8tkVzdtry7lUxKlTk/CL2tJL/UWIx7G8zd2CXCKTdbSJMXUb3H3gobp7cbGyOnW1z6gC3cM,iv:2nORdhEEG5r4B8JUnkhS+Il7qLzGhUOe9T0zUplfNIo=,tag:tpiDNTSnw5OpdKYtq0wDgg==,type:comment]
    #ENC[AES256_GCM,data:G4RTw79tvefGDRlwWyvX9u3jJA4KtPSqgBX6JDgLrhEu3ulw+eGCWI8kZnuqJyfEmryuP501xCul/5d0Xuq00Zc/cg==,iv:6b9gB/3ednl2yZ9DzTvikaGASWHsoEMZVZRbtYNZcV0=,tag:XNj47i7AWLFf8BG19q/sFQ==,type:comment]
    LIVEKIT_KEYS: ENC[AES256_GCM,data:SpScnYnig2F53zJevsgNkmDK8SkIMIKfFrW18RKIJjnvP7Yoa2aTmmzNYK2CVeEB6+gNhbr/3w2dGJcAhg==,iv:7aSVoPuVwyPY9nwTEDlwqMrns7vs6f0fXW07N7mrdnk=,tag:nDFmcPT874xDTu6FBBqYpw==,type:str]
    #ENC[AES256_GCM,data:GVszIPTiLl8h9aphjZUHxoWlUJLxxqYTaLasB1dj62ehJntZCWkhNoK2TXa8RVssVtPGNNHeVsdpML2tpmz2Xa/Vpw==,iv:q5sSVGYn2a2HKDdn9PXk8L4uvGIimImYzgRRAg+n7TE=,tag:0nTALx+o6mrj7vB3jTEJOw==,type:comment]
    LIVEKIT_KEY: ENC[AES256_GCM,data:tMl7qqN/zN2Y/5fg5D+A,iv:rg7IxAYbLz8CDP5xprmKtJKT7kGWht5xXUmMWxyeEzI=,tag:24O2dMdhGuquwrwv5fzfEA==,type:str]
    LIVEKIT_SECRET: ENC[AES256_GCM,data:H3hNPjD4niwWOXCRJ0kSmS7IseAOJxFgypuwz53KdQSy68d4axbRLYXruZs=,iv:4O2pvPjKxXTP3U6fyumM7EhWZbKkyd1ZZDngmc0hDXY=,tag:XLrreO0qcAivGBftrko0CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdnVTcE5SaWdLRFppeHh0
            ZGU1cjR5aWV2Rm5pNDlnS3A3R2xYeGkyS25NCjRhVDZqUStTWFlJSHllY0l1Rm5P
            c1NNSlcrQ0lqNktySzd2ZFRUdmdCSzAKLS0tICt3a0k3VHg0bGNPK1VJOWFUKzBR
            d3NBVHdkWDlobjFoS2sxdDFramtrMUUKp5R5wyZXz0qbn4Uj04ItIDbhWV1z+9Kk
            lJOGZc8g9FgjgnythiuWrxfJYUDzf6FwLb6cc2ZGfkY8gCA0cRSVTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T11:53:35Z"
    mac: ENC[AES256_GCM,data:vbmGbtHNZ65Q9XzlPfOX7MWwipuC+pI8q2/xp+i5dWQK2OJ3dHWQSxfsSlAFROndh6+WID2OL/PewhalamT0SdunoXEvGVLmx4kFG3RnZMzHXG8Y2lw7fw8blSfTsMs+E62MAQYMdDj01tMKQdWadYWgrUcS8rLVJzXXFyFl7ms=,iv:YXJCHt9AR4EWVZKcGhQBrTVLpxdqdTzG9AS0gXcqmhE=,tag:mq/iHWs4riHqtQXtXTzl1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
