apiVersion: v1
kind: Secret
metadata:
    name: tycho-a2a
    namespace: hermes
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bdImLIao2/LuuDbH/b1mh8GbCOS+DJzwmDwoSawXKzAr4Y5wh9q6sXTDkojZVuQ2nYcVdptkeyMPeFeqQfQn3fOKzEshKMeF,iv:+31A1kOKTnIArC82/CTuURT8z9p4wNCKCKxdSiLlXuI=,tag:ygx1PiP651F3DOwmLFYFKQ==,type:comment]
    #ENC[AES256_GCM,data:Cha4tcnKAGVHnPZ5WFwnoWgkrASMRrcpbaou4xVxwGiRBpz5xu8zqpoE2EMIi8Om30f2aClr0TVuGKZtBeu6LZyvfyFDbxApVg==,iv:hdExq0PYBzndTJj+svVLC0Xr5UJiy8J6kocNLgb7VcE=,tag:DrDtgGgxTFpOf6dGrC1stg==,type:comment]
    A2A_TOKEN_HALE: ENC[AES256_GCM,data:LfJytIceyWdOG0smYwHxiOuOhAEuapTMZLJR93meF/d7JNDn+R/OGg==,iv:AgEvbYY9wN99Co5SXQU+NrOGfFYF8VDPY/6CtBRAyyI=,tag:Iig++neTAXish/O63+F3aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYkVjYWQ2bjZXaUFnSUwy
            SjNlcTZxcHVlOXU3VEk3SjJqcDlSdlZSNUgwClRoaUE2VzRtRTByYXhZTUdZeGZ0
            ajBncWdtbm51WUZZL29EN3NHbmtxRTAKLS0tIEtXMURnWDRpYWNnNHVUYkRXaW9Y
            R3RPMitKVmVWc0RiNXdTNlVYYW16TWsKSsaat0WJm37zusTIRetvg2h5aThatKWe
            OODXR3/WYMzWeZzveEqBcrjNZKF/wtHZeB33rZOb/83PjuE02jK0Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T16:15:54Z"
    mac: ENC[AES256_GCM,data:gyFG7IHpxNFi7xagXjLw5RTJMf4/d+i/ANb7o/82dtQCfCh8+KTNjk1vJJelIToAoDLk7snYG+6URJLCl7CTCtZ/CCxfdSiQU7CL9LVBXjAn/aRSh7nl9hOeNmJRWE7SUg4CQ2kDNXlSjAVONYuZEDRNd0UmtZPD+mh25D/UfQk=,iv:wmqVsWFUUsL+1l6jHbkSgJ7xq57TG09ZtEsUySK3Ry0=,tag:JPDzByAob3j52kWE/UDU+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
