apiVersion: v1
kind: Secret
metadata:
    name: avatar-sync
    namespace: matrix
type: Opaque
stringData:
    SYNAPSE_ADMIN_TOKEN: ENC[AES256_GCM,data:VncVhziadZy5+M1GpjXbtJQg2HFKgc/p5lozSk/vv+vfooHs4hRHc3k=,iv:gsNgxjrUkTBmJ45/zeYDGGcmPGsFqR5nIxE7MkpPdO8=,tag:L8AYWqSSbHatiYUrPQ+CwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUTBUN3NteWlhd2l3bzl0
            OHdRRThNSXIvL2VsR0RWaGtHRkxRVHpjMkRzCkR6L3RTYUFaaVd4Y3NQdS9pZW9n
            V3kvTlBWVUlCM0pjU1JyTDl2c0tWdjAKLS0tIElFZmlEdlVKTnlGNU9sbS8xS0NR
            UzRmR2NOaURlRHlCRnZFcWNmK05PRW8KIEeOjsP3cNGa50wAykx1BFQp6dHApISs
            GVBPF1sruugjuDqqJBSjAQAVgyD/Ujkup59NBR37e1yzEpzpcOplJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T13:51:07Z"
    mac: ENC[AES256_GCM,data:kuqeOdAuPMmVb2fhZo8udgz2VNp6pKaLXBZFNdpiptlg0lOhqfHnvRVLuTZqWYOtxaLItteUkD6SqJimIUC/fQxUBIGu84PDEYCR6aLaCe85KDWDac/afB94OkRvR23Mti4AajSYvK/w9+8Q4WV1dzfMZwaHhOoEjoAei89Tth0=,iv:BldHVjLcNgkNgQdNu+8/yERlunnFlX3Dp8G1kqaLotU=,tag:jy3iZXUIxOhR0O/zo+qjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
