apiVersion: ENC[AES256_GCM,data:iwg=,iv:sx2rgohraUHSMDxbHQDOU9LNwS3eGmkZbZAYmywTVKE=,tag:uX6zOQD0kN7G7/g4JkuGpQ==,type:str]
data:
    apiKey: ENC[AES256_GCM,data:mCrGH/7PbzHBB7JOh4YrBra1XaaA7B0qQtIJ3f3epZoKzXmJtL0k/6FRhIOYzQyvZHSQ0NfSV0/WyyolNd2c5wSY0/aLdssrqCbc/5nagBZlwdsMpxWf5w==,iv:TWVo9sq+Tf38rZRBU1zXfxKUKxIVUku6jfNC9Zzks88=,tag:VIMUkA9BdNPBrUcJrh3+Pw==,type:str]
kind: ENC[AES256_GCM,data:IlkD3H5p,iv:y+isYjtqhVS8nDhKujb5vxc3Uw+RMZSW74zpVCriPLs=,tag:vqNyvrPxBre1RLVNMoXVXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5L8LzM5BMea175z7kHwLBUGGkbaMWFxlIg==,iv:QA7vwUJ6h6pdHDTkcA0GezYS5mj4eLlTVoyFOBMFWXU=,tag:E4U07XcFcg2nOISwtvhr5Q==,type:str]
    namespace: ENC[AES256_GCM,data:NA0iMT9jBzdEw2iCuq4=,iv:CRz7m90yh1XXLphaxratHdQeVccFgyT6uQ/83SpJiWc=,tag:hRtVBuxIoLbwqbrtl76Sow==,type:str]
type: ENC[AES256_GCM,data:qlLUDl7/,iv:fTFEVHjh9ZCjQpwJcHXxiplxczAwIQEoSef7tFVYW+E=,tag:JcbJQXIJ3iTS1HiMQS/ehg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMVBKdzg1MHNMUXd4MGJ1
            NHdhaC96ZTZ5cGNaQmY2RzJGV1lvUzcweDNjCllPbTRackZZZVNQcllLUUN3aGVL
            NVJVS3dGQytBcUZEeVg4cURzRllpVWMKLS0tIFdvdWxHM3RURWRuaW9za0JyaTU3
            eWZYT3NHTTYzMjEwaG93Vk10ZVVhMzQKrfM3Y9Qw6zzkA+saBe1TikEGW3m3PhKA
            AgyQKsYMshGB2J58HxB+JnXL8a6MgnkM6ZmofOzAOjHNQQzZmEnxbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-29T10:52:56Z"
    mac: ENC[AES256_GCM,data:fvJ6TCbEc8//YNykMh+xCxxtFBzaOgkso/0y463Ha4z4FMsNgVkQpy2IaD8HaaJr719K32sc7SWuuMazXnQIp8LN2pYTjPc+ifcFBdWEaa+A/BR46ma+PtmAXB2/sGCy35ub16UtkVKilfasSjjMMemGz7di0OE/BzJUC7cEl1o=,iv:cLJOHIKv/jfyvNIlmNj4FUxOz7LI80nrl4XLaHqBXH4=,tag:deDSwuTsLpDwhx89OS4cSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
