apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:d/Q59jyCUV3hvnXi+qG/A7lJ5CEPH5C7nQmRiMGjnHIBblFxMrF2o06Ukz891vBd3pQWPFM=,iv:cPOOUnaxi+MhfW5Lu4M9KK8d+rp/PRmOkBRnUNjq7YM=,tag:1cFmT8zgeZkcuG8uEthIaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZlJqekJSUER3czBJWU9R
            UVBneVFkVWVWYzdsZVhvVmtBVE5mS0pDRWkwCmEvaUNjSmRNMkhpb3N0NFM2TWRP
            NDdFS2NHeEpNdzk2VWRSellpYWczU0kKLS0tIEhTRDBzWG1pTEtWbmpwdHg2TVlt
            eitTUDd0MjhoZzljeHVVOWY5RzkxSDgKSQG01RuiCeWGIY36amET6C4d7U3kf5bX
            rb3Ks2QI3Hq9p0tc3tJhGaHhU26hyMOmh1bRmPnYTHF75fAjNp9N1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T22:20:26Z"
    mac: ENC[AES256_GCM,data:RPGZaBo92kDnoVCHAISuxK7X2o+rj9Ba05rXKgEzXEfgd8QHNUqwP9BiPSgc3LVTOz/v6GX5f8yOQWAvwMK+C4gxK8SQ9iBl5lSSs8dd+Xb7os60Z//MT/mQcWOTQbcm5Ar6E1Nknvow7OGa6pvY7cMBVIO/OfxuEBaH+O28TQA=,iv:4NKvGuAuRafyDpAH/vsbillx9iltYZYo+1vwJ6G/084=,tag:HXo3bVXwMNiOwpmVHnF+Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
