apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - media-pvc.yaml
  - jellyfin
  - seerr
  - download-stack
  - download-stack-dashboard
  - music-assistant
