apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 5000Gi
