apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret-jellyseerr
    namespace: media
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:6iJ6m0DFycZAPooFznLZROn00ViBW6koJpXZVKjuVjIpI6tl,iv:LzTkvpkFJLIoL+yBlrE6iu/utZ199scTbQr34k1UakM=,tag:z6c9TC4HyT4G2Z7kv6jS4w==,type:str]
    clientSecret: ENC[AES256_GCM,data:MNKRKL6fIeNIXK9tifOuNzFigse2nbYsRkXERq1h9wQ=,iv:2Yu64UAKgia15Ftad4rdEzSbrU1ZOpyyo9eLryW1PT4=,tag:obftUOVPky96dNYYUkqRQA==,type:str]
    cookieSecret: ENC[AES256_GCM,data:NJP49yUgcD8Da/u/NEzPy6+AoFeirmzvHn4RR2ecTqo=,iv:NbTUNIcvv6DdK+/3kiznIIy9F4wAaz3S1P7rUSS9G10=,tag:ojkg/tHgHYeBLWYuwyWdOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSTdGeG9jQlQ1WnB6RTBH
            Q0FLLzlPM0ozV1Fva0x6TkJCYW1HNStmeFdvCkxrVHlDaG84YkV3RGdsNi95OUc3
            V3B0d0FNdkpWT1BxZ3YrM0JhN051dE0KLS0tIE5pYkZFZVpYQXg0R1EycnFKM3k3
            eTRNZ1BSOFZCR2RMQTR1ejRqZTBCMUUK/Lwv2G5IRF2E3A5nJTFwBD0ZMBNANxU8
            ut4yUo0e8t+Etyh6zSHkbBzxdhi1VRTVPl03xiOSHiJZQ28lYdLXkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:32:58Z"
    mac: ENC[AES256_GCM,data:H0u0ZbPMRckCQUu9mxgK/m4MlfVzFEjjGjD+dRhvuyl/hZhLasUPNZ8KUKLGCGqWoJkIO65Yfo1xTEFSBBSPMntJfAE7fd8GmYqKOLxqGqqGiN18QrlO5UUu9aC/DRE1Sn3/F/3QYQ2BT9uA4DspGfvRJHHPrQWGshdU4Ss/qcM=,iv:toIyzTGg7YH9VUPRVlP3RU4T+RRFl65tqRQEAKFRmfs=,tag:4ftHNrriIrv3NWT/2GOBQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
