apiVersion: v1
kind: Secret
metadata:
    name: hale-a2a
    namespace: agents
type: Opaque
stringData:
    A2A_PEER_TOKENS: ENC[AES256_GCM,data:AbNgLVG1kg5q9w+nX4uBV7q0an7jgx7JWwdURnKq3Rm2Wp7r+7xHXx4zSheyS3X3u9s=,iv:G1ojW12Nz7cb5xa0NHs+tZToxsNSHdZT6iXTyT8KAAo=,tag:4AzszdAO6oJZDRVVYGtDSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMVkxbVNhdG10RzJSeGlm
            RXJDY200NkZ2eHNNNEp2OWFMOXNONml4dlU4CjNSTi83Z1BNNkhzMkJuLzJXNHZs
            Q0hoUHUwdHo2RjBEMXFUS2ZJQXBMODAKLS0tIGk5ZkhENGc3a2xTRUJFellJQ1Z3
            VmpFbkZsTGw3QkpkYmFHU0cweUMyWEEK+zA14fjoyTG5eBspiqYapPyPu/dOM56w
            BFq0I/bsMKHIo6dDZDZe6qdBVmOm1BUytanmZ09gX2ojhCxv44xC8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:57Z"
    mac: ENC[AES256_GCM,data:N0V9GYlo2o+DHt/qd1Ul5WLQ178Yy1crVOv6/enCk1zHDAiuDO+NsDlI+eHTyELbuV841p5ig4Gf5D6dU1zrLpSGGgQBbOH4M72OKdl0u0WXapE0pxM/slrTd73OYQUvD4UjaL5O6sj/69jGbvajANIpNZfL/PkBVPbCbXZOzcw=,iv:c4JR2KKFLV7GYfQxhPUHIWYMDA2kB0DXCFiUZLGy8d8=,tag:SjzVW7L+mNo6BNtEIrCR6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
