apiVersion: v1
kind: Secret
metadata:
    name: hale-matrix-secrets
    namespace: agents
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:4GJHyC8UwtWC7BsGwujjThVXOf0/dWlV,iv:a8BG44NGkOl1tFsZ3ioNTWmlql1ANuYLkSCigEofNW0=,tag:U2lZy9yXLh3hWxRqP6ZH1g==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:+eUbZUWkwCaLDDD/eaIvOMymZyE=,iv:xfrFq433zUkl5b9LrWCHQCkq9pY87Ccqz85ATvb/+Fc=,tag:lpyFaPzU/tWrS0givlYIDA==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:60anGuIwkIgb0Q==,iv:jlQABZIzUE0SXKK9f9orHkvrGo8eAv2v3MkoqNBWwt4=,tag:l2kOV6A0K8ARranWBBKt2w==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:LxYg/+rLPJo=,iv:s6UK0Yw6kkE2YlXA6ZmooLiBw24Ygw9EfKW5rqZ/5Wk=,tag:oC6h2pP+1Pc21SwJDLe5RA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:wyaLuBYhyub5ekmuplmHlLXub2aXKzuKb8IiZQ==,iv:Z/YWKbXTq1qdohZJ0yiRxJmEpTq3/bmcRM/TJymzQBQ=,tag:MKgELJ5zkDX1Qj1ny/0QFw==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:GL7Gq1o7CFN5E7ohq8EV11EZOI86Du4G,iv:4sWMHn+4K9Is+FhmrOtKuZnHlm3KVqSqH+Xiup34PD4=,tag:M4tewwdYBKXCdzirC7pNXA==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:jixo0pUj+6eBWkBji1OVJxPxrce/gQ8Vi+bGgNm7Kpq6viMcvsJSVp1XyMNMATKDohOTUcmJIzCQy6o=,iv:IOwCCUKgObHgRS+e0/aepdb3Y7y43L8BzkeDnnYNRFk=,tag:MB9te1BKHa/1eQtp2Cs6IA==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:QnwGBA==,iv:f2ngsCKHfZ/6uxRl+d5NJJ7Xg7melQDxpts6sbxdPL8=,tag:+o8gh/OWuGdkmGMgbt7ljg==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:8nhDzg+M3vqbYKoeRV3genGgO7N+ktx8cNBh508KPuAWbvCs,iv:yRNS/oSgOS2epl5qv1nq3wc2pT2sKyo8s46iYgeUdtA=,tag:oEFL/BB44SOQTn0tXKiISQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQWNFOThNNXl1UW15Vzh0
            VjQvYms0WVhHbmx4VzNCVWVFdjQ4bWRrUFN3CnlnR0Y1YzVxbktKcTdhY0pXd25Y
            NUlVVmpQVVRpdlRhMGFCSm5CWDI1VFkKLS0tICtEUlVwTjZJZHJIdmJZN2R1MkRi
            NS84dGt2b1d6bVBPbVRZWVlmc1FnblEKECFNfqQbNGBG+UEPfNzmKXM420NZq6NB
            c+si6sFbIzr+nAK0zvh8hLcjqyajvWrrpf539TFzbbSVXv/hkVURVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:56Z"
    mac: ENC[AES256_GCM,data:HozVX/K/oCWgg50EFCHXmY+DnOxS6Diyd7Sml1i9ZeW8FMHffYL83Zv5eAFAzA1ysPWSLLtS2gruhStVfQCVsuAMRYgmJlHFlVkh9IcPxvRL6dqhnB8pU7hN11s5RojAkeMjr5g7nsqvonqOaQR8Pqj1HZwtbIgE/0FPChKvv7o=,iv:Pyuv4ggiOOF3L4Wgh69ced6i3mhoLz+PI0XZjwMD+XM=,tag:RZ2etg1MM+ugKdmrVsPTiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
