apiVersion: v1
kind: Secret
metadata:
    name: homelab-expert-matrix-secrets
    namespace: agents
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:KieBDB7KLKzsXpA3IJEyUVm7Ug3rzLs6,iv:5SWATxY+zKov6WdFrxpqzRzp5amszv+uGj2T5bG+OMo=,tag:mZzhXRDc8GAu20c3Py3tbw==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:5PSXgg1WuA4qW/OlEyg6+7UyqL4=,iv:qdVSYdROeDSsi2ONUieqrKuJSkj+t6NEaGCzyI8yA7I=,tag:Nl3JDpj1xe3ezxLXK0fKAA==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:qqwjox+x2dzlgA==,iv:FomVcvKFN82JRKZR5iuDCI18njNiyBJFz2t/xX9g2bQ=,tag:c3qDEl9hascltkfW8LDLhw==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:ClQrWkBQQYQ=,iv:SuUIe3tIM+0Qix2NLRzsRByLr1kv2GoW35+Dwy8Tx5Q=,tag:RUTMtyqeQ1zgtqJUGBdu7Q==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:nteV6q3seO03/6Z922OUcPgWbCGr0QCrzM0Otw==,iv:KM6crz9TSEuatI/ZtiL/Tjv0JE76xBI+Crhjuz/UDPQ=,tag:PEOlpBTJ73SgtvgQ/NQqVg==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:b9aUXEjFVToexAJntniiazOa6MCjBsM4,iv:/LKWk4gUA4T8/8pHYFLE416LLYiCrMHS7pejs7uAnr8=,tag:k+IABFFr/1RsOi0x/+UJEw==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:J31lgFAIKzTdCpSRjc2xMARwMwe/3obwLOAgHawUr0Hd6HEMDY7GG1b8MqSj019hVfntXfJwgYznGUI=,iv:1lPVPfcheFmtbdacs5qoaswOxyX2q5q461JhxOSyS8w=,tag:ZWJg2o7owtvjzQKYI8hX5A==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:9ayG+A==,iv:HGS/biL2doehPQguVVOdaftufFBhQ9yq3GJnfJXXpos=,tag:5Pu30caTpZ4BMsKG/Y7hNA==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:f+bavtqTFwgy6E+Nljgod1MjESlGjQQ9hgfJQQK0MwLmJm8t,iv:TVJoji10grNsjhLza+eJpjwlR7sKxfVeBzYR2RJnMT4=,tag:yD+J9Q8tMTpZVsrZihb9Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVlUMHRYWlp6dnp5elNR
            UU9MVzZlK3c5Y2MyajRONEtja2NJZFdmcENnClNDU00wSlB0cDh5TUdONVJnNGVD
            d2ZrTkZmWHZ4Z2k0QVl4K0xZYmFuSzAKLS0tIG1KYlBNMjNWeWJXS3pCSGtNS1FV
            TGx5bHhBcG1BQmVwc3JUWE0yd1JoSmMKx9MpkuOYdo7rkMOl3zkr0SgR/D37jFRw
            onEgyCf9SIxD07/p9Or8x/yZbEAM+l1NYG4jtkxZsA6tqOKPpXUJag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T19:34:59Z"
    mac: ENC[AES256_GCM,data:JGHfcJz5QtEZ2zv6Tc46YxmHKqvkceWdvaiUHo8O5NwYttSCEdHCDk04kwLofWUamobxsNZQR4eS2hjRW8Aa5zcO74bpkcJbhfD3rRy/8mTggCqFWau73VWfjga2MkVNA/POPqfM23rUUsc6LSDHdMkIUL8jmq7mJmq7sneIG5g=,iv:8gY95+L/VCPb3ROgH7wReaTxNX2BilKvcajg13O3LKU=,tag:mZ5BI/G6dISW954AerB6sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
