apiVersion: ENC[AES256_GCM,data:ifw=,iv:gD68eQGHOV0v9kvDtA7ixpSHKcn6xr6MVXIe0yh057c=,tag:REf/PUHY7LOemFLvTbFiFQ==,type:str]
kind: ENC[AES256_GCM,data:IQ34vumA,iv:WOmY+HXBHmqEyOJ8b5RZuTtf5asZI06IUM0By55OOqE=,tag:MBgkVYSlnwSnUONJK8OuMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vfRpiTZYi7QQXJDfPaQ4A5SjFA==,iv:tWmD7lV0dHeU6hzK92W+F9BQ5Chwv9wrOM5qVZDTrRc=,tag:qQmjwyFVhKQegKRKjl1FNg==,type:str]
type: ENC[AES256_GCM,data:Dipiz8wc,iv:iFRMw4FgiG9bY/j7x8lYvMEbsoycL/+0NyB1UlOrNwU=,tag:AwTSzls7Lgxq69ZBChL0+w==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:FC3gux1WMWWkG0Wl/OeaA49zdrlj//u/Mup+NMEhhGQAtWZv,iv:fpMv3PLDcD7AWGZ0yx9+Ed09y4qaKyv0gsB1/JFX39Q=,tag:Ld+qoMcdeF69qRgztgW4Sw==,type:str]
    clientSecret: ENC[AES256_GCM,data:RxJvMv+ILYsOrJ46uIseeoNyrksF2QzYRxWu7/PYRGQ=,iv:NE5FZqkfjlKRueh+jKhP9i+8tLfj0zwyuFzGQCpUJuo=,tag:BK2IsYHsoGpYCfUUUW8QCQ==,type:str]
    cookieSecret: ENC[AES256_GCM,data:EVE7V7rYn1u01z+gOg7F5s1hLyZofrbFL8JDfe9jsA7DPdiuXcTEr4oROgY=,iv:UjYdTwmLNA72OsugsjMJQN6mEnVv7inXCGY+iBvKjtk=,tag:wRNFXaUGON1jayxurItXSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZjFWR0FtUThQYmVTSTBY
            MjY4Z0V4RlhESmh4SjNmR0syVGNnaDBrQW1BCnZlOXQ0cmY1NWhpMUJYSDdSejlV
            bmxJd0VmMGh4Z1dVRHduQVhKS1ovZkEKLS0tIE1kNHQ5QWt1WUhaaGgyOFJpTXBr
            c2k5RHlPRFR4UHBaNFU3YnBBMXZvMW8KMJpnewjSLkKPLWF32nQjqfIReqIxY+YA
            vz0qwcLwFCA9be8IzslJB7QuDff0ba0WGIL3v4l4Xnc7+mSWLxdl+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:14:12Z"
    mac: ENC[AES256_GCM,data:r4hgesdPTWpUDKRIFFuFNtww6O62i7m7aOLQaLHRBdYYAr5EiHVpVih5fTrYIM0eYg1XUttVqlQmdLxkI0XB50ofM0JmXGq1i1BvOiHURwx8QdQdtmme1KXutFfqg+A9KFVNtYxdPzkQbrCcLlavB6nS9RI2LriwEkJwjxkkcTM=,iv:wKJoA+NrVMrNrgLclpyvwwTnw7XYp7TWof6F6p+zUEQ=,tag:oSOKWuv8mpYUhpE7KXTL7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
