apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:XTkuUoDxE8ssWdE4T2U75X0+AqlbmsGxUj6mWUMC8ktzMQRG,iv:+O5JtWWYsz+UiTfs0xe0vsYAT5PZs3V2w6aYbA2PaoU=,tag:vqpccyHMAqBpNMW5iCYZ0Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:/GmtHS4/z9cyASi+pCZx83WiJ1Y9lNWukvqHE+aC5EM=,iv:E/AbbPcYI4Wo+wm+6V+ki1k15yTRfcSXzis8xoPkvPc=,tag:LW6614SB7EycaqjNSGGyaQ==,type:str]
    cookieSecret: ENC[AES256_GCM,data:nZM4AEb/D7JtB+l17h3tCmxAGZEhr7+YRpWMYInBGna6IqEoqmxYY91kL9U=,iv:raKPp84LJmN9v6gCQgJpbrXDqxsbtCt+Udi5g9H+PTc=,tag:/FaKFvBtIx9a4wTlTYdnIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSW5OTmpkaDN6ZXNhOS9X
            RXl1cTJMM0ZzanZWekJCd2xma0dmNUdiMlVJCldwRVpvTTI0SjNRWi9Zd3JJd2w0
            NFlpOVZva0QycTc0Y3NHd3A0U2RidFEKLS0tIGRUemxSQXdjTlBYWnNDUWM0WjZa
            YW9YWk5EUjBITS91Nmkvb2huY2xORDgKJPQXZpD+JWU4EsoAALDSDu1pHl1eQljn
            FtyuvzfTYj7xDhxjzYOCEKe9Y3Uw/N3UGb+fkDFShH1JT/lzbYcxvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:20:56Z"
    mac: ENC[AES256_GCM,data:mDDa9EDdKS1tzXZz2FBWMq69dd13B+2GwVtxMRQkXp03mlpno11S3+1xirTgYccv4VtlzCQeJwnoovDTI87Ox+JUJEr1ryjeWKm+qvZICcYmj6RuShUDf4Z2xFcqjXGMCdLxoiVHTWGsJ4EqnYtOOlGCRJR6SPWJNJE4RCJcYs0=,iv:v4oKXz1JySAeHDWOE8PJtSM+VtRJBPNKCOewRATN1Jg=,tag:Ph/uwK5aEnsz7nhf6CQjtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
