apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: honcho
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TMdS3Kmi7Yb6bL5R6NW3Qie2A2WkoXd7rOa9muic3dfKWmMrNNoz27cYbOX88j2WYE/sxfQyEkvOuzB/MqSQqFAG8sfJ9JLu,iv:mUo0/1TS5JNJxUdcPOlnUN4XVEX9drzrus8FSQkkmbg=,tag:29pcTPHwG2gCyYpZpGlONw==,type:comment]
    #ENC[AES256_GCM,data:N1wMvEpmbqo8LbTZiO8d9m7Px/KBuAvq/3Tc6yfWJpP2jO8t4XKMwADvTBT7u747uWTaJbbdfRzDKr8xvVWR4SZsZ+o=,iv:9eMDvwkjMdsroaqYbRTsqAHDNeoFd5Dbz5KqeBpNiTk=,tag:oCltuAN/FoFuJCpkwQGxRA==,type:comment]
    #ENC[AES256_GCM,data:ZFK0zJQ0Jv3+QtAgqARZVEEayKFfKDDBzdPNco2Rm114QGHS5ekyU3kLTtgmTzVIFM1lJm5RoPSZUs6Osq4kNarlwvJqqsnzsw==,iv:5UAEJ3VVEFl3uPhBCNpHn+DM+8Rk+MTBvAFfYVfvlCU=,tag:B+2jYCTQW2DZECfpBjVYxg==,type:comment]
    #ENC[AES256_GCM,data:+hj+Z7oju9lQM9eV4LpA4ODf8a634BV08tNhv4/3Qs1rpMC0lJO0UaPNvha7cGpBgFpWJ2RzO6IgOV+U1kGxWL59oI28pA==,iv:8ZC1S4wjNjQQes0Rd/iyTvAKMPyej09zrqrRpotrhyg=,tag:970CEp9MwXWGbK7cPNNyKA==,type:comment]
    clientId: ENC[AES256_GCM,data:Ma+RIcz+4r6L3+EfozzZi/AWvQi7uPQ6B/VHJ8Cn,iv:wyMzApCMHVC94MWuyhYuw9pCNFEBspj25X2l20PmfNk=,tag:pIartqYdoYupEQpXlwunUw==,type:str]
    clientSecret: ENC[AES256_GCM,data:BmuSh9QiX9TLG7q2CTb1y5w1d1VAL3TU8VqHvlmLDowDQg==,iv:HPgfMwM6qpcSLs7r8nEbWJdM7TcCY1wNaydjS67Jibo=,tag:Sd01ybSM7t2QvDRxTuaX8A==,type:str]
    #ENC[AES256_GCM,data:UZIr8B07E4yy1oep4Mz6J7wdPU2rWOoL6A0nW/+1Wuch8QePi94Qcueyu1obejTeCZXvkrmV2TJc6yLYFfhYkdhyUXCICEUdQQ==,iv:HA4JhI0ZP8UBFFzcbacWb7h4ty0VYkGQMSuiwG83Ogk=,tag:f2/9h6QuJTQ+Lym4ucyH+g==,type:comment]
    #ENC[AES256_GCM,data:I6vWDBXsj1Htwn8j0ZaZnBn5RPTmbLZE12svakjYuzSwv6ZnkMCVbbuDcGyimCQ=,iv:8Tl812zvickTwkZO68mMNmRl4zjEzlQGq1lZxZJJAP8=,tag:tyUxZOzTzBcS7Q2d8tNlJw==,type:comment]
    cookieSecret: ENC[AES256_GCM,data:KGHUAfZqLLFG4mZfVl8bf3szrDM/U2E/QHovkn4ozT7FLzbBcAxMQgZvyVo=,iv:uIvWzUilBuOJCZNNn2VQ3G5UAgjNthXkMoSuzn1Qrw0=,tag:cqqfNNsLLXw8j55axUnigA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUU9xdXVwZk8xYWg5R0gz
            MWJ1VXFGT09nSVhjVFRPTldKR1lrNVFKOEFJCndteS9QYVRaTFovNVpiWEhNajFN
            Z1hDR3ZjZ0ZVMFRXM25tdjA1TkFVS1kKLS0tIFAwenRnYUdsZTNtVEkvYkFrQlpp
            YjFSRTA2dlZZb0dWQ0o2VWk4MW1RekEKIy4MOjGBRCGebrVsO48kVqvXwHXGJ5NY
            Jcb0JQhn2kKPs/rSHOw4TjEzH3aRDpccPLSU4Z11IMKH7wcJ9KGpbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T17:00:50Z"
    mac: ENC[AES256_GCM,data:4VIAZ5xaMrWoKSKprKOe7yYJZRIxcBSp7/JRoMSNqJcxpB9nC71u3N93ULXRInb9eFA9tf/8Svaw9XXiSKGM+1qeMaDBJ7Y4VTy21c1Eg7s3MMLwIBKiZtue5ygw1QQStpUSxR/fOeiRs60itvgF19jS5ArxsoixvIjufttL5S0=,iv:RI/j+1IwlHmb2pLvCT93C6D+5RIF8vT5bMo/bDUTYCs=,tag:XSktZpCoJYjvSWC2fBMOvA==,type:str]
    version: 3.13.3
