apiVersion: v1
kind: Secret
metadata:
    name: honcho-secrets
    namespace: honcho
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jXrCUvGyHKCmcxbXN2sli7ojrpDgp+xUmzIxFEaPjGLHpK/KqxEiDUuAMPG5+V3cGEoDzOYLASxSEs8S744cMzZB3Q221do=,iv:W8fgzha1Zwi+7uw2tf8ozAiiegsAQqbJhaAsjdBwaIE=,tag:4MrSAOG/DHSTtAY6U+fAZw==,type:comment]
    #ENC[AES256_GCM,data:3/wfTygkORwxcRf8fSKbtHA26Fva7dUTGbc9ltwYD8nl6qmABecXgpb5wnVr9BFpVAkefc5bCD4n+uGt4pHBESIUeg==,iv:x1RNm4oS88o1JwM3lpD85FhULEAhB3PNmuwcfd6DA28=,tag:f6B3ZMGHwlO1V3cnd84PQw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YEFRC74Xi0q2RI0Zt8V74u2PrpUrLAjRI55Ln0MHFhZe6Sq87ST4La5Qgw==,iv:U9vIQzAMgfQh87YVMfgP+bb/Uk23aGN1u4PQrYVEDa4=,tag:yiwDnfpMi0hpQviTLWnZyA==,type:str]
    #ENC[AES256_GCM,data:ZcEtU2Ybl8k5/gxoGJH3eY4i5px0RdZYBFeeWF9/YUgiGGQC2MT5C+Zqv6hokZy+Qlf+h4nVFBvL6BIqwBNISFbaOkVbMa0=,iv:TvCuOH6/c8y2W56Xfpbr5+0Ila+bs9o2GOSzoDfeVCc=,tag:AsxepZhC6Q5FgO0Z3sG+xA==,type:comment]
    #ENC[AES256_GCM,data:8PWAJWjWf08dHNDBE6CF7wKtGKrnpTAH,iv:GpSsk0Hyj/FwO8e6E5TCIlpxLNktyvMP79DerxvYXCY=,tag:fkl0wmT1A4p56aM9Fe3ing==,type:comment]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:4AJc0c6Q7cbBAO1dYVttiRq6BOY/gHtb15PLq/DawpM3bJEB4/cOVf6zT39bvs+D9Zda8J1Ks8QoE+kOpZ4AgUsYfVU/UjAaFFLHBX7GSRAbTo53BYbPx/1nQ0HTSJEoOTfK,iv:SpWi61C1OKXMpQd4KjAqa2x8tC2h0uDXuaVxkCdVlQg=,tag:ZB5S8vUaCpNcHAzhZQ7bfw==,type:str]
    #ENC[AES256_GCM,data:DwJhcTjoD0wrEMjBDdeE05lQYrquLFHiE5zbkWR/YVrfdsHULzIDCZb1w2AmInXvkPJ3ctzYcE9kWL964Gpvo1DZ,iv:zZOCJUy/u9Z9O/Xz980H5JCpvZsUPC8o+7y65FjjfNY=,tag:Tegb+ncoyVxCqCc9zZiq4g==,type:comment]
    #ENC[AES256_GCM,data:YbCQAYudct2kTrSjqd+bC9URjx6xXRzzeTXGIOSWTu006Vt9IwFxV3miYhI2AM4uQks=,iv:qggayL1RlJ40YqQceakwoFRwaEGE5YjAm9X8jfJpf1s=,tag:fVi0AqoklqYSfdEOJZpn5A==,type:comment]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:etJ7Ezti7OA/ctxcxlL4SxGVqaQ9bqJu2UTr267dUuisxW7EKvBG/q+yvDVq+3FwcPD55y9O3SqQhwi2B/Mfcg==,iv:tzRjvu+3XFfHfoqjBWc3/JX4WwHie/3nvcNrgtYKA+s=,tag:ydbcT83tyfqJHOl/YDZu8A==,type:str]
    #ENC[AES256_GCM,data:SbP5XLkPcapad0bw/OXZpCmBG75R89kgkw0SKdUOPHzqryl/EaJmUvB3one9rqkKnI1T2ATXq6LORgErZd3ANeV0lBRy8KXBIsw=,iv:Dr+5tTw96PJgxMdugvK8CtPImxDFWu66KekfXMUsKbI=,tag:N2xrwjgVZnFn4JHsZK2+yA==,type:comment]
    #ENC[AES256_GCM,data:7b/7dm40TeCTCj0qGS+GIrIv1rHJG6OndI7y9DoB6mJZNJLa1lX/jBSqiw/DgvMb7NNIurpb021GaiiopalKtETN+ARr2w==,iv:24ly5gZ1QiWLxBFWQ3XzfUPajD1gljV/SUqs87THAFI=,tag:Dt+CTadjDXa4cjGb79t3qw==,type:comment]
    LLM_GEMINI_API_KEY: ENC[AES256_GCM,data:qEuvk0CV6dXvZIuAhFL2cIDyMK6PJF8cmwR9Qdmt,iv:QWAb2fgkYC47iQF9K/lfag6QbTiUiRw0hd9XvPWaHos=,tag:BeuXd2H7HSYgSJyIa/H6Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRemZEUngwNkxURXZ4ZDJx
            U0k0TkZjRDhIV1RCcVlMVXFqRmQvaEllSmdzCmhRUjR5RHFPWHVjZEdzRmRROVJR
            WEtpcFU2b0NhQldFbEZsZW50WEFrZm8KLS0tIFQ1WHNlZW9Md0ZwOW1ZNVRCMmRp
            Q0JST2Z4Y3p3UElZVStzUy82cUdWY1UKzNvL2hKViyV4N67xY1GHjCh+04xlmN0K
            tiy1HEDd5ywB3uIc6thVBSYRz7zmrjJm91dTmU58MJdUwlQRLaCgaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T17:00:01Z"
    mac: ENC[AES256_GCM,data:+hZbbk9ExQXfMi6T1kwm3XAQ9/kysMnBTs7SH0OdoLdiVqHo11NNk3F1NY4dK5OtPsk0v32mtUqParK8QSkMPaEJlqexxYxw7W3mV1dm/9bz/FQ9Sij07CD1ExxJN8NHIC5tMOfRFvHOyFKFoNFTG952akYXAhJcJeLF9XYurno=,iv:u/mOeVIJczdzHKpArkyOUxNhjToclfnU4syinknsJ3A=,tag:pnSreQxKoFfF5McmtE/8lg==,type:str]
    version: 3.13.3
