apiVersion: ENC[AES256_GCM,data:zyg=,iv:ebool9VI95nV6E/QSXOpSEUiDBdJ0vb7e/EjsBLebkk=,tag:UyEBEgCiArLO+1npd1Eo9g==,type:str]
kind: ENC[AES256_GCM,data:Kl0Zmm3z,iv:1tRjEJOlkX/WgrRjQLQo7dQPvcAx9hU6WRjnUBwBG0k=,tag:1nUBy4ZUbfAteRF23NGYDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3nyXdk0dmgOX6HJ/4FdZZQ8qE/VRj6np,iv:KP2HL3YVzY6wt5RHi39eZ6CX0o4+3UNWaDYh3o5CBI8=,tag:Bf0twgkLaZN3fZ7g1/HS7Q==,type:str]
    namespace: ENC[AES256_GCM,data:AkjJZNiunA==,iv:Shet2gjNXrqc9jQwwccrQzfMhCntxfdwzw5ZivJFHJI=,tag:VwsOJxEKwwWEQ2v5usJA/Q==,type:str]
type: ENC[AES256_GCM,data:TmBZ52zY,iv:iMOh9SANr3oYhhiLkDPICQ5BYvZhnssJ9wQk+h0+v4E=,tag:2UJixUhWQsTrDYi0xiwHOA==,type:str]
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:fnkdGR910r1/I4Vy4ulZ0wqnu9s25YyrC+wQtEAySco9g3ywfiw+,iv:coD3b8yZ/kZnUA28fPLdkQB9LtnNS3w794rJm1IQ+EQ=,tag:Dn860qrxtBcWGigyg595tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWXhiWTZ6ekdnMzBDSERk
            UWNZQnRaRytFSnN2SDJNckxYd2Z5SHBVVUc0CnFDOEpldDVBYTZhY3lUZlA4QkJK
            ZUthNzExbmRUdFNQaG85YkgzaDFEazgKLS0tIC9WaW5PdWJpQVMyUU1KWnpyUzk5
            dEcvYmM0TnVrZytJbTdweS9rcncySDQKMF8fD4UF0I+masyNyLCCZbss3N/vgHnI
            tK77d/2UivzUoTbsjY20SpThCfXo3DOQ74A4ZZy0vyVWUe8bH9vjHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T21:38:43Z"
    mac: ENC[AES256_GCM,data:gsPAKqJ46T4psHuJx9/GgZtcTvIJJaMTgVdl5Xdx0+PVxfFldS8kc1Y/iEFXtW7+DSxVxYGsRTmmvVWib5y7sPHEcg/+k8Qlm9zdGnNMp3BPAde8dEGiqIT79awh6M+kI3X8chLn472GyD6jEznqrhLWDRymtzOTD+C07Fm6EiY=,iv:rOubJhwX5UckW1BqRcQM9vSGu/PCmy93iUthsfQw1vU=,tag:tHbO+Lyv+zmno47vDrkizA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
