apiVersion: v1
kind: Secret
metadata:
    name: syncthing-oidc
    namespace: syncthing
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:V5JrsTBV99rOpwF5hdKGk1YekkNHX3+WfpDgclboMYg=,iv:P2zDz4meEKuGuDF2FgINKbumWSTeqHqIUqCycQzW6o8=,tag:g0uTNIIcAYsVRuCDxC+JFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WTBDc3VuWnp3eUFyZFhP
            SENvMDBKbjF6aGZuUXIySjIxaGVqNkdoT3pJCk5HZ3lBMVJEaDJzKzN3cFpzR2pC
            OVRzbkY4aEpyN0ppbkR5NEpKTUlFekUKLS0tIGNxME9SdUZoYko0V1V2Nkc5QTlw
            N25kaHlyd1BGbURxWFE1c2tpZUgzc0EKmihaZNtYsjCFN9EFCtjoZvpzFSuih1lw
            MhfXaXITipsfx/JaLZIPymP3hFX9jxWoJlPa+esQ0w59hh1dWvtVeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T10:02:46Z"
    mac: ENC[AES256_GCM,data:sdYmvrSoQQAkgd4nbX/8+Nbjp4yCbnNmmhI3lPHY/UQNweaYmXZOGFoG2NwWKVghdPlhgf/jt9FzIAyKtAYgfpGTzFsWT3XHoUuO3r3csa8geUFCoyj1dK2DaEz+Yor090JuwfdNKox4f+NEYs3ENCA8bEs6DUCXdPxwy52cYhs=,iv:5oUsK6ANuU0dUqlKx/HqJrFHd0saUeSYU7mfNtQEZ9g=,tag:En0VmRiRlhXv/NXXEXegdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
