apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - httproute.yaml
  - secret-oidc.yaml

configMapGenerator:
  - name: n8n-oidc-hook
    files:
      - hooks.js
