apiVersion: ENC[AES256_GCM,data:0U4=,iv:dUqJ7t+SDXGnO0tXc4mddoLScQaBBYEaOP5CzS+hVIs=,tag:40v5/Gq+TrhyDB34Z5jLOQ==,type:str]
kind: ENC[AES256_GCM,data:rcQuFESB,iv:0Kbm/3Bsfyy87H6niWpS7RmBreNKPJXMNFcqFMb4kGs=,tag:nAMwHlOrIaD0LvWgrj9Zbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kI4Dpon4pSM=,iv:SCNIFEnhWBbzMbrYTTAaUeGwuhLIf2ta/Tf18GQtHc0=,tag:zlENLew5DLgpWzgpHMEw5w==,type:str]
    namespace: ENC[AES256_GCM,data:Zv5o,iv:CDVWS9hnUm1vEsMeZaYNZyvVfSlBnazBsPbcXkji7WE=,tag:P+IyJGqFIdbpjqV1aOQBNA==,type:str]
type: ENC[AES256_GCM,data:iygls3R3,iv:58cFC6qFlOdSGJcPNVtw2gTrxAZZW8Ribh+5ee0OYvM=,tag:mSxqbx7aXa8Tx7Rd9L04KA==,type:str]
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T7M69WucVYHY636usT3iuTDKJwLMZDj/2ER/vS+00NA=,iv:W1PMUgaORwwqIoTiwAjm75pZVG1adwscTr8Ns7ikDRM=,tag:A9yv6rBVwkRtxsPVsDwy+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOGFSVk1uQUZzR0RiR2RS
            alh0eVN3Qkw4cWdPbW8xeGFaM3dKam9kclFZCjdEQlRIYTFPM0Zpc2NMQ2Z3Tll0
            QTY5ZGg0UzEyZFpTcG1pRnJiM2pyaUUKLS0tIEpXSWNEODJhQmsxYVdDd2Y3clhY
            T3FpUzFxcktsWXBmc1pCS1dpanpVemsKYOdrWUmYzKtmcM6WDZewtPwHdkt9ZR8V
            d2BA67Gi5J2IdwJ13OP8/CzJx9MKFyZB6XKVQx9eORp25oqG1VLJ1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T18:19:12Z"
    mac: ENC[AES256_GCM,data:fCz74BAYVF/EdD05oOXukrwBvVP7uE5yFde20rimb8t8q2LBqPWI/jy92v/GVniNuFUTsVaQ6Y3UuEm8aQPOTKSe06xDo2CRwCSDB1+36C6w3CyCiL2PImunq14E/JkbaSKbSLMJvI+TtuIDtqqLAWGhN+qZNnad/av0rZtXg0k=,iv:nZf3h8mj9Grg/od1u9+xnUX5tPi6aH01JJ3OBVeS+n8=,tag:FvDGUg5PodCgrZVHx9CAmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
