apiVersion: v1
kind: Secret
metadata:
    name: n8n-oidc
    namespace: n8n
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:BDIFiHfATlv5cZ+BKvkngOeYldoacEOfhkj/ZoRJlX8=,iv:98TQzrUHyfhlZ4aiiDWzk/ABR0kG98lJz259bGpVTD8=,tag:yxjvRUr4Syb8BRYMyO3NZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeVZmdGZObmxVNHhLNjNl
            VjVESTBxSVc2dHZ0d0RwRzJlV21YRm83cGxNCkdkNzRFc0ZHUGRNMWplcXc5bE1H
            QmJiakZoOFdwR25kb0xMN2p6bDNCUzAKLS0tIHpGUG0wWmQ5RU5TOUZmemk0Sm1h
            TE9Kcm4rWHdvS1pZMFpBb3BTaGMrNXMK4aAtbpjVMHTUJ2utEeKJlItdsAbG5cyy
            za1Dz9pf5oi4ALPKA5GsYwsuZRu7ndIz9hQoPiL2oune5+V1xqChlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T18:28:08Z"
    mac: ENC[AES256_GCM,data:r5iWFfCUi5ai27wLCqxX5a/jderbuoomZKhwr5J1Rsp4JvD+VADRj5gEnLgg/en2KY9vT9inqiwlTItse1G+bLo+ggIJoFKriVUmbnnCPzLfKAiDFQElCfReiaJOXKZ4gFjK7+aBWK1dL5IWPAi+HVqf3qUTkQOEpYjkclZv1mo=,iv:1XvIIuuX3dW24PZ/7fQfafegtyrZgAz8zjoMLE7yQXU=,tag:8oxY6hGiRMFxX9xOEFNpew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
