apiVersion: ENC[AES256_GCM,data:ELA=,iv:ZM07bQbUOgvH4hdCXqYA+jk0WL0H6THCsmftTwHVuB8=,tag:m2eujyt1F0sE58yR4BbdeQ==,type:str]
kind: ENC[AES256_GCM,data:y+a6cf+s,iv:4HWYn5kMG124IaioK4Jcl4RpoJDh8pYv1D0HREQYDRA=,tag:0Qxo78mpEPxWCTW04UcCEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WrOI7dmrc2M=,iv:oemmZnxyBYU8q9vSMu1a9EDKp8bu+VkYaLcRh1aHjGU=,tag:uf86mepVsY5xqlb7Q01OyA==,type:str]
    namespace: ENC[AES256_GCM,data:S9Ms,iv:dxBmOA/mi3gaIxCorY3hAr2c8qmLBkByOGg7UkD5yuU=,tag:o99ejf/RwaIkBVYZGDTn4A==,type:str]
type: ENC[AES256_GCM,data:sT+pVFFp,iv:ySqxqIRmIvDT2F0fm8j8ItBebWIgZvxMsyFCerO8Ttk=,tag:YUW2sps5E9pVK+yxSxwDpw==,type:str]
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:DrK+vKQqOXOQQcapp4+eUBjV+DYxWWmfECCeOZpS1l5OvDX4,iv:HIHMYDDRUgAJPGeC01aKdVDeUmG6znGv7gWcCaXXH4w=,tag:OSv48nbhax2QoaEtP5VnsA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:azHMAIQvj7gvYXFiTZ3pztdqL0FxW31/Yc2aPame5P4=,iv:XwEOZiemoiAOqqkwS71j/sKEq0487ycRzeHvbt+DCF8=,tag:WfJ+osxt1+p4gykoaey19Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUkVrSjhONUgzb0I1Z3R5
            TU45OUFmWHQyalpIODBwT0FvdUsrMUdUbVJFCjJ6Y3pGQmRYRjlCRDEyNUpQbk15
            L3VEYXpYVU5zem1FNFZPdlo5WWQ5RlEKLS0tIHY3aE4rSzNyVk1sc1JJQkRxajVi
            MERGU3VMa0tTUHBPRE5xWjV2UDN0ZnMKKs4eJI5UjUmuq7rpobvp9ZakSl0vR4nn
            xi5RP8khQk1+7awz9bNFazKBZaSIj1Fiz35qYCcIfDJh/wcBxRyW0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T18:47:22Z"
    mac: ENC[AES256_GCM,data:SgsSo8kqg/rU1Zwlc3ze1ZUfxAdJZ8Ae1ekqrRD6GxAwYhksX4LwhT1BWyXRLspMjG8AWs+QMbnAfymwE9lU8SCU5LtOPz9jUF+dF04TQjnT5CBMWOHwTKw7KUEQkYH9wBsd6blSATHcBiPJZptjIKzjKMLCreqVO9lVa07nzT0=,iv:Y63J46I32HkZ0WeZ+78kuj+gwa5s3nhfkEIVh5NQC00=,tag:j0lzOrlASen/+kMB3xKshg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
