apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: open-webui
      version: ">=16.5.0 <17.0.0"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/open-webui/open-webui
      tag: v0.11.3
    persistence:
      enabled: true
      storageClass: local-path
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    ollama:
      enabled: false
    pipelines:
      enabled: false
    openaiBaseApiUrls:
      - "http://hermes-hermes-agent.hermes.svc.cluster.local:8642/v1"
      - "http://homelab-expert.hermes.svc.cluster.local:8642/v1"
      - "http://9router.9router.svc.cluster.local:20128/v1"
    openaiApiKeysExistingSecret: "open-webui-openai-keys"
    openaiApiKeysExistingSecretKey: "keys"
    service:
      port: 80
      type: ClusterIP
    sso:
      enabled: true
      enableSignup: true
      oidc:
        enabled: true
        clientExistingSecret: "oauth2-proxy-secret"
        clientIdExistingSecretKey: "clientId"
        clientExistingSecretKey: "clientSecret"
        providerUrl: "https://id.kalitsune.net/.well-known/openid-configuration"
        providerName: "Pocket ID"
    extraEnvVars:
      - name: OAUTH_CODE_CHALLENGE_METHOD
        value: "S256"
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: WEBUI_SECRET_KEY
