apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: open-webui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TMdS3Kmi7Yb6bL5R6NW3Qie2A2WkoXd7rOa9muic3dfKWmMrNNoz27cYbOX88j2WYE/sxfQyEkvOuzB/MqSQqFAG8sfJ9JLu,iv:mUo0/1TS5JNJxUdcPOlnUN4XVEX9drzrus8FSQkkmbg=,tag:29pcTPHwG2gCyYpZpGlONw==,type:comment]
    #ENC[AES256_GCM,data:N1wMvEpmbqo8LbTZiO8d9m7Px/KBuAvq/3Tc6yfWJpP2jO8t4XKMwADvTBT7u747uWTaJbbdfRzDKr8xvVWR4SZsZ+o=,iv:9eMDvwkjMdsroaqYbRTsqAHDNeoFd5Dbz5KqeBpNiTk=,tag:oCltuAN/FoFuJCpkwQGxRA==,type:comment]
    #ENC[AES256_GCM,data:ZFK0zJQ0Jv3+QtAgqARZVEEayKFfKDDBzdPNco2Rm114QGHS5ekyU3kLTtgmTzVIFM1lJm5RoPSZUs6Osq4kNarlwvJqqsnzsw==,iv:5UAEJ3VVEFl3uPhBCNpHn+DM+8Rk+MTBvAFfYVfvlCU=,tag:B+2jYCTQW2DZECfpBjVYxg==,type:comment]
    #ENC[AES256_GCM,data:+hj+Z7oju9lQM9eV4LpA4ODf8a634BV08tNhv4/3Qs1rpMC0lJO0UaPNvha7cGpBgFpWJ2RzO6IgOV+U1kGxWL59oI28pA==,iv:8ZC1S4wjNjQQes0Rd/iyTvAKMPyej09zrqrRpotrhyg=,tag:970CEp9MwXWGbK7cPNNyKA==,type:comment]
    clientId: ENC[AES256_GCM,data:jMfX1jAonru4xm9wpvfNzPzHiM0aX+QE4bp7dsHQx2GkJ7Cr,iv:IK7Zg1G6vtex2TvsfQr0XIU/VR48gd8f3G0SQ5bP+Kg=,tag:9jVcCQqC1ruN/8R8nGbolQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:U80CtYvAVZYAWosETUivh2Gl6Vf7Kkp6GUMH/w0f/Fc=,iv:cFSYIAgbbu5vEPrvTVaaHTbiEPPsLPDOKr3WQda4jGg=,tag:ILp0EzPed55oiAXMLwaXIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUU9xdXVwZk8xYWg5R0gz
            MWJ1VXFGT09nSVhjVFRPTldKR1lrNVFKOEFJCndteS9QYVRaTFovNVpiWEhNajFN
            Z1hDR3ZjZ0ZVMFRXM25tdjA1TkFVS1kKLS0tIFAwenRnYUdsZTNtVEkvYkFrQlpp
            YjFSRTA2dlZZb0dWQ0o2VWk4MW1RekEKIy4MOjGBRCGebrVsO48kVqvXwHXGJ5NY
            Jcb0JQhn2kKPs/rSHOw4TjEzH3aRDpccPLSU4Z11IMKH7wcJ9KGpbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:04:07Z"
    mac: ENC[AES256_GCM,data:v4tziCESkw6zjY44Xx0aaAlactB/g7H3t8vQchZeZcjXojeB5D14aFDwiUFJKgmyEV0dEO/3l+wyYWf74av6EGa1lGoKdNgKtOZCrHYlT0O1x4GIkggJ6HcJrHOqFXy4OrRn+Gjvwn8PtUqle4fMdqdTSqdWbAeiVsNuC7U5a38=,iv:JdzCskYf3mSYwrCIXdfAo0Sph6Pgjt/xCjFdE6ezC2E=,tag:ytspN0Tv5GjbWNJICQmObg==,type:str]
    version: 3.13.3
