apiVersion: v1
kind: Secret
metadata:
    name: open-webui-openai-keys
    namespace: open-webui
type: Opaque
stringData:
    keys: ENC[AES256_GCM,data:80/D353TzakpIGdrE6BRrcLlodO5hkOeRa6fkU1rwN/NTju2QuqlZjs1nIxcrC+9wfRpzenuJq1yZVvCoOB+68nTgE6vMXqcCsnaPNcvrvrGx3Ko4ktRV/3uQedsB8ijGeRNwGctIAJwZNPVXwWbABmSX0X+hkiiu3CkyWT+AyxnMqwq7DM/0b8f6T4xHcaBVk4sWlLG5Edmd3s=,iv:bfswHgjF4BYc4sYk0cGAP8KnEGpePcmM6H4HF8pnbEU=,tag:dQD1hA8axKNGrHndvbvmvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU2UveG1pZmhhaDhrV2FO
            SWVwWGs0YnFkaXpabTBBMUM1RC9qVjJPQVZnCndtcldXMXEwN2JEcjRCT1BXUE5G
            THdxczhZRWtsY2NEQ3gwTkF0Z0JlelUKLS0tIEM5YU9IY3RYSHRaUFNnUkRTa3RL
            REdiRzVtSjdpRk1rbEMwNWNjeWx4Mm8K8pRQrBfilTRtRXS3dAhBlcFi1Qim3Pt3
            CrVMbC/SKiKzOp+eoD5FpSTMRf97myBkAqVVIFsIW7kRJDXpyor/2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T15:47:24Z"
    mac: ENC[AES256_GCM,data:oXqfQBCWA0tVWdBKlkrBo1NjB59fLT8FxahQFDslJf6pSmBnzbw5UyCvsO0IRfD4qZsHlJKdpS4OeQhYpHcQ7/taQNgCzPcN5y5CfNMV9nYyG43pH2RWmg/7g2CmS9npl+6bkYP6medaqni97nbzf5kSVXTatDVP8oGOCzT7E3g=,iv:tlQKBlDo/mBopwf6VS1HjLT/1Gt6SaEvNOYGZ5+iKT0=,tag:kJH7ZfXJBsOw0wiMUXwGNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
