apiVersion: v1
kind: Secret
metadata:
    name: open-webui-openai-keys
    namespace: open-webui
type: Opaque
stringData:
    keys: ENC[AES256_GCM,data:MQvYuV72pYy9fA7o2OuOK+Gbzo2yW7lZi9GnFCBtj9qs9/XfT+hsC43cgr+lOsiap91JEAmEb919NsxCrHtiEuMp4k4aZ8WJ397WSYMIQpjYH2SACJWJMEsPnm5EWe7ZaVFc4Lha5wAOYim0nziTIfD7RUzPTZWodckL+QXTPAGGN0kGbQWgW9qWvVGApwIUwXtMvdikKyEe+fs2vXlAta9yzHHqJKtlwNLFvJxcJC6B+kWlspjsol+O/A1rutvauuDTM6XanopAmNi4nsehOlRscgD8heBh6E0f4JCgueC7AkQ949oud7ahp+LvRCcSbSy/kGQy,iv:v9xAcQf3ckFX8rZtEifox+HYJ9EWg9Cc3Newy3T794g=,tag:rLYtBNDx7qjcyj/CnhnJaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSFZIMSthbVA0SWRrZm1v
            eldoa1VocUs0bzZaS2dBWmxtc0kzeWJwVnpvCnVnRWRobVVhdHFpdEZKeklSWXNq
            eTFhWHB0R0RlK1FNZ3U2S1A5SnlwNzAKLS0tIEJXSlliTXR5elYrZk9PSG1Xa25L
            M2pMNDFIbjU4THJGaWRYNkxlVXlVV3MKEsZ387kbjegzaWn0BkP0JpqaxPLiiANA
            q0/g9lHA2kOJA7MmVx0RRB1fJn5nlykP+ppgHAWAJh2TaC/EJi+sXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T17:29:48Z"
    mac: ENC[AES256_GCM,data:QNYKMCbnaOOUz1HqqAbgWXuMaURQ+iR3I1UTbk96buIROgebVRnpf1jC/A0Kiw0VpfnVv1k6KFr6L2+zNJ2tfFKvj236BiX6E19trkqtt9y8jc2hNepuV4Cg+mHXiqloU/BhHSqWGW7iju1wnpsu98NwGy4cVdC83erACDl1NO0=,iv:q3F2VI77t4LBR5b657y3HUczBhTBZiSQOljkMiRIBn4=,tag:flH3Sop0QfmYnd0x3OoVNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
