apiVersion: ENC[AES256_GCM,data:6l8=,iv:b9UkQXgugyPB8JGiJaZjAvHIPlt7NLW+vn9pZdhmbwk=,tag:N8qKRnbK6Bf3LG/drGd8Xw==,type:str]
kind: ENC[AES256_GCM,data:BzrxCCtY,iv:0gTQGcypW3T8PLuO7MUn20w6YFtjbzDMLrV3Ap6V9t8=,tag:cOhLKx63V1ME+BT/paWT+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xiBGCPZ+vui1rNcqdPImPfAoA57cuQ==,iv:6WOePU++iQMNRi70vECO54P3CzGaOVZo1TqAJfjG4VM=,tag:GL06dCLKWRGDDCmyA9LExA==,type:str]
    namespace: ENC[AES256_GCM,data:zdgYFsQZ0Vju1g==,iv:TxweKkOOEKfPAXohkdLOHh59LCUhgF67wKZgDI7l6QU=,tag:LiBUQ1LphfWtIzlx9TLXFg==,type:str]
type: ENC[AES256_GCM,data:AHs+aUBF,iv:7YyjdPtKORGqv17RyeYjml51i7OArV6mxvXZta2zV0Q=,tag:BQL3nLjvWHQYcL3bOizZHA==,type:str]
stringData:
    keys: ENC[AES256_GCM,data:KhSAtBdY+t7HFEXVKRbMGi1J1Wp2heQvmF68,iv:xvaK4zNkr3rafrg2OqhqNG4RFSg1kz2vEiPtME7Gr6Q=,tag:/zFL90GYvZLcyQjPfGN2jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMlFuVVRuVzd6Zlp0RFly
            MC9QUmpoaXU0aTNRY3NPZUlEQ1FwVjF3NGcwClo0WFk1ZlFQT1ZaaCtHdkVGcEVj
            TXVubG1oREF2Y05QU25KamN6Uks2WWsKLS0tIFg2RTEweGRCdHZwaVFSQ1I2UEtS
            QjFGUUhhaHhtTCtOVWlmOXoraitEVTQKZ6kw3VcaCqCv0CJ+O1NXgq4pruzfqVuY
            zkQJ++MY+H2ofKVfTRYtVungoiRQ33q3sd7ZPjKsBRsZ3Fl1hYegYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T14:43:47Z"
    mac: ENC[AES256_GCM,data:XuF7Xe415sTGxG9VZJ0FrXHyYbygosePyDjq9ElmdkpESJeOjMl/qVpmRS2YDuyMgjIDXh+bMLgnRqNMJx4qeKhXsEd9zD+tb4nkg6pFN9Bqwt7hrdAFHbFAKAPwgPxk/qrJSh4Xsf5Iys8BNhUgdXEM9SwL9JAvXSrPvEiKH6U=,iv:X1YW9N7i2TZ/VVmXMapJJbhBoMyGC8mTKcpukEDbJZ4=,tag:5wI/tmoa1mr2MCY14OcTrA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
