apiVersion: ENC[AES256_GCM,data:4cI=,iv:ZrZsmikrIZypp1txhBobhZ4LJQyDcFBcUmyA1JEzh7s=,tag:P8YQuZwx5faHYCSyTwiOUg==,type:str]
kind: ENC[AES256_GCM,data:HcoE89to,iv:BFpF8NXkNmSvZj45h+pwHnR6C9vBYWzPAlyM3WriDjE=,tag:E8Bc85iSNjU+oXNLxwj5Cw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5VxNnDFyfwDn/iTwxRE28mk=,iv:ZxBnr3JIO8Bz0OkCrJuvu3GB+H8+y+bNdfq4Ct0FMMw=,tag:IUw6D9ABGGaEG7+zkDxq5A==,type:str]
    namespace: ENC[AES256_GCM,data:2grcB5bgkhLctg==,iv:cpf4qI39JdcyN4zU0lTrWx+YvcpyAJGq8rSCSOYAazc=,tag:GMm6KiGFCRn9XXLxH+KI2Q==,type:str]
type: ENC[AES256_GCM,data:bu6pu1xT,iv:ocH2tFE2Vv0ld/WcTu4wW2ufrbTo2iBOYK2Xo8U6Us0=,tag:9GwqSQyM8bT/HQzH6IAAPQ==,type:str]
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:Q+jP/WyszfJ+SKaGRxFeW7EqfOR59ABEr/wiIRDL+Ak=,iv:lxb5l0tF10EtVLnCxQfmtMudGpduH+3dNIABN0qqr0I=,tag:kuBvxJvO6Wur0jffcCcRtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISDY1VVBqaVBLakh6c3My
            TWhMaHJMTjNMNnlZMWt6Z1Q2cTRXdm1TY0M4ClgxamFEYnk4VytQYnZwTGZmWERv
            Nm1ZcGFZSnFyRzVBQyt2aTUrcGpsMlkKLS0tIEZtTjhxY1FzUzVycnFzS0dIcG9I
            L003MkFyaHYwM2Q1NmJFeE1jcXVZQjgKEtAGNE6zYMO39wRLeSVGv7B9uOb25c+F
            dAjG8m4lqhHn781aqxSZRv6BZ+80+kWqA01uk4RFeUFM5TkZntsTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T13:34:30Z"
    mac: ENC[AES256_GCM,data:QmH7PRhsNljtGKwegABQsRL4iUCPfJptM3EnrnCaMVH7zGmB5xYfj7TgWdnPN37+YGSJGmFe6pu9US+QbdEr3IMD6tIgthNEgRcR5PBoaYBE89EuJTKPhd67fdDn+DpkhnIfhVSAr0SNm3CGDlB4yJNRAtL2wV2wlkaX4qPSwKk=,iv:nLR0OAHapC5AgwqJNXzqR3zWZS10226KUPGuUn/atxg=,tag:n9LGc7Mhs7WQPSHQ/JGItQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
