apiVersion: ENC[AES256_GCM,data:msM=,iv:0rRkVow1jO3BX/sbi/iidR5ndPPvQ3ELFtlCDFFqoNY=,tag:EQIbWKjkZxJjAYbbPcAh+g==,type:str]
kind: ENC[AES256_GCM,data:86baZHWh,iv:c05KNpSRgiTsqZfmF2fxD26t7kHV2yx00UYwALyQtfo=,tag:Phomd+nBmG2nNdmEYsaxzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mEaOnyd3xZTMfUvaYQ==,iv:pYzZcUyw9iAC5mDmYNfjLvysc+M++JMCxULMfK1W4VY=,tag:HYyP7Mm+MIgcSHOLxE86iQ==,type:str]
    namespace: ENC[AES256_GCM,data:lEnwuFXx,iv:d7K98ZKL1aicE89gpyD2w8fGLgiPO1I6YifGDyrowx4=,tag:Y9HaBZwTGnk/uusLJVxIsA==,type:str]
type: ENC[AES256_GCM,data:UZhdxwLw,iv:9kkreai11cxejtgQQfPiVbC7mhN5DewDnZST+4qDb3g=,tag:yOKoax1VT7LyOJEXwVyUmA==,type:str]
stringData:
    #ENC[AES256_GCM,data:YKNPiO0qOejP3xXFtPtqOikOhk1wMc0TdYKHvaPpIqNw3SwOOvVy9dZQ23oSbeGasGTv4QdryA/uQNSj9oA=,iv:RP0MfpjuOrvR+8IDfxJP6/leR9hi2svfCpN62qGe8MA=,tag:bdX8P3ruOp9bd6mXnc418A==,type:comment]
    #ENC[AES256_GCM,data:2dEPp6NySsqmHEj5qDWtWG7bPLNmbQBpfiv1eiFnbU/SK2vLLoemf0xlelQGtal0CDo=,iv:KMxgOS59c8pLs8b/xpSb5S9K7LPW9CJ1RGuXnpK9E90=,tag:L5m0PeQnN/6d67I/MuS2ng==,type:comment]
    static-auth-secret: ENC[AES256_GCM,data:c4TpASrY/rzilyfcDT+Lg7ZKE3oL78JDJ+z8a5sniS6JxPr6kYwZnnmbNGao/Fy/f3yGHAMutIrCcg4HWMnhpQ==,iv:vqLkw4pxCzvBnXxrr9YJA1QXi+hWA1nhS86K+GiTquI=,tag:dI8sgiwTOl1Syps4LuDIYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeHUzOGhtNTdiVktyK002
            a1N3KzZZY3drcFhqdmkwOUU2ZHpCc1RjUGo4Cld3d3hreGEvMlltUTM2S3JrQnkw
            ZGJMRUFybGxsMCtFc0FnRnl2WENhMUEKLS0tIDIyQ01jOG1tclR3RGVvYWUyemdE
            R0JBaDBSN3UwODZYcWFXaVliTVpyb0kK5Ja1a4/tcXFnlAVSGfX7BeN9gaKqfAcz
            RkjE9hypLY0NfexHeBxURh2NcIxlHQppjfVoVtOluhGA36JhFittoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T19:37:54Z"
    mac: ENC[AES256_GCM,data:JEbjRAyZFIB3X6nNuchjwkbPZrtNfdY6qstwebOaNLiL+P23baN9aSHBpD5EzkxUVJDRAho51LNUAaGBSZoFvwf5sHLYXONnXs9LLJFAOsZsyqe/uVzRZSMRLn6qgeSRNlSJyW5F95RutNv0Q0FZg7BnXZIZ+fzyFttKmGuB+rY=,iv:F+8maryB9EGOiqglJMRnizZD08ENnh0n9/vUUXx4zv0=,tag:sB2rnPL2PhRhWTlCkXs5EQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
