apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mautrix-whatsapp
  - mautrix-signal
  - mautrix-instagram
  - mautrix-linkedin
  - mautrix-discord
  - mautrix-discord-admin
