apiVersion: ENC[AES256_GCM,data:Lsw=,iv:nhrKYU9DdeuLb0+SCc6V6QhUIhv0shUCWF3OGwdKqds=,tag:NdQ2hji6dGdE1Xswtrt2YQ==,type:str]
kind: ENC[AES256_GCM,data:zibQ6XWf,iv:dOZyfvQcX/A8nqCR0aNFZFAwJ63L0wIYj2RQENNJUvU=,tag:wLHhMfBVOL9TFwpGnDFkVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0n0luWBwOw==,iv:P45MdbRo/MSMySA6VBzaXcsKZ7a1QE818Bywubr95RM=,tag:jxARTTfhWHQdS30p3HD1pA==,type:str]
    namespace: ENC[AES256_GCM,data:PgtcdBCxJg==,iv:yESqUtYCYKm8L1nCMFnxbCh7sPPJR5+V1v4jpIWCahE=,tag:5R7xzcY7AEYnaB0RYkDeZA==,type:str]
type: ENC[AES256_GCM,data:c0FyVcuZ,iv:74M0XbEkXaMPWGoYNQyleMZ/OX+WrfmFRYIoUG0gh5k=,tag:+FZGSxpWCIGhOZeXXG4YJg==,type:str]
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:lh6us1I+V9GO7OjVLpVt5NqVCtl0R0AnP5rE69Syf1Q=,iv:WAa0htF7gVOh/AcXdNLQcZ8AFf18TsPzIJQ1ruixbrk=,tag:RpcsZdKj2EdTS2AzrjsmYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaWJCcTl6MjlkOHBKMzgr
            NnJmTTI4aGxocXNuY0hrd2VlWllnTHhYS1IwClVjeUpmcUVEWFRPMjQ5OGJ6N2J1
            a2t4SVp4OTNzSlJoR1A3SDlFU2FwTmsKLS0tIGhWWVB0dUl2MktKNlp1cHl5eGlR
            UFBpS3FyWEdza1VkQ3k2eEl3ekFhakEK/7QO4PlZ1U6MBIbmj7x0MkNliWg9EVha
            i0ajUeGdXPG3DFwazQp3wmfbGYUFfRP4rtNFMsU2vzuL4honkqsBfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T10:50:51Z"
    mac: ENC[AES256_GCM,data:0C8O/slx6Xnvpk/pjtpTPeWTliASj/mWXsllupVwHCIUzMDrdqPYBmM1sC5KeGID+FFZ0mKEO201CYW5u/suoD/leSnHjB5ywi3QrU1rrGgCtT7zm0aV/bXFGHxN7/qMN4rJz6tu1SuYkTH4p79HArSVh3Jmt3zqvY6Cj0Rqlr4=,iv:AvO8u6YeY2qxN8CvMcS3N94MEjQ+NjSNA0IunM4VRaI=,tag:WK20Fr301PjmwXTE9tZZQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
