apiVersion: v1
kind: Secret
metadata:
    name: finnegan-a2a
    namespace: agents
type: Opaque
stringData:
    A2A_TOKEN_HALE: ENC[AES256_GCM,data:wjfXnev7gpueILfcsquriJfiXsbsGRqP0uUGYtxpKIsVj29BLN+sFw==,iv:1aYJOYx804WZj9PsOVuxwwle8lQPXzHZ2/f6j8f/oSY=,tag:HHNOS2bdUoFRPNYZ0bYXwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N0kraVZ6UDVJU2RxOUdC
            YXcwRFVlcSt0MFBLMWU4Y3R6ak1DMVFSd0ZvCjhvN0RKaytCMjh2MThCUzNkTFcv
            cVJrRVZVa2hFRm9xY2dBREh6aE0rd1kKLS0tIDdubVg4OE9iM2FWbGZQMVdDb1VU
            UHVqS0NQZGhEZ251d25INXdqbUdwWkEKNZJTCNgjNktNy2FO1ANxqgM4ko2MLgv9
            Zq5c3DUBAH61x7CYuWUuX4imWtH7B0oJJan0n1KFtQlwt5Z008ZWSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:56Z"
    mac: ENC[AES256_GCM,data:+MvOodSW1wFewRuc7fHnA51cr6Yp6PR0AlEwP9Xg07FhSguOsVTksLJemwlDgKzff80OY+tU65Xg487O0Vw0Wq1eZfy/q2M/aunX2DTA0Nldb3WmoeCJTkrEOXo8KloeSvERA4eT3kwN3V+oVRRzeVKG+IU/S+/VDT0gcYKB72E=,iv:AERDoWWfbyz/YjkA0nTomReegk/EqSxrc7wFuLHjKLI=,tag:8g1QpzpQqubv31ibon9ROw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
