apiVersion: v1
kind: Secret
metadata:
    name: finnegan-a2a
    namespace: agents
type: Opaque
stringData:
    A2A_TOKEN_HALE: ENC[AES256_GCM,data:LGeLrP3GavTDqC+NxwINKnwq46yYOXCkAM8ugOWXZlzmfHficEulSw==,iv:FMnneLpDW2GhieUE/W/WW4nnbFAp8KZLu+MEIBO57oc=,tag:fzGKG/4i9LZq2vtve8HCPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOHlJQ25WcWZvZkExdnQ4
            N1Z2NzNsVmNqMnZlWUt6SUVHcEdVdlUxK1RZCjdJMUx3ZWR5anNUMlZNNFBqdGFN
            OEFEa0kybzA3MjNYbUxZMHk2Qi9jUXMKLS0tIEVmNDI1US9rUUV1b1RMSEJ0eSsy
            WTBXWUtOblQ5aWF6RnBCOTJVRWhsR1UKJgfyVOopkAIuVQmBKweMxG7+/VA6g20R
            XcK0xzF+pv9FSvhYNIicBfdXNgLMig2FKNx9lTqnIF/qnCpSoldTTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T19:34:59Z"
    mac: ENC[AES256_GCM,data:4STBpmG5KETT1U/wzcS4g2u/jCWes1OR4jW6OFGMjwzmPqkUEN2EzPK+//xxDTgCSthD0gt0/jBgQTQTYO5C8XqkT21n7CuLb7l2RkfFeo4X44Iu16CZ3ypE0W+uznUCfYu5UIZiB80DN/WVto35Ock0e87X8IBhPQzYK0tq+2U=,iv:aV2YMqDYqZ5iTKs6exXwg3/zNkCC32Y5FeajSDDI9tg=,tag:1mSwXZVA8eKR3JySAfzkTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
