apiVersion: ENC[AES256_GCM,data:6GA=,iv:R+7esgbE1QJhVWU8BY/BZBvseidnqltjMOGEJyAYAxs=,tag:CHLQGKibCZiXWXMbTgJvKg==,type:str]
kind: ENC[AES256_GCM,data:k1z08DMW,iv:mfv6LjS9Z0meGkJeA+2rsAcO0G07Y7j5+UQDym1e7lk=,tag:XFkBoY1Hjgsh/0EOkNS5RA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:17IdsT/NpgFqVzwYFe/d/w==,iv:3BZPzp+ppUqciBm0gUkE+poDvOe0HVmlkuAMX5ggPA8=,tag:I6mRsM1ElY0BE1xRNf7nEQ==,type:str]
    namespace: ENC[AES256_GCM,data:NEpdarrW,iv:gn1I/LQj/QXip4C2+JMDAX/J9cwhthSyXZNgcX6S73k=,tag:puae1dyOkpqDW9E3Z6+p3g==,type:str]
stringData:
    access_token: ENC[AES256_GCM,data:VdWMQxKbzeQkI3xQ8+hHXyEEGwudb1kcNwvuPqD9aeAxS9Aa9X9dig4=,iv:PLTY7dhhUXxvFxrAmfdX11I6xs+PVbqBFFqSxYwOutw=,tag:wsECMiohnQEmwEuzXxDX3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVUJyNFM1SFpqK2oxUVdp
            VFBuZDk1N1ZFQ2VjZnJJd3RsUXZGd0l6N2lFCno5ZUsxMTZCdmZhNEFrWGdpMC9x
            ZFp3d3dxUWo2T095RDJHcGJ3OUwzLzQKLS0tIDhKUG94UXNZK1dyNWZMa0tva3l5
            S2xyYVJ3a2xDUE9KWERIVG9KbWpuSWcKx7DavWeoue5SC4PXtpxSoYXOKTQ31Vtj
            SPrKQYd6hAdPS4j9PgzafEdzlBJzm7nkPtIW4erJN4PuBmqW/qeZjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T23:21:33Z"
    mac: ENC[AES256_GCM,data:0iqs9tIbS2DxnfC2G58YNt87XbUIXpPQvNeMcrrgr87V5e/l+IL/7sBB3xF+GjSyaD6Yl827nIIGz4zMovA4iLtHySV0boQ6BBH3jngVRNmZMKhVCOSl10+oxOREu5rZg/LormHctm5EbBvdAccrdKkLkssD1ijiaataAxdx9PU=,iv:evL6LYbnEq/Urk8AuQEgM0Sv1ZDwCogvbWor8ZpBOsA=,tag:cU5xNBT0rc2jppKntJx71w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
