apiVersion: ENC[AES256_GCM,data:eKY=,iv:jXr100bypqQgKem4Wxw+yWf21OvHIvaDcQ12hBNTEGc=,tag:ceNb2pu3mMZZa7oA++d0Eg==,type:str]
kind: ENC[AES256_GCM,data:LANdmLEN,iv:9K0YHUY1YSBgiUbh8+k0icP7LsYr4Kq4w7MqsWuZfiI=,tag:T1a4cwlDoxh8ikNFy0/iTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RVx0ANN592ip/RoL1v39wg==,iv:XFFfSWpp8ZitjiI12sYpnuQUsKGJWU1ppGuc4Z8BixU=,tag:cHqYByBhepLUFoVirtOmzA==,type:str]
    namespace: ENC[AES256_GCM,data:7flWUHbg,iv:WsuOuARsOgkyTK0gJLUP5h2ES8XXI27ndmTsIsQQmHQ=,tag:483zeRJQvA46B/XFsVnpyw==,type:str]
stringData:
    production.yaml: ENC[AES256_GCM,data:1jDtsx7iLdsPoyHPu7RKh9r/axbWkIlAE97F7iA/Fa7G+pXx7lmrepSQZ0WZi56KxPS2c6TvUw==,iv:UVAPwSB5PsMPnQ2T2eLAKvVwYdOqsUr1iu0n57SG2o0=,tag:JrjYf6Q2buOFi8J6BMkY7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR1pndHVMT2o0cDU2Yllv
            Qlh1c2I1eXZoRldocWdsUkpNWldJMDdTZEdRCmtYSnVuODNXZnNhaUxBRktuekpj
            UWZ5YzFUbTF2NW1yL0d6UGtlclRVb2MKLS0tIHZwVDg1b2VpMC9TUEx5RUhocFZl
            MWJWZ2I3RzNwQW1RbHVKQ0p5b3lhYjgKmGUJmbSowfG0YykoQIrzvyg0rZycZWku
            Wc5pfZi32solJcDYKOD6sfHPrqqD6LA6hMLWLRaomiDBpqSS+mW3Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T23:17:43Z"
    mac: ENC[AES256_GCM,data:gqtM/C4AHtfHb2KEmMTJQdpQ7qHcYhJ6i805pfWUb+TTb/078Y47iFx1/Cm1raaY0KkjizULXAPGwJNPVEE7c7Xm8SOdwtv9Zrc0fJWAw62j6ieY4MnCmX3Fic0/3pPmE1ZtvLPbc7F54GM6btRunoUouK044y7UcBZqHP+jACc=,iv:UaT4tJeYufnOnteRBks/04IkbE+wALrOlYqk3gaDfNI=,tag:8Ix4NT/zsRgXmGFqfnlC/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
