apiVersion: v1
kind: Secret
metadata:
    name: draupnir-secrets
    namespace: matrix
type: Opaque
stringData:
    access_token: ENC[AES256_GCM,data:EUJrL4PfGqY0YN5ys0Fkd6LWE5eI8mQZ,iv:Yh4eHo2mOeoWlaiHNZ2RMkW0vqEu8P2raaVhmfCkYDc=,tag:MX1aN8lQM7CIOob+p+vzsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2lsanFkdm8rTnBLUCsv
            UUdMS3hMcmhncDJpS0pSNTRNMEp1aXNwY1ZVCkIwTGVHcFF5VW1EcDROcHBtQ1JJ
            NVR2RGhMS3VRYlBoUEtsZWcrbnN1WDAKLS0tIFJTZUtNY25nK2NlNWhyejFUWEI3
            ZXhaUjVnTkFjNy9aWEZYNVR3WUIwM2cKM5vB3ZGBXy3M9XCn35padJcdaE9LPJR7
            9jU0WXZ0FOkD018w9CBcshJYjaGdV+62yRmKozQlTxMqt/SZFAzpag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T12:51:45Z"
    mac: ENC[AES256_GCM,data:dWkPDPxTbmhFmPpD+c5u2SE9S6CDk6L2rjerCQEJqVF5Y7vB8B04QfDTdZXT8WR2hc5gMpFPF+9Dj908FZo2QEyTgkyXXoG5Abi3CSNNqNvLmgfP1+ANHCvdKPonKMcXxa5HTFWYD/ALopBsYZyNaBodyiGBZ3mxa+LTps9MCPM=,iv:3DGmJMB66hwx0LoUMCbfdkdQuJ7W7yIHGPOtrP0CliU=,tag:rGQOPbHrdTtbL6UqYinNUA==,type:str]
    version: 3.13.1
