apiVersion: ENC[AES256_GCM,data:29I=,iv:JIkt2yLR5J+zUjBKluycr9Zsqzcs37L9hdYMLsVN0B4=,tag:BKsU9QIMJIUmIwqwMD/gSw==,type:str]
kind: ENC[AES256_GCM,data:7F4BHGXG,iv:kYXLwNEXp4XRVbZXubTiaoMuGweqDjYGyQyBkEJLOc4=,tag:b7joM1DUv87GinM/XgnGSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z3YKla8dm90+d0QMrTUg0alK/Q==,iv:yJVc2WOotlWUbFqISceSVij6WQATLXQsn7Rvwd6ul+w=,tag:SJG0KTIjecFmTVNXi/Niyw==,type:str]
    namespace: ENC[AES256_GCM,data:+52HuW4=,iv:galN1cbncEczX1nvh/pfYsy/SA4PUaUW8MwmwpTVzyM=,tag:LBn1TcZBLJju626FvZXGuA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:IxGz+n/t979ySwCqo2KxkI4ppWsZMbzQBo1FpLIpMs7qUtTB,iv:/x8B+70iJ/bPKhYJzcEkD5DYZHbE/N59X5ZuQ4kK2+Y=,tag:GjRL3OmR1tPWyuiw5A6ofg==,type:str]
    clientSecret: ENC[AES256_GCM,data:GDTZGwKFJ07WVJ/yXnIdn7DMj0VQAkaEV7MNBABtvZU=,iv:RuVpFcUA2qvtzI1JF1Fnz0xkqxYfC1vokGbfYedE5f8=,tag:JZs2xm6qsS2udDYmvWLGyQ==,type:str]
    cookieSecret: ENC[AES256_GCM,data:BQuLls1xpUT0C5huOoRo5mBkQf0OB+/WuDvResDE7OsvyJHKfJ0sZwnsc4I=,iv:G9/Y37I5wdk2fB5xQAt27zBCLL6HRjkPnEVBbV9M+9s=,tag:HaEuVamwuPjGSYwxkcf46Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQLzdrc01tKzluQnlkZjB1
            aEQ1RWg2b21aaHJKamE1d054MXJURHhIZG00Clp5MXJSd0FxWm9hQzFuL0czcnFu
            ai9CYWg2eFBpclNYVTNDRXdScWdUZHMKLS0tIEVURnNjRTRFR1VnRzF6NFhpR25w
            NWFkS0UyU0xNa2l1RVA5T3E4SlhGNGsK6MZvX1CoehUa+fimXUp2345ZcZScrt5R
            7OitwNXvZbWCLofhZiY1pSKAqJsktrneTxF8HR71ORV3EFnEDUuhGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-30T10:16:39Z"
    mac: ENC[AES256_GCM,data:vQE6V9M7XXPqJiM3v0E/mwn14k8W449h4ZIGoyOnbA2SExPspdObgJ4tHL+eNucS/980PZPaDKPbdYqEsoVz1x3Y7nIiyd2vySfHnFWE01lt7eIVdKKtWUgOSisx4BTb8lk/WbNfqz0hHtNd9sMauvruPhrjyBm6Ov+wnIWHpmw=,iv:w/0fKHQxiQpuHRoQtHWSrDoZT6znFBSScRFTX4hir2c=,tag:mdSBXQfFf1Ot462yetKrpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
