apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret-download
    namespace: media
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:YSf9KgziBfKn7FAlCsys3Mb4or0eEFpLOT3h0bY1pOGBu5el,iv:lyusUVBgnxKkRNx2pb04TG29Nc/H2ZHXt02k5KCDpVw=,tag:A/djHcZydN5VcA8/NtlXXg==,type:str]
    clientSecret: ENC[AES256_GCM,data:idDcm8b5/PvYTdLMxz9f58OZHKRgg5Wgbufui0aJPh8=,iv:AZqj/bBDRknycyO+37LZ1GNGRprppTis9DvOaUyIYro=,tag:z7W9DSx2zOzyQBSIfTScyw==,type:str]
    cookieSecret: ENC[AES256_GCM,data:T5ePRAdtN5Tfw0PuZblHTMby3imSqwCCua6cqrEWcXI=,iv:rjc1qFxKrZB+U1yWuTxMtdtncJ0wzg451QKVjyPS2QY=,tag:5Dc11nGfoPab9dmkr/ph/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVDWWVLK2xycHhCQ3gx
            V0ZhcE95bkl2VERNZXNtSFlSUXdhNnpQQkQ4CnRmbkprcGRaOXFNeDBDTE1vTkRa
            ME5QZXcwRUVidjF2SFRuOE5pUEtjWmMKLS0tIHRCdGJRdHRYR0lMWWg3SHJWeUkv
            L25CQzhPOUZuRFNXakw4eHJJWFJtY0UK77meprE3xIVE6Qn22uEmylATgXvEEVwo
            vPDKF4vkNyJ1UOkagOutq4IQcAOGbHswv19LQUMek45iUzz/PTL1Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:32:58Z"
    mac: ENC[AES256_GCM,data:VW+xv8um58DCln4MMM0qrPtRWdpL+xNCYDDH0/UCT0EF8Whzg+A8AlWnXPk06XZfr5lznVzw506w4mzYcQskvBhz8HcZlw3oswAzr+qiNS8WXnCqp6VqQzbLZPOvyeSAka8EPbZXa20bgUE2pagauAXZsOTgaLNoF5j0/11AJrY=,iv:lW6ddfkiBSJMFFGWWdYaaG4ed6u+Cqrdm4xq2IwCk0A=,tag:tx03nW10p3ks9pldYuViMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
