apiVersion: ENC[AES256_GCM,data:Yk8=,iv:BuMnfuGT60STiPsD5EUeKmLFu+eQk/2gvbHDjuVubgU=,tag:uqgxXHQL9qvM9ubCDF2aVA==,type:str]
kind: ENC[AES256_GCM,data:RBtsNJkR,iv:b4/JzhTD+a/x3T3mHrEVlbRGMq15BbMv/3X1wTuAltM=,tag:bLgiqirRSLMotQCM+HHmrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xnf8qKQKNC/DyZRDLmRq3kz4OA==,iv:ggP+GgATGnv3adxjIiWys8vrkolvEXEaAVukWR9hEhI=,tag:d+XyzDMTUAQqM+L8mYrNFA==,type:str]
type: ENC[AES256_GCM,data:YAXZRWNL,iv:iIzlELg/z5IUUXDWfe+r4qVt4A+vQT+1fIQ1v6Awcrk=,tag:IChsI88MbuuwIoQv5il4ow==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:xpmaLVh9BjPxHGTh9E6jH59/EKuuoOTBr89bhGF7lk6OsDoU,iv:yu8KssZUEU+Rlqq69E657CFZVbgpuTrKvx1kSyzOF6Y=,tag:003GSNM+pgZmEA6XWcUnCw==,type:str]
    clientSecret: ENC[AES256_GCM,data:SDZClTpTrHivN55pCERQbRYCOJp4waquEgxprHwrowo=,iv:M7qZVVbPpA21P91PZNCE/sOckPrmGjkW7iXv59o4iIo=,tag:8KO8Im5rKWUL54xuxyvNZg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:C9mFtlWbwaYDtNteq7s8wTVDqELSX3ACaicTTW2wA99rjfl9l2CR7p7I8SQ=,iv:Z5IG9T6U6yhuofmM5ubvw5P62ApAnIYSgSU4L+5GQT8=,tag:YkUPwUxvb3VOdb/SMg0SeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbi96V1FRQUdCckQrQk5P
            c1ZrVUxQbkk4SlZ0eUwxd0JGN2lITTE2SkdBClo2MU9mNEM3aVFzc0hLaHl4NDZ1
            NU9CMkJua0hJUkZ2Y0FEMzRLK2htTTgKLS0tIFM4NW5YQ1JYYnZVbDRlUTZ6VFgr
            VXZEcHUrU3BsYW1iWG8yaHBEM1pBRGcKWQgu5r7AG3sEDLWMQN7yttm2ZaFewQVt
            sN4rO93/Bltt4VaLNRyvsjzJavqnZxp/PA+Qmd5tK6B9YEA8F3Kn9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:14:12Z"
    mac: ENC[AES256_GCM,data:uh5pFu/grHRGHz+nBPoBLlOjUViljaN4RbL4JaV85O+E9ZDqMJtY+ETkb7XLMCvQOYl+zBSzcnM77ZspXBf6yWMuNoal4zcDyvtZFRuRwWVmwGMibvyPzZZtwuwtlW0yaYAKL9R97QW5lNRwCxJ5SI78QCoD92OpE+AUP3hxVs4=,iv:gWkRqUyqGxlwKy1QVTEuF43jdh6JvSaqsaudFxCrNVI=,tag:0W0gTtT8wqFCPQ2QEkblNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
