apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:g4e6DaX5pyQOUyTPfUh32E9wYLTaVQkx2c1BuW0Ag9DvqnZd,iv:mu/D+YJQpjDFbMsEzNlP9qWQonv560iwUrucsg09RkQ=,tag:I2H1ZJABW/NaOWgZy9I1BA==,type:str]
    clientSecret: ENC[AES256_GCM,data:q5G0cvBlcb9468majqqIMt6EcZx4Y/QkqMoeUjCQlYg=,iv:OwoF5+OXMbztE2+8xEBjfd8rzC4eVxoWmQz0lVV7QEY=,tag:ZpFIAWhqBvoDxSIPRNRR5w==,type:str]
    cookieSecret: ENC[AES256_GCM,data:eih+P/HQ/eHmorj78AA/4v5YpU2M1hJunKTwB0YmlUwQrbhRB8U5BFfO+gk=,iv:KiQWxHoF2eJ/QQl+7Q8jB5TJmBmasZl7pE0qYZyVqiU=,tag:tOfJzhtf81kqs5gokJGA0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVzF1QkhSZm5qZjFqQjF1
            NGtFL3ZHV01DRGphNlVOTkZaOUZMcVppMEIwCkdXbUJDM0EzdTJRZUE5K2pEdUVN
            WjVQWVpHenIra3JUemU5OElOTFVmb1EKLS0tIFdUYklZZFJxZXFHY0Q2Sk94REFZ
            M0FJeUFLQ3U2ZTdqd04yWUV3S3dkdW8KHs4th03+Hge1uX0jvdJNVOXHCXK5UCt/
            5ApWKJGypqzBi17OtjvdFw0MRUhc7v5+UBflCbhYAfqvE6snqEbDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:20:56Z"
    mac: ENC[AES256_GCM,data:UTwppX9erUCafCBAV2XsCgoIei94HUreTCBrow4KZ2mbhqUKsanMmmO541IBIz+7QHEXYM1W/A9P822/dYhTOm74B0TbGeMqRug2lABsoQR7PEwn55k2ZWTYKJNTWysMCso/irCTAqawcN8S+v3hddxemcc1BFuEXZ1xszR8bdA=,iv:qjYMs9cSrMm3MtiiPt/b8ci/imXOzV7ps24luXuUsbw=,tag:XLeLyZHQloeRXtW/bd33sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
