apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: media
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:X/IYiuwVPzaNLZS/TLNtvRiwQvbE82AZ7gxMVcfFlKGH7hb8vYfqI2R5zl9fRkXzQQvLXoAiMzCLLdFCRz0=,iv:Q6vm5y9y0y7vgHehhcC6f1pTlUnW95zICCAnzhUe8xU=,tag:0jIpMcT3lRmtEzfx1Aw2mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFdiUzFZMU1neC9JaUhM
            T01xVFpyMlE1eUFHSXMyUXlpMWx3N2hOSVNzCllkbGRDQzFYcGtHZWFxT1Y2ajJ1
            OFhJOXM0WnhBUXZaYmNURmg0ZmI3ZVUKLS0tIFVuZ3kzZ1R3cTZuS0FPdVRodGJ2
            SS91TDQ5dkNVSWcyZXlydERIeStDelkK0syJLi5Z58QdKap5xDKGTy5swsrndLSF
            fawkQ8BOJq600yrGxUohyZN2rVIt0LskmPhteMsYPhVepHaIWv+jRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T21:22:54Z"
    mac: ENC[AES256_GCM,data:FP2Vi/ELyx7A/zr8WijpzTeDtAeUyTeONIvDJW7y9zFdnLIKDSUMcnbbaZkEt2GQ15cFJ290a2AlpmGiR6lvH6y0CBwoItkMyKeBzOG8TI/wXzE9t0/Qpy27zHRs6v8j8kAC93xn06uO7hU+ZRIHWiK0J7dsF8KTb8qAlnusubQ=,iv:8EK3tVIiysfNCKmHEg6+LOh4woy2iqm5pSL3iLjRJb4=,tag:lZVskdEOo96rATcgA0zzCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
