apiVersion: v1
kind: Secret
metadata:
    name: wg-secret
    namespace: media
type: Opaque
stringData:
    WG_KEY: ENC[AES256_GCM,data:Mnj+sjJycDcP3uJiMtc2ARNSS/PMJPnhoEC4FW21aoUmc7wGAR71kSvBZQQ=,iv:1801/J2MeeL9qbmNlQ5tkXHI8XkpMiX/V2f9BXuuadM=,tag:jBH7yuLFnXUFRbo4+s28Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOXpjRENoK09KOFRUQ0Jx
            dW5LbFRqT2g1S3J2QXJNdGdPRm1PK2JubVVJCjBpVWdJSFYzM2hYNXJrQ3ZNMnVP
            ZmtpMW5MN2t5UXNXSCt0cFJpM0F2M1EKLS0tIHNVV3gwcmcyeGovVGZRQzE2QWRD
            R1kySkVFQnpNUzRwaC9aZU84Q09WVHcKMgQRb4cSZN9hrGgymXzxGEfliPOe1rP7
            nrYqMGO7Mk7GT8nQLlT5B7vdnzTUQGClcI/DHE4yid62gpG0JBW75g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:28:26Z"
    mac: ENC[AES256_GCM,data:XO5waSVoNh3ng8Yt1jiE0rFzOiQ4Yz3Yzwhc4nbmvEdDFMvg0CX+Cc/eJkKzNKK5wSc0w15/iotCuAdcnyixNhh8xpE5VOpueHNEkUdAO4vgBH9aTPWsT2RRxD0tlxph7oG2vXJcncNwkV/WtpHQL2YFlr4JcUFeVBFP9f+/FyE=,iv:XYm5HNElTMTWB8wgANpe/ZoOyEPmzWfCtN2qDoey4Pg=,tag:FXcXJ8ELzgdafDnN/KJ8Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
