apiVersion: ENC[AES256_GCM,data:qro=,iv:BS5dLN6Sm3bQRJyM199HZ4ICuMBuRAITfxVSZzLSAfM=,tag:3Lh1FhEsynxS90nOsPqoCw==,type:str]
kind: ENC[AES256_GCM,data:HaPvj+Mf,iv:8zxb7aayI1d/yMmWlxOxqSlUih219HjLa5k8n8/ORyU=,tag:Ec2ICi5GyAC4o7wzEGCu4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qyeJ7k7/S6s5,iv:8JVwwuTsQ0WLqiQMAgHGwPC6tIIXqEUf8K4W28Ko2wY=,tag:vnVpRvlsxzXlbNKIuLMjrQ==,type:str]
type: ENC[AES256_GCM,data:vaX5OGVK,iv:1zsW2lF7OovIU4gD/o879dlxCShPVeQMcQB+eaozoXw=,tag:UdIL9mgfKxffET9GDhAPAA==,type:str]
stringData:
    WG_KEY: ENC[AES256_GCM,data:3Tug8hx3NLVO/75A4qQqDYk2rjOia8MdK7kLYlBeTZ+4C93ctimq6FXK,iv:ETlzRwkLSekv9A7k0wu1LN73FSc8k8lSPSjVbh3Ev/c=,tag:yZC8cR7YW31Hk1HaIcuFhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcFRzNFV5dXliT1UxV2k0
            a25FQ1IxbmgwNmVzMUs1cmdmTWZXa29PZkNrCm1HUFZQa3dBOEdJWFFEM3Ivelgz
            VEtSa0sySWM3VkQ4NmVDcFAvQXhWUEEKLS0tIGdIU0dKbTZNUXVZckVBMlMwUjZv
            MnRwYktSV05KeEJmSkdJT3NmT3hBRUEKViTbJOtKL5yjMebu4lGWy8ehPLmu5/6N
            kCe7Eay8LETu0ilVfFadlbpKR9aWSZxxG63/HiZ4iAnu5x4SCZ1tWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:14:19Z"
    mac: ENC[AES256_GCM,data:k0GkqYYMVn1RwoSksb+fo2Xe2hAR9BRWPUmZXoA3vvVo8gPh9+LNm5ijbWRbeIvtPQ0W91MWAt5pt+vmxksnyVlMUtGXvjRwBOsF6Wy3d1lG7xLi3QgWobYCBGQlMLNFwYoSdNxBWNGs3uHWrn6rCxlx+8YCxu7EHG3+Bp6vtlQ=,iv:78We15BSvq2m+6OvZACFof9jqRfcRwED+zAPaPPA7E8=,tag:y+sH58Hzr3VDhZQ5IHHZiw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
