apiVersion: v1
kind: Secret
metadata:
    name: wg-secret
type: Opaque
stringData:
    WG_KEY: ENC[AES256_GCM,data:yDWDg8dGPR+zfo8N/oLV5mcjnrjeGoJnWlfA1GGyPSq3ssQiIDHWpjAO,iv:svSsUjVYYs21FxcHXLYdV91pjUKPzqRnlGlx2nSdG5M=,tag:4gJaX0otF8OwZVNUj1l0Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2ZBWHIyTDlvRWZWTEor
            VlpVM2lmM0dXRXpJNUJNbjFPcjMyMzVQREE0CkJoTEM5WElFQ2ZDUjlzS2p6RjJY
            c0krNzF0aGJCNzd5ejYvZldMV2pQL2sKLS0tIDlVOTJTQnNsQU5VNnJwU3FkWkFu
            MkYrVERZcUkyeEZWS2xsZG1VTnBmS2MKv2Liu+zer36DDip4n3jk5tiNbEZwXlMP
            XRS4TB1xYJZUvvVsyQc7mdYY1ym+j7CxCxuyC0aliO7uesoCCryvbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T20:20:56Z"
    mac: ENC[AES256_GCM,data:sangD5yh+SAb+h2xdBqx+jPjO8Tl1YYQq9feOHx97SKhXFakiPKbNpMypRcm2WqfwE3amj+QBCIlOfnBcTMF0jZ8FNCr/doaAfLJC4fES0kJqQb9gWbYZfjwgL9kCk0XdCj09pczQcFLV08lFxe/u7MyP0JLB9jUrEZWoMaxc1s=,iv:mo2V+MQzEXBh5tO5f43Ulhr+8uQG3DhVQNBlWQiy9s8=,tag:+/WhZTUTRI0GVS5PutGBxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
