apiVersion: v1
kind: Secret
metadata:
    name: router-secrets
    namespace: agents
type: Opaque
stringData:
    #ENC[AES256_GCM,data:oqgCSTyAG2rg5r2RdY+m5DTsEcpZR4bT6HpGbeVvJ5sbnxzCx/uCxO/Q3WP859HPp7NwaTeU5PVpQ6kKqcBd/xPyuA==,iv:akUbRkBMh1tRhEMV3BR777Zev88PXC6YmtIV9E/C++E=,tag:4maZ5YE99Zk7ycjtkcjL/w==,type:comment]
    #ENC[AES256_GCM,data:ESjt9Yt8BOk2sNu/sM9LFYhxyjV/H2DYD9whpzwTHhJs0oSiZ0bLrWiHixB0RJzzDG9pLiUqrs4i5X1CGgoMZEpv7LQjgw==,iv:nq5K9f8IxMxAWLLGFUOBj1JueikppWmBsQMmB79wAU4=,tag:xCc29ZfQAGFK4nr5AaRUPQ==,type:comment]
    #ENC[AES256_GCM,data:F12OsYxJEtt7F9AosApw9GUBKWKd58jCz/Rckn5adWJrQsIMuF0wHroHkRvYWqgtfqmIM6t9/4HQbJ4XjG8gJ3lf,iv:UytWxmbqjqWr338lZtMNxNcVq6tUy060oItoE1jc9XU=,tag:ghKgnAFJR73BbwtcLkirqw==,type:comment]
    #
    #ENC[AES256_GCM,data:oBDRnX3EDLeF6E1tTc2uZulQqop+p4X6InzZ5A0v6yAaKtSeozCcy1DbKKcMi760NwC1IZ9Wmdtn2Qk2VwzOgY25UAj8Hcjm,iv:TX3q7c6i1t67xbSK8Qu3FYOZE+ylFyLPeJ2d8cU3p1A=,tag:nP1e4eHsHM9U7HhI6Ko3LQ==,type:comment]
    #ENC[AES256_GCM,data:ZdiprzL7oxrvhrjRiNjVH43whrP4TLECeNa8K2n7adRhbqymoK6kew8tVzrh6VHNXSgcJvEybZF6fjDPwtgmxiHO,iv:8OsQuEXueL76tlUmosMjKQviAxhuQDol3PaklhaO3to=,tag:efvd7zrhj4NRVN8R5xfeiw==,type:comment]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:E/xyKsfK6EIyfahaYzfBTwzXGV7Hx31nF1Vr9IFI0+hOb43AxSPAqeG2Kt5zKtJu/8Sg,iv:8ohxSsOffrLe8lcRgp+9AV7dIRitzezBQkmjhO2hjbo=,tag:vCwp1WOjJJVgHZLN1nWwIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdkI5Wk5LWm4rOXpHcnhv
            eHhUOSt5Tm5kS0dEdzhZaWxBUkZIb0hNK2xVCmM1ZEM0VkdqRS9BUWlZb1o3bEZi
            RXQxWUpJR2xRUzVldTN5Q3ZUcjR6U2MKLS0tIEs3YlQvUG1qUnFkQzVXVUo4YjQ3
            ZjZqSGw3YmFab3ZCeElGR2NwVitnMjQK0fFnLlYoWXU5JmpWWdT4SHLmfb1t+AaG
            n8tQgdPLnELvYEhH8KhhiLG/GKaEc1NboqaHsc/Cj7XGbm8eqb7CJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T17:22:02Z"
    mac: ENC[AES256_GCM,data:+9qafbhxkyhzb4FuqBvH3cMcPaQV0X5c++G9wU3x0cfG3NBw/GFOvW50TnppIuhucjRTNr9xzC8BASjPYxzOVx+P/mDTioOl3ASWE6+ecMCzloYfIWY4w5WqeQNo9Vtq/iEIiG3+4SJvQctPUOlvnIKBbIKJqhS4XkHB36SPLNQ=,iv:nX9wZQWC0/lOvk+eFhAWRJ4jVPyNk0yeE4/Ek3gsuOs=,tag:uNAzYYfBFVmoa1N5oWmjfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
