apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret.yaml
  - smtp-secret.yaml
  - helmrelease.yaml
  - httproute.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: smtp-credentials
        namespace: pocket-id
    target:
      kind: Secret
      name: smtp-credentials
