apiVersion: ENC[AES256_GCM,data:Ua8=,iv:OkqxfJhZo7U4wqGRcr0qcZbulyATuk9QmD9/tZckrGE=,tag:IezDkImXT8sWOAtk4/mUig==,type:str]
kind: ENC[AES256_GCM,data:ySTQmYCs,iv:qa53SKf4OIBYyMf72AMZXeesrSjKKQkJO70LTDq2OEo=,tag:mFk1SmfwObkSl9hMiEJvlw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lHGTmrFBn8K95ArEcQe1I+M=,iv:svTwsWliFDSyD0Kst28yh74yRszG/Aqaa40a8o1s+AE=,tag:QzsDSZ+ESZFeemKd0SNx7w==,type:str]
    namespace: ENC[AES256_GCM,data:jXgK0wEKo3te,iv:uAvUE93kL1De9OLa9+hUgMloCDOEsUZNiT4C6WNQtCU=,tag:1okqWX2JAqpKE2wT9Rd26w==,type:str]
stringData:
    encryptionKey: ENC[AES256_GCM,data:U8wIFybfPnVwXLsMnU+n8kF54f9/NHh7LKu44flpl2cr9E6swxtfvkNPhUo=,iv:+rvvDzfy5lR22cojAXEcL79hXNQSurE1SKVZChICvW4=,tag:JLOmFB7mXv0JoV1NToWxIw==,type:str]
    smtpPassword: ENC[AES256_GCM,data:RdV3BL1ApEM99ZYDQkjCNdb8H8mbI/jQWc0wsvBcKyr2RtjI,iv:M0cYmB3NSzLGtvurs480VGl+vM8vNz6xMYf3wEjUCnM=,tag:NJ+CPPZ+60VnRhzMukp8Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3amg1Tmg0OFFEYlN5aUZC
            bk1zREhmaUsrQXVQUWZvam9NWitJM3U2Y0E4CmQ3RmhIZEFMenpiSjlhN3czQ3FU
            clg5ZGFzcy83RjkxaVFSM3BaN0dsUjAKLS0tIG9MZVUzYXpHVnFOMGdqYnJkbFdL
            WXVCMkRZcTR5bnF2VDlKK1EvK2VsVTAKQRBFkQlN7qiPIGlZRsZia9TSjI70gIse
            iB6CVEZeij05xzzNHIStOKCl1oqU2OloxV86v2otguZjBpSJZzRVWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-29T19:26:30Z"
    mac: ENC[AES256_GCM,data:Q8/ZwZN6kSwnseofArQCIYIQofPOe7cF8YN8UQkUMIrTyn267nQN/RbHh6j+eqhJE1ITOEMZ2faV/m2N/bFRbY0GhQt+qzTXYD5TdTKK3HN2V03WdGJfuPRWGH1Kjpwfb7tYZoGtaNjN1G+FzcO5cxVk2EMLf6L7FyOsTIfh3oc=,iv:vrc4tvCwO2AZV9/f0GAhSErBmLESD2i3HwIaPTfp99c=,tag:F8/n2Jlcphe3xbutYkU5iA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
