are_9cJLWxf3_9cNAA6XfakDPrnXZZaeUiiPBpiVersion: ENC[AES256_GCM,data:ohE=,iv:zvVKhTvZS+5iU3eRKkKRsgWeERDHslQ3SBsRCJdHC2U=,tag:IM8J3r+Pl6+nPKPQUZy8BA==,type:str]
kind: ENC[AES256_GCM,data:biA87O+B,iv:gzSOhMMmR/t3HR8PUTZ6e/dQwnnoEAFhWwWv50uRpzQ=,tag:D732wnO6qNmtnBf/eecDVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ybs/88mQ7W4RTRoz6IRtAQ==,iv:+I4exQgl5iRFeHOIyLqp6slkMNNP6r2Sqw8srJ5TPAQ=,tag:Eot947WXFH+mAdjGvA9AbA==,type:str]
stringData:
    smtpPassword: ENC[AES256_GCM,data:flx0YEYJMsigkVtvYgvkj63nWoLqX9Z5UC999W1/flS+5eBe,iv:d2MHEpFpm1pgWIs76LedHkvYghkQvL8o0rH1eqV5lWY=,tag:NLvc+07QmY5hFEVw5apSqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaGVJaTB0c1dzNWpKdWZp
            QlJtUkx5UWRUN3VBS1ppNTJ2K043ZGhXQUhvClZFdkZiOHVPWm5PWW1sakl3WEcw
            Z2tzVjRUWklaTGE0OU1NNFErOVJISk0KLS0tIGU5VzVFQ3UrbE01Mkt1SjAyN0Q4
            NnFhZjE1VFA5ZXZac2tNYk9JMmNRd0UK3qCrPRDm5sBUW/SED8X7uhiokgBcDgg0
            vNdzQQv4jcveui1AShz2Zyx3HEUkbpIELt6wfMYek9eyyo+XTUm04g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-29T17:50:59Z"
    mac: ENC[AES256_GCM,data:194hMWnzo4xQkruBHGH0R0w8I7uR+9TMyrWWtI3XLoPnt2HYmNYs8203qxocK3nR0pRsfZTLjXTVcr1PdqALqeIxhV24H20BIZ43QTfyfEfFNswcLUMeEeZFZvvai0vzqAgBOO2OmGWOmxhF0rpcXa3jej05cKAVDgeQN6rVUuY=,iv:oG39QWmjh3cvbArr8UXlJ+AN2wV4IMaP+EmxU/7nKmY=,tag:R0GC7J5SMhItOC+SxIZrcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
