apiVersion: ENC[AES256_GCM,data:t3M=,iv:PMprhCvZcovgMzybSEIsgxnIft8fwYHXoo3oVO4Q82E=,tag:iH1l4fyi/Qe0eBi++SApfQ==,type:str]
kind: ENC[AES256_GCM,data:a81aqlGv,iv:XdpAe+57ciahKPCqb+7NhYgxzm5Rvz4hXUuA5OQISXA=,tag:0rW2ZM0UXQwEUfIi5Zl0Gw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wiz1llhwaAwSkZDUp7yJKVSYw972PNd+,iv:Q10TZPlsAihYBBhxL0GV1+6lr0NL7UQD460diIrGuc0=,tag:aAdZ6IaTUv7iRegD9tKGlw==,type:str]
    namespace: ENC[AES256_GCM,data:pC5kJyaygQ==,iv:Er99Qcws6FIPWaTpHKWRmNRu24mYdHb4kHGwqDvJxlQ=,tag:9strkucx7WXIWKnobvFd2A==,type:str]
type: ENC[AES256_GCM,data:+2wZ8TrK,iv:qhfKQDnQxl9zw/fP6L2VpLcuAw15REJq6xFl4NOBdgo=,tag:uZOmJPNbpMh/v7JpgGytRw==,type:str]
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:HcGIzLvw++GVMvxyhrt9N42n8fTsgPJ4p+3PEG8W53mkKEQkOK1PmBVTQOniUNbv103C3hA=,iv:W3o429OD52nyEhVZJpIelufsX8uW6ta7pROm+vfBuKY=,tag:V+DWPmM5B//L6H6Cbay9xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdWdqMjNFTGExU0FCTmpM
            eXdXOXFlSytJTXJHMHd0ZC9qbDRHZGVsOG44Ck41bzgyTWdiVUtjN3AvRTZzSGkv
            RU1hUUlYOEl0cUNlTDd2U1IxUDV1SVkKLS0tIEI0NElLcUl2bTNtM1dLZzNVNDlj
            cXlMSUFwNU1GT3JqK3NjdGNHa0hDTlUKFh4/2s/x1C1/5456BstoS09gsBDK4GMo
            91FX9U7HtXkP0/Bg0iwUa8j4Utbnj9Q2LGPZgrBBm7yhnhQ8nO/VRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T21:39:38Z"
    mac: ENC[AES256_GCM,data:p76+GCPpnBHR3hRnZbtR0EKe/uihm+VMc3AXWbCM4n8mpzIprUSMeNxa6lPobvaqkckgE3rrJ8pfDmRu+3o4aOmmXA9FRMb6ZgAGbvXwYF85p2J3d57kQRITHJssnB51EMPxn7/ooXQKfGiHgzJy8jltv6yLS/dssdDk/4+DGnc=,iv:gi7Tub9jVlMKmKtoLpnjrr4mHAS6p5VSZi1T3JjEhM8=,tag:hj7rdDXKvx7i9e93CdL/JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
