apiVersion: v1
kind: Secret
metadata:
    name: hermes-a2a
    namespace: agents
type: Opaque
stringData:
    A2A_TOKEN_HOMELAB_EXPERT: ENC[AES256_GCM,data:mv33ICjxZSyTXXjfRHJNm7HrDeVtyBJZt01YvJ+fxyMK953YiafYfX8JVw==,iv:5UWEfDbSwjLh54uL4H4yg4waZhR45/E5uAAjB+VTK1A=,tag:jV2YjRNqLooOlDNNSy1H6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UC9UWlhpR1R5Tm52d3hT
            V1p5VW9OKzVyN0dubGwyTUlNdzR1YkZrZjFBCldwUFJnSDZZWXBGb3Rtd0FDN3NE
            YVl0WGhKTExHK3RjeEg0NGUvand4TFkKLS0tIEFDazlhZmlRU2pnY1MvdXdsMi9m
            eXErbm9JSkYvRUgwVmJncGE1cnNydlUKwiIjSUgPhHK1UGXKbVXW3XQ1GOhM4f4C
            Yt4lbj/cLUyQMuCaK60t0zzx2xJtPJKx56HoX9uYaRA3HyYeYGY+sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:58Z"
    mac: ENC[AES256_GCM,data:VFZxfWm8a7q4GXHeM3zYNhXPGRfh65adPDFMymw+LEipZg94u92J50V2ZoMpqBM+uFI2wU9iGzS55z3Is516Fj5B7sWKgC2m4iqbci12Rw/1IvR4m41xLTSDJv3LwkGYU3G8BlWZjysxBIoE/mq9E3iFmy6zlWOpPpW3F7QkQ80=,iv:HwP3uklgAexsdfQ57kzz6B+/AvdjwB8fz5ja80980J4=,tag:WdflM+B2MhwLSCj2jzAvIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
