apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets-default
    namespace: agents
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:8lIg2nJciTW/3xfPE1oLlpVx51teEzEu,iv:jCN2NL1qvebCPyEZqaeGH03kMmN/MIum3gWrqfyek3U=,tag:bLbk/WF94YYbyJ0E953ZRQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:mXDCyXPRcNIpbxnkXSaXAtDyCN8=,iv:USKO5Gx7Zng9C1q6T6n8yOvUNYOfiXfsMoMw1FTJnfw=,tag:O9MMW7uB+6yjsis0stIM6g==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:58MGO1Jox4l51w==,iv:7MA6YiFh8In4d3Cjt1atoWyrX44T9nz9gMCqJWiRWcg=,tag:TqAq1oGjb4df+cSUCW/Q0A==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:9p6UISmsTYQ=,iv:AH7yTuQYequ1/SgtdxQNXb9h+I3rE6lxe69JdIvi/Rw=,tag:hSmGKANULcsKt3diJLudUw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:owpD4hUoyUh5U0keDBkCDCWDJ+33sFgLcHF4YA==,iv:g8WD+8wJHmIGphsw030RudFA70W9hSLWTeru+NpyHmg=,tag:Z0qwgpUSWQpwyS0KDqq8Mw==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:5fR8mq3EppW0+Ek8KC8dPyzKgDD2cnqGuMfnpKLtiFpvXyhs1lUG,iv:xi5X4BpKiIEQSGTEVdiOifvX1e0a4IOhT+Ai2fc00M8=,tag:3nrMVqqbv3CaCXNcNf6DpQ==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:abgByZ1+oy+LFlywAkuOO/V8MwEQrdf0P9S+bzA1F7v71OrlsnBHCQog0DO+taCCdHHr5bozWdp1S5U=,iv:eAGsCR7DuPWEuA1DQttRnv/6bYwupjWTgMRSNdGuyzQ=,tag:FQvKEsKm7pzqhMyNFF0Exw==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:K5fB4Q==,iv:dqFm6GzS0S1WNDFK85vughlrcrTTsxDgv98HGFIx6cg=,tag:3asszXdOPJQxvLYoQCGfjg==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:aMZpLgi1EWVRABdtbEfXI+gXNQiW,iv:V/C+PhD4edi8alRbp8GQKAoTTS/RwIWZx1sIljFrJzU=,tag:gg7CN4W2UeRMIQ2/Z1B0tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Y0psMXMzM3JhSk5sRHR6
            TWJkZjhhOXFRYVE2QWZheTVFVVU0L1lVWUFJCmtWM2dEb3N6aC94SHNvcmhLYis0
            OC8zOTdCekxFZ0NoTWNTY0VFbHkraXcKLS0tIE5MT29GbGYxNVdFL0x6WEF4d2dp
            N3gvdHpjZmhKS0Nyc0hGeFlxZE54UlUK+WFUjziefsEEWV0aBN+EcWFQ6MIB4ksU
            VN6mFt9m1yohZAHWvalwm6msAMlQjrq8jS3MEICl32uuuYku54PyHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T19:34:59Z"
    mac: ENC[AES256_GCM,data:THLhR5ZE6VZ687vlVHfZJqU1MkCqkHY0g/OkGxiKVXD5lqISMiLIn7TPUlo1UZOireFtMf1O8Xpy1yc9KAG9LdUWFdQJlSPdbtAgrFpyH6z7yqcJq/Eo/+lsLbAJnqH6HG2MY++2YcC4VOGcyCyt7RfwhpiwhJylFdBE63lmbn4=,iv:OKwnad5/bPhh/aIiRxvuLBd/uf49iAnJULY/xdIt2Vg=,tag:omgFn0racVoZp30xjxTMnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
