apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets-default
    namespace: agents
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:NuD/gexsxa/PMmrC7e4zIhPAjKFqTFoa,iv:YkS01QxSMuqwKGrGjaBVaM74WHQp/fDrMo/a+s3tYlY=,tag:K43cruHHkcCXKjJrsqm4xg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:vqg1bxDTJWcMOregvTPERiPsZYw=,iv:qL2a1P9jQOUIo2+WwDK9Z7ps7/xb9oj3dp/vkkZHm0M=,tag:PgsPGM16H2EeRxvFMHeaPQ==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:eKzXmuaoO2AS4A==,iv:kCqMwQGBXD3k1CAKWaAyexDvuv/ai4jtX+YW4VpiCl8=,tag:ik2PAXqToa5pU3d1yUuNWQ==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:rRldk0qvvsA=,iv:qiHbDoQdsuHYCwwLzygj7No1KPQG3RiYEyIV6E9rfBo=,tag:qCpt8YqKqWhJxUvfrCvT/g==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:dRto6yVspUy0PVIQt3aPPhLQlpEoXZl5PiTnNg==,iv:q503+xy7i2qy8rtU9dFf0tDSazIJ7gXu8EaPClSJznc=,tag:G0TRLTp3/WRioUio7JyGDw==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:4Vydyn8+GZ32XTZ73YtIgXJN+bAkGMQmFCO+Sag5UFuKqL/ccor8,iv:basnLOGEZCXc1KP+YgNGPUn40DoBIdhuONmYiPXnGl4=,tag:xuku31sFW5eRZGP1Scah9w==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:RQ39rPUdJ2EbVv07LBmOE6tetYPEprnZmpN+uasYzF0bVCh4AwD3AemZlLdgUHXuhuAVz++xMl/j5qY=,iv:s8Cf1Ja4gvZkoxvpah+oxXgMlwN478WxdxUtSwnvd14=,tag:d0WadZvhl5sum+KWETJosg==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:MSSI7Q==,iv:NBH7PegGkFhM0l4h4TYGTljTDDB7h8cEnONVXpqo/1g=,tag:+dMCQeyKys4CfaP3szCniQ==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:9m8+6DB3UA15YpJNCoAWZ3Ik8Kx6,iv:g93HbvB0TcISC5lqhlPRWHDflzNEc0Y7H0tQ8p8lKfs=,tag:dBWRiY/SKC5QnKBujFw21Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcFI3djdvdDg2aFZWUVBO
            OXBvNXpwcXlkWGQ2WnNNS0RpY0tZNm1oa1RrCmFHN2hDYVVjT2cva3E5TU5NVDhT
            VmZ6K0R2K2JDazJGM0sraHZSa01KR0kKLS0tIEg4Rjk2bEhYQVl4Ykd6eDNPMHda
            bHIxZU1yTFRDMG1UOXpVd0hmVXU1L0EKTiC7FiS2Z0oKcrgz/YuvKECyJS5SOPUB
            +lZnU7NeDBSXLdOOGn+/qZOYCHJ5ZgsK3GdxZAE8XOqWiOc0Zciahg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:56Z"
    mac: ENC[AES256_GCM,data:E2cHB4Ob6BGNyyshE6nOPdH+IEUBgIq4pYuWNP2xTHOLIidIGu/r4x7DY6JNvaSOUh1S8CgvFZZ6VE43dW7yFBrlcx3HZZ3EcZJGUPCJC8i1PUIo1t/ywG7s9vgWda4koc8+3tpZdbgm8LEdjJmmkQSTPqYsM865EUrMWVNI4PU=,iv:lg2nnwjePGGCevLErq1rF9kz45EtxjjC5bcXN6/QKZs=,tag:s3Yxgmym3Kg7BIwODhR1MA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
