apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: agents
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:zaDiWIeniM0oI44y355b9GFU7JDLjaDHAUU85KwQ+L9VAovr,iv:z+G+CK0LW2aYwfLd1jZXcr//7Cf/SgXgzPHgEH9UF9g=,tag:6qDo7b5YJA1oHSw6fy72RA==,type:str]
    clientSecret: ENC[AES256_GCM,data:SaMCLR+zCB/7tplIhbB0GsilFyATxY3Ok3fIuMDT50k=,iv:II8BCvj/jS+dttHkrEKWoCh+yduuBfDpo0QDYODlHsE=,tag:0x6qAUbTallhUxFB5ZmCbg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:LiNF8xqMMAFqepgZdWeL67PMSmVO2JclWwsGXZcFn9PT0+xhsS3r/gA+qgI=,iv:t4zfRGN2c2VgdNh3cNz3q6mDuFAxm4EuR05UYV0RQn8=,tag:3GKxu3V4EXR8ZAE727OHeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYandmQys3bmh3TndGU28r
            cWl6aE1xWWN5SlNpMUJnbTVCYU5oYVM3L3pNClhkWjFLRHM5ajJnL2U3MURxeWVq
            R1JlUXc0Q3VGSlkvcXEzS1F4MlZpajgKLS0tIElWcisyQXd3aXRTUGdCSDhmSWkz
            QnlQcXdERkt0eTI1TUtHN2FqUE1zOHMKEvbfNAho+P7MlhMoU+io7KT8ukojDzQ3
            r65DGQsjuPMfR2Tu0xD1R7Qck7KMmpKHYbGI6NfC9jZl4iEkel5+/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:58Z"
    mac: ENC[AES256_GCM,data:/F8SLTHARH8UY2PKEB8Rk6G6SydZn3uC1EYzGPDEjou4fVida40qjVNbCfICGiPCr+w479gnyN4ysBE4UaRV+PApyzNyEVjp2vf/8zNb1lBE7OyhMj5kbLBl3UloMvthu7/PxmLIx3mt2tR+19fVxT8C0VPy7P0jIYzoBWmI0fY=,iv:rtUMM3IylOW01yr7+n18MRvK+7droTJTBLyhsoXZGg8=,tag:1BjTx92m/ufQpDGZDYqjrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
