apiVersion: ENC[AES256_GCM,data:Nd8=,iv:TsLHLGt/hSBuQZahHVfhtz98a1EcvJ0WmMtl2Pxajuc=,tag:SQLX7Z1/sD1tvC5Ok7KVYg==,type:str]
kind: ENC[AES256_GCM,data:HPs+Nrk6,iv:yEk4LKqW+aT5BFg/bnGml95o8Xt6eoHxP4G9/jO5aDg=,tag:BdKmSEkB5bE04t2nHENo+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1w2AWwkbOaaJfhKIyQ==,iv:Q3QVE9Jt6huZNBit91DSudv4M8RWO6dqGWGFOD0pRMA=,tag:RHMntBf58YGl+kzqsVXHNw==,type:str]
    namespace: ENC[AES256_GCM,data:+LOQaUuD,iv:1KTjjcsfwh26fX2dSSkyhnzVpQzMrZ60MsWywLTYa+k=,tag:NbT+lAbB+SIWKE+fK//Vsw==,type:str]
stringData:
    EXAMPLE_VALUE: ENC[AES256_GCM,data:Fg8=,iv:3kNicTurcU0Awln4C65dTrljpmcZIgBrpQXWfCjwBFU=,tag:JA2VZvcotddYUlj+h0ritw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVG1nYjR3aUkwRHNVcHZn
            NWtWQUhtd1ZSeVo4UHhtT1ZSdTFscmorZlNFCndJV3Q5UXV0ekFRQ01VM2FOR1k2
            c0puRG1wbS9ic3VtSFRBV3Q5bDl4KzQKLS0tIDl2VWRZRUZUVms2NTJUZWp0dmlP
            RFdIL1BqOVAyRmtJdVRyZnZPY01zWG8KImlRWrsSEaUq3PSbVdc9WyGwjEzoC5u9
            zQ7vnYkfIGg4l0qBz1RnZS6hIHIHVg4nLHkTjnxjMREYKn/FZRfMHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-09-12T21:16:31Z"
    mac: ENC[AES256_GCM,data:0WzTZ3jWimImHPVJnyv8055LnRCO7ERKjLO5AZx92uKVSqABIfZVIysOFAa4pKNkf6f574qkkMO7IKEHno0vZeaQEIQHgCoBSnhr5ocNbrEm4urM55v4y4vnbpY2cuIkYqIVEB2o3Od8xW1erlJtST/rbK7dANW6SZKftZgm3a4=,iv:xN8O2VZmeezIieBtpI/6/Jr+r15Twc19tRCuTxQQe6w=,tag:vgsxerIWCr44vwBscRNmDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
