apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: agents
type: Opaque
stringData:
    EXAMPLE_VALUE: ENC[AES256_GCM,data:7CM=,iv:sFwP1hxN+dWZjb7HR6O4LpTBDZ1lE29upG4VDaJhN/0=,tag:jtXPQIh6euCpPuRFdp9dYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTjZGdkY2RnlITE1mQ0Uy
            NDcxb3FYcmo4SmE4cW9JUjJNTC92L1ZIM0F3CnRVS3gzak5Ra3JmbUorYmcyVG91
            ZEd0NWVBV3c1cXlFR0hnVDE3WGJHV00KLS0tIFlDaVFWRUZRT0k2NCtCcy9pQzd5
            NkdJMEwxc1VzYjZvZkN4YXlvdDRlWm8KHGCIhAcbg5yeml1HJcTBUOUXYV7yOggR
            4jQ6upwbwdj+UfylEyHnQibBgSE9BPqXUbuQ7hiQ/X6iMTdrrWX0+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:58Z"
    mac: ENC[AES256_GCM,data:vfbWihD9JiRUMUydA8sGFSiEXpJLnCr1C0G07ZTEWBYnlMLqTU01+NCkP8RDRG4QHbgwqhHEYZLNf6aUDh7I+h1QrVfRyCFxe1s1i+IXu0/j6980Yajjuxcsa6qgQbC/5FpjO31Ua/QvDbSDAohBY+gQDlf9NdnkFNObhz+lg08=,iv:oZel9LTbI0KtIuvjcrVogVSuoien0f7uBxpNwVijoTA=,tag:fzDi3XQqPRyXcEElmeYxIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
