apiVersion: ENC[AES256_GCM,data:JOU=,iv:BFl+3AFi7Jl4gBr4CK/Qey264EzgW1bwkWPFViR5YLM=,tag:7eG0rAYLYJSUvbLxD6uihQ==,type:str]
kind: ENC[AES256_GCM,data:xI8vhZPp,iv:KvFShBdWSBzVrohVU+vcT/ArM4WzeuCSiTeEnUu2U3A=,tag:nbKKygWG22rP19Kmn/e/LQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KFuJY42OoOU5fkX+QTuPj63C,iv:V+6yfBjSEwoDdz6PGOHk9BRIRph/5wWGv8hSWDscnuc=,tag:CTMbP/f+48CEQboCKYKLhA==,type:str]
    namespace: ENC[AES256_GCM,data:PyFvR3c0,iv:gbfyOrabhNY2w8bMTG4IEzFMNFHLRC7ypPAWV+cfeNw=,tag:NPx8kG39htLx3g4EUVrqrA==,type:str]
stringData:
    FINNEGAN_9ROUTER_KEY: ENC[AES256_GCM,data:8RvJR+54qygVIzQhrNvSiNNFCxTiK1uLcRJXQnhXI9LEMh7mMe/Y60AW7X76wd7XN04qBM586ulDPDaCYs7rgA==,iv:N8e7FfyM/SuyxrJZ3ynoHeaZYZpLH9ONKl+z2psPC74=,tag:LcLAomVH3ox0dx3HSdN7eA==,type:str]
    HERMES_9ROUTER_KEY: ENC[AES256_GCM,data:+28P5v2IA2k+LHDj2k2QnL2DKkxp32qUbWEeRile7O0rX2vdZrYqk1Za/yETqk4oMv9LgUjFehKqfsHdDjmpMA==,iv:0PXOv5/mCTSIJ0yUi1PXGDZm7nLUpQiHYYB7J5YR22g=,tag:tH5gENxYm89ZiEBOr6BvYQ==,type:str]
    HOMELAB_EXPERT_9ROUTER_KEY: ENC[AES256_GCM,data:C0gtJB+6Qm8c9gEDXJruz9l6IqNyl3162u4DIQIHZGZeyv7E8HyOd9BPnmfTe/isCHfbOMIX+161ZzsEOwEDpg==,iv:80QjTGhVjRZJ+I0OMvR+0E/OjH7lEqUywXuaH6iX4DA=,tag:e5c7BKpo3wqgJ3WpNQF0iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bzNlNjFiVFczMURjWHBG
            dVZkMGs2dVMyUkNPZ1NRYjlodDNqMVkxQ1NZCnN2RWZLTG5yZnIrL0RnTTgvbDV3
            eTVPNmdvRjVDdFVEUVdaVGpTYmpKTVUKLS0tIHkxNU5EUmw1d3oyT25iankzWXhj
            ZiszZGJGdWVQQTNGR2ZMR0EzcVA4dk0K5zTlofDhVOuIZ1FtqD0A7Lx8SCXL82As
            +cooIN440BZCc9Qffwb+SvCq/sDplDBZdY+ksohbLGdo9eiEMFh5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T12:27:20Z"
    mac: ENC[AES256_GCM,data:qpDXMEGXnZo3sCnWS50wf9CvSmii8abIGNv8gvsR2XnTZBPtMVezcmaHe/o+ckqpIWKkE4pLc+im8m122pAvEFXKcJjyr6e1RifJTEffpF82LapVmkzBdTBvgxDfDsWqRLPp/FvppC0w+6L34fBMcfWWh5kb70J5qMaoKVapJ+I=,iv:DraYVatr3yZSsR4uYA9A12VS9mbPFAOtmgJ/FpvSgtY=,tag:EuJj9URAzhaqnZhK1go8PQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
