apiVersion: ENC[AES256_GCM,data:0O8=,iv:rRBHj5SrWV3Pr0ogweeW3PbJ8uDdyi0wZXyTMT2l1GE=,tag:nmHigYGNjQccWF4mXHLj4A==,type:str]
kind: ENC[AES256_GCM,data:55xW5F3d,iv:0z/uod/kofGQcPpYrh2qgx6GAG5c3Dhuh5esK306q/c=,tag:YngFuKnt3QPr7nQk+wTGRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zIeeHEOy2/wYo+nKoUM=,iv:JSCraOW97ASeHOWLh2T9xfXxK1rGJpP7+6rPpOB1VJI=,tag:HtCnK3hF4K3jOHnADwjm6w==,type:str]
    namespace: ENC[AES256_GCM,data:BpwLp0q7,iv:boPy7Qbuw2nTfl5+Zlsj5Y4n6tYKR+9EJZwHAOlrrSs=,tag:1zy/+32GI4uq1P/SvQJxwg==,type:str]
type: ENC[AES256_GCM,data:04pPIguZ,iv:CX/WqLLo3Y+phFjhsntX0Mtxii7sjzc/5gxlsVHsl4g=,tag:ckaUaV13bmjAnFNxaqJwkA==,type:str]
stringData:
    #ENC[AES256_GCM,data:B0EJgnwF,iv:bQ1mwLlkhU9DV/+SAvYWXLIjS9ka5EzRPHoYKwMhvAM=,tag:Te/qaZywQLDqyiQR3e38Ow==,type:comment]
    HASS_TOKEN: ENC[AES256_GCM,data:RlFo7nGeV0mYS3WrnMVrIDK5hvWSCuOOnmOEtJhq7QiX72V1gqAAB1iafYRE2ohPwjXv96eAKkRjdRsPdC7eGWoglu2nGv0vpwHozPLdvhVydzos9lX57S/eVPy7wbE1E+fPtp5ILWZoInAV/16jjgEbyufBmewwMw9KoGf2J3jMGgjD5SGMRGJjiHub8CLmmFnfF0Sl3DmsfGu4xO4rGBo0l4BxxLrNLXr5ZKLx4A6Z01aLxh3Z,iv:f0eXeYQCjiSTLh/+MAbJ/vXZquAKaY6NPYiTvzKWbhA=,tag:ALfM0bNOWTfzNVS6lALa5g==,type:str]
    #ENC[AES256_GCM,data:F6+SyqakpYNT,iv:JffDLia30azClhFDu3rma2MBCpQaw16HAYg9Zlw4zmk=,tag:BJ1MLH7EfMuyAoKOtCvEfQ==,type:comment]
    HONCHO_API_KEY: ENC[AES256_GCM,data:/BzRAyuVvn70IlDCSkkWJRPJRZ/bcHo/ZsWJwqaTqvjRa0SDH0VcsUEJjFpX0XtFWqPUeB5wfwPx54hXFTVer8HeVnwnBUsge7+axW+0xlOjKRrKWZ9nrG0czbZwQFyu0Nad9PB9bzGn,iv:9jKiXk3eDkZK/EIz5lELJY+hdbayF9b/TLOlNOh0pm0=,tag:RBIbLA6eeOXD2ki8PURCEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZzdsOVEwOExIWlEvbmJv
            STZONGZhVEdRYXVKZGZSMDJiMVZzZFMyVlRZCnlweTkrNUZCQ0hiZFNaeml4NGxG
            Z2tBZDdPazBIYTNJZUlkNHRTVWZsTUUKLS0tIDFBT3p5TlRJSDlKcUNlQ2FGd3dy
            dlRXU1FoRG1xWUZNRitPcG1Pc0xsSUEKxfgmbnFb+WLNpY3Cv4W48efsR9QW555J
            KPR4QArZVlQoBgrU0Fz4jhaq6Z+vUkDt0+1VHcRzTb2Vf+LkqpCEeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-09-12T21:17:02Z"
    mac: ENC[AES256_GCM,data:U2YuvD9Zs7EarqXkYgJM3obGsemQZ8WlYFGs0tW6XZMDoiFM1CWCP9fP6KaAccU5+3McbvMJ/z8kbxrUdp88N3Az98clU1wU+iznGpwFSIddTvlrgLu3EJ5utOPJlQnMymBOmNgNu3bUmGOUO2MWfW9oO6AdyC50DleDeyAD/QM=,iv:NDOvkUStgw8hbteyXLMTx4ld27UMO4qwJrJRYndpk+M=,tag:6Sq8TTuL+DFnpYwVVXCCsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
