apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: agents
type: Opaque
stringData:
    HASS_TOKEN: ENC[AES256_GCM,data:/m+HBHu88B6pPZ2ZPKtU5fkJoAAVGJyzMr/vxu4f+aPrelAo9tU1tjqUu+i8+2bqUwNEy9a1YmTIUR2dPoR7I1fAUOrCnJEIXgVsnYGkSSoGjNmYtpMDkoBOG96bIMlf8DBwGqaHcM9E88cnDAFnbwTyEj4bVl/wi2N7x7nCBSli2BxTg5ltYtQZuFJGyj/9Nbd2fdcfYU3c1/oWXdONeRqTmOrRZtio1Tw7S2/LaqyeiGE3FGqh,iv:TRMfOXrDbIrlPN+PpcWmA+BcZOkQeG8wH/heFpNR4Ws=,tag:lgRZKjli0ueR+NrfWqF0XA==,type:str]
    HONCHO_API_KEY: ENC[AES256_GCM,data:VdYh0vAX67rsK4NPCh/6xJB8svZHIJFQ1zwKQtn2YIPLhE73WoHeYIRbnT6bs+UoTDexRgUWxkl9sOGHT6XVrS2IQB4rmf/X44tH5vZJXy+24mePNNUfYoXt3q78zlOoBnUJ83u3d9Vw,iv:nkjgmE3iJDzikyT4GNmxdL8VyeKRCair/skVo41csTw=,tag:/UwA/0gbYR6QSDoxYh4ltA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVzFyUkJGZFVndHZOcEhK
            c2RKQkZ5WnZyUjhiNERDM1BjTlF5YitwclE4CjdxaDdsZTQ3bHFrRnhSSkJYS2lU
            MUsxdWIvRkNUYkwvVm9DMTNDbjM5R1kKLS0tIGFjdUpqZ2phQXdPVXQzQ0tvRzZO
            UWwvVUJOZ0IzS0c2bE9iSWN2ekl4V1UKTfTQ4imRtg3siOYpfgFjEaVEzYWedAiV
            lvX4gOzVKwyvbia6NIgIPFWiO91SmaijJq6VgFd8yyQz2uHwgYtMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T21:30:57Z"
    mac: ENC[AES256_GCM,data:d6+8EWi4+w2RH0Q3YnE9SF1q/Mv5xLRlP3HZZgQe709dh47LJODGDdqH3BTt/V0RVzWOS2RpOVeRgL95LzetM4LlUayGfVl5pZWGJrC1blD53InKDKWwpc6+mjvQzVexEdD7VKR7kVi2pDj5DgCr6Mm5kT+fHs27Ai/sVxF5V3o=,iv:pSydauKoFhSXK6nK5y1izqN/tSCUNfJNOBPw7iDVo58=,tag:zbUpTSrEhI/3uE724EWijA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
