apiVersion: ENC[AES256_GCM,data:7eA=,iv:kIH05LSrSS+U5Cu1WHEtc4WBLg8K99umLYRGw2cGQ/s=,tag:9YxlRZJ543B4SDqlRYupvA==,type:str]
kind: ENC[AES256_GCM,data:yJO5HdOG,iv:LEBGqUwfxIgiuU0D6j/FnQAhwlUdQ628AKDr6UrdYO8=,tag:0qZeHWTK4v2qqqfLGwUwJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YBLTdVUN/CLWeg==,iv:eUE1LPxL1/r86W/+hkdbR2MQezQQXqgTjTD24K277T8=,tag:bcivBOHUFW43uRiAhh/R7w==,type:str]
    namespace: ENC[AES256_GCM,data:mUKXgmhV,iv:IX3HiW2RCbK06K7YZs9MBfUJx30BUCqAWMUdY/oC6zw=,tag:duz1jUl49ZPVqcOzZ6kRnQ==,type:str]
type: ENC[AES256_GCM,data:RRGuw5CD,iv:gcdrXxRXrGe1fxG1KuoVefQRdaxy+MpA1PVuLo5pGKs=,tag:Vu4q2QVWo1X5hO2L+givIw==,type:str]
stringData:
    A2A_TOKEN_HOMELAB_EXPERT: ENC[AES256_GCM,data:KFiVfqP/jXx8Ef9VujhPbKbx8TgVgJKxg/TFOlT0JAGzsq+eWrd+b9xtmQ==,iv:7F8Y5Q+/4ZumUlMVtWxgh7AiZ6mK06vlghIi84GNySU=,tag:m3/lqhL4AenwcmXLcchWnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aEdNSEdpZ1Vsa2R6bTVR
            VWY0VUR3Ynlva3FFcCtQUXVxNGFTZ29acGxFCkxGdDk3ZzI2QUZIczBOUDdnS2Ju
            RjdKY0p4bGRsaHJJd3YvRkJaZlZGLzgKLS0tIGNGYU1GbWpSeDZOTEw3L2x6M0E5
            OUtmdkwvcW5EaXV6MTRUcjlZTFZ6UFUKDTFmQK/3J9VHGtk2sWU+HvKj2FE/0WhY
            mijAKhcJWFQA6s2o/StLy1p410EJpCDoBcGSZzop5GSLWYcG6DHK/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T10:30:36Z"
    mac: ENC[AES256_GCM,data:g3pZDVURkzcjQcsyIDfsoB4kQlM4wXMkKW2g/8vpF+qR1nVgRzvwpZW9SxgNMlykA7TJJ8b3YcJzC4N7edlxYwW4FANPKkpQnDjf8c27W1wmkBtzK6hQikB6coAzk3ykqbZL9Y0pn8AhtUEId2NJ/Wak+1pYxkw11dWUztVWgtw=,iv:sBK5pazBCDVmBuL5dKEuGUhYU+QR3OqwKwkdTueGmi8=,tag:/uqOI9iNS0oroN9Qf2fDow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
