apiVersion: v1
kind: Secret
metadata:
    name: honcho-client-secrets
    namespace: hermes
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zOb5fZIZZN/uDeG6j6ySlyhvsNLnTbvezqrLMp6QhPlMk43qE/dEWK9/TGCXZxjvQTO1sE0nXhWwMM788iCLMAyWVWSqgp1GDQ==,iv:reZdYuHYRDto8EoRWp5JpwydOtbS5oVEPYDCb4SP+Dg=,tag:eNwkzxjN5cSeXVwyyuVxZQ==,type:comment]
    #ENC[AES256_GCM,data:93r6hE/T7XYhs2zGo8I1TLtbaqwVDj0Br4tPDO5g88hAcsLyae2Hc69S2GqRNLmdEQNjNGA+/ayPv+oaqOEJSoG03BQJdiAohew=,iv:PLtcOeTNjoxFeGHkUr8kOVXn8a1jHG5OOHn8fblPCeE=,tag:iQ8ll//FSb+CBAwz9Qj3zA==,type:comment]
    #ENC[AES256_GCM,data:ODdS7+c3tLLQVoADp3Aemw8oU33cVJCfUqIkaQioX04JbmBMtJt0H6ir86xLoAcs7eM/z/K1epr9HvCuZH9zeyesrjJZqvI=,iv:qFQJU9uM+j2clUrOtpJXhOPJUGC4blD5G9Dl16cqQXM=,tag:Bqyi8rn3CO1VKfuxyOWjXQ==,type:comment]
    #ENC[AES256_GCM,data:wOWWI/Ks01tKWEi+uWNAjjE+RjYmJEmUrDk1VxRvPdwdfYB7xTFYlRfHM9DN/8v14Xo8Uf61sSoMJrSYqVBjEjzBJ51IaWEqQg==,iv:k7bpATOBQgmvmxHLaUAtBmfO0JWmJvUrkp0L3iEMvc0=,tag:WtGDb5WDogBEbfPzCfW+gA==,type:comment]
    #ENC[AES256_GCM,data:7loalnGsFfY1ZJW7kZYZ77QeL5nv+6uFAHI/w6a4JoqEeYgXeoDn1FNvfA==,iv:cU4Oo2wyVETPt8ZhjR7p8VYjW7WSLoVWWmzucMmgUTA=,tag:ygy1w1UKHYM//DvZoPq4hg==,type:comment]
    HONCHO_API_KEY: ENC[AES256_GCM,data:3gJAf4OGajnIwBB2NT1ddN/8vDC9xCGusSi52g9bf8stWMe/c0vyybHoi5tf3mLNEqOOKzWDgzZwQHsRpZgJ7QzLdaOpljxw1yiUgrLAfc4lb+IiY4oyxfrnPcTF0uN+dqKHjX+zKJko,iv:qq2v2DZytAqGfHQrbI301znPkZnmmvSmVkoU9zQ3DqU=,tag:NetaU0K2LsVv+S13C5OwAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuajRqT1B5ZEN4NGRUQmY5
            RTQ2WVJpZXFaQVlGdVNqVHVidUVWT1J4YjI4CjJBRHNHRHdSa0RuRVIyaERmaC9k
            QW1NOGQxTGFRM1I3dXQ4Q01HN00rR2cKLS0tIGxULzZwTmRTMUxiZTZvMlB4dkJP
            RWxFdmpCQUpvK3FueEQ0MitaZ2pHb1EKTfHOvjUSZe0qKEhFFZnGq+dWC1+EW9m+
            6Fa7nQxbaenHpP1/XHEzdA6b7ddoR2/1ngRzqwmdmBuC3YpIXauhNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T17:00:01Z"
    mac: ENC[AES256_GCM,data:32uDC6D7G7QNmZBeUYz+neglPhngrU2ngDsVvybAunhyDfZWTryvTwlsqD9mq6ceNaZZB64TR5NEkwZo9IIi+3kc5PVYhDqlbEwlPCkhPm6NeMm5LKBx3PoKK5WiSUjyGMEL2wvZQl+v/nDNeg7gwArVMEKRQD7CFZQWRFtl7xE=,iv:0m4bOKxIvSy9amGc0Zok3MKtWrZbPMhALOq6FCu8jAk=,tag:EMYRvm9pcfcRPNDnYXYVrw==,type:str]
    version: 3.13.3
