apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret.yaml
  - helmrelease.yaml
  - oauth2-proxy.yaml
  - oauth2-secret.yaml
  - httproute.yaml
  - rbac.yaml
