apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret.yaml
  - profiles/infra-expert/secret.yaml
  - matrix-secret.yaml
  - matrix-secret-default.yaml
  - honcho-client-secret.yaml
  - managed-configmap.yaml
  - helmrelease.yaml
  - oauth2-secret.yaml
  - httproute.yaml
  - rbac.yaml
  - hermes-auth-redirect.yaml

configMapGenerator:
  - name: hermes-profiles
    namespace: hermes
    options:
      disableNameSuffixHash: true
    files:
      - infra-expert--SOUL.md=profiles/infra-expert/SOUL.md
      - infra-expert--config.yaml=profiles/infra-expert/config.yaml
      - infra-expert--skills=profiles/infra-expert/skills
