apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets-default
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:uAQjVHEUJQ5UZdgGL60go6Eblw2RMxf9,iv:TzC6q/X5Ye6c4PgFQ+2aoJFcNUShITb5XsaORUK2zqc=,tag:yoNMqceyTJmU0LZZPVvM0g==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:D6QcaWURWxyoS8FFtjnRTmOGOPPzlsr6kS6qRA==,iv:rlPDMxFJl9/VerXGeMJT3gF5ECDGQMefRs31oNuC/3s=,tag:kDfIDvGi7FDEaUzVJg3F5A==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:f24aDU0hUkefH+2F7DeSHVsVcXx3,iv:8ikHPOcEgJkj/FasicvrmZpjt14t76B26Wlqeg8TMic=,tag:L/5IE3SpAfIVsNU5u7J34w==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:b0Ly3B+3A8GLJw==,iv:ADOudWwpRFx6tjwIYzKkzWd8nYINdDrge3jtqtLPNj8=,tag:ycn3BG56m8xJ0O6rDwtFQQ==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:1hwgjpiXjfQ=,iv:QcA66UgiP7YmMkMQUvg+B0gR3qJNBKPSgeyF881Kozo=,tag:XytA1+8knnd0WT8WDcSBwQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:Eg0iUlTOODcQkGzdsKSVzYnAbYU=,iv:n6pxxpR/SCdTA4VdAzuTl0QDoMM2CwpvgBCcK6eWPeY=,tag:6obkqb4AuMhLeJIpm7GbPw==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:mspf9w==,iv:6vCE+3i45UcduYLU389whhwAOgbfz1ZZXUCmQ106NKc=,tag:UkteJ+HKlimbJCc3d4QmbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNHAwR3V2eFFjeUcvczQ4
            L2xGc3l3SUVhb1hqRW1wVHJoSFU5RnhnbVhNCmtiOFNsSDZObHZMYlh5c1RJQVlT
            cVNwNzVtKzBsQVhrTUlJZm8zS0pNMUEKLS0tIHU4NnFNaEVrUFdNQ1pUK2xGWXZm
            cGZ4SDJ2K1p6T0pXN2tqZ1o2QnhjQ0kK3oje9ye4n2w3vgPF5FkU2nBvxv+PmOaP
            bS3wFvKHJWZewFY2IKwbf8okjPmn37EtooLHPTuWySh5m2BxCga07A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T15:58:10Z"
    mac: ENC[AES256_GCM,data:Dp6bTVQPl8SYT+P7XmQKRjyH/Mv2LedpKBJ6I+lXVfMt5ibt9rURe4zVxJNkl42JEveD9jUAivQ5/hc5/SAsFt9hdlL5W+PVqISWnHwsq0oYPpTvqwQ+0SXlOuE56FjtG/0HeL5ROKUu+BOPGxs/O3xqruMP7miB6rpYpC/Nv4Q=,iv:5+Y9AWLOIGlku/SECqvNsY33NGW/C4NFlftQI5bApj4=,tag:Z2sfCmJbHF/oEb//Q+NEvQ==,type:str]
    version: 3.13.3
