apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:7OOQDakgCn+ufP49f/qJP3BVVf19tXpx,iv:W+lfNVkvAH4P9KRhUk+l2m3MDwAzscC64obkoBTLLgk=,tag:83528dkdK4xUiim83e0gWg==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:FtpwfvFVlG2DxkwY2fsrIILtMICnrmx/XYRLuA==,iv:Ik+D+nmA2iaWgPUff/AbzNb9oXCR3ACieo+Ko6lT5Fk=,tag:VLB89i2c+jTOpH7Y9+ZOIw==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:Z1pbyrFXWarKKhzJ+8zZvUcpkOb3dfsox+SIx/eNgZ3MqTX3,iv:vNntv3RKzJgCFSjwhmw8QBElWwe2cG3wbifWNojYPl4=,tag:PlPLxOLMDEmKy/9ZtyBfbg==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:09E4Xcsq7bCuHA==,iv:JzxL8TBN4nTbM5R42ESh9X3VzgmYlB5eCukII01Jmm4=,tag:Aki6i/mA1eJ51xWN3pczrA==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:tELoGiqDOZQ=,iv:lose2WEQKHMvwPqsjfqKk6na8K8XssAes+orgTX4EfY=,tag:zHp12l0SsPD9QHL70EJbkA==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:DNsjPKk9iKR8dMqKc3XDAb89XxQ=,iv:actWW0iX7HeOcHPZtVRjSvZNs9m+ShwQF1FPdTfGpc8=,tag:j6N03iy7mhHLybxm2sIOyA==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:ZfN4NA==,iv:BLz7QA+BqUI454mpUDWvEdCNtjKXSpTDFVV4GWrAwPA=,tag:Rzs6G9Z32hwXadlcU0Ki0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbTB4bkVxOGc3S1BJb2gw
            QjN5anQvWFlZSTBnSkc1bzB4KzZTL0U3VlZnCjdsMGdxaVBab2lJM1R5Ly8zYm1C
            ejRpZ3Q1Qkd0ZzhuU2xPUmJNaEV0MlkKLS0tIE9YSUdBdUE2M3VDendsWS8zMUEr
            WjNzclNWb0pTeFhTNnFtc1RiWVdzdlEK6ZtxRR1d+foJLrBQbYpBY5/f43PyAWNo
            IV19WYD9VDTEhtPpA53tqNkNYBX1xauq3BsqvbRjEapnaLnDROPp+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T15:58:09Z"
    mac: ENC[AES256_GCM,data:CAYVEKq37qWYe6pDextdzlV/ANahA5GY/s2gncyBVZ7jwL0zznlpyaAEgcf/nLMD96m8P4MAg8LRB80GYQss30Wb3fZdCZt78RvRwFc82YNNEZPjHuPw5D2zGPWwU21jYdqAPoHM5ZfyZN47iJD/DOzeVFaWDOWVUbSHS8O8lZg=,iv:bbiMvLLhoA9U6yoRasQumWKz/X5PTC+kO1J0/H67vyM=,tag:hEL0OM0bNJgmwI+QL+IhwQ==,type:str]
    version: 3.13.3
