apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets-default
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:fo46QsnFDr4kV2hBBJYQLa/EFpBt5ajI,iv:Xq8TjupPzZtaYZHD0qAqed5amm17u0ngKEQOgUMFeg8=,tag:hGCazcK6C/A8UzR2A8ppiA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:03ck9f3ExfNEhXS3ARMv6JoPSBOIyNSUZIq30w==,iv:O87qKR1lmhBPAU11ydYeLZh8NqtUT05NceQ0NW7n1ZM=,tag:wA2DJY0rrQ1zuZch57Wj/g==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:f+JNe3KOHdDSLus/Wio2xE3ruOWT,iv:gO9lZS8BlTAnWrWFCHPK5Mg8pVBCDkpqP+kYkTwMcac=,tag:HTZ5F/sxymj4PAAgEX08KQ==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:clzbN7eA3e7Bcg==,iv:WefHRJNq4+oenm836niYziTPFb7QBAeHV7daNxfsMv0=,tag:Pwcz5kn2NI26yXLbutrW/Q==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:RxU9SDaMbMs=,iv:/2yuA4ao4QMbcToI3sj+PQB7WrDS9L8sNmAG9ZtFKnc=,tag:/5g9XP667rT786YUeDVsxw==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:1JrIB26oyNOR1NgURzzKwClugX92aBIXSOCZNv9Qc+10uA/V/XyTZDZ++sYPJuV+WycERNiGsjv3QCE=,iv:/TaSDD65MvNK9AElhVjlWgYeEe3phxAw58ylQAXDz+s=,tag:0gbh01+qQo7Obw6N/QoZMw==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:LHpylcKj3Q4LrAMurJpuSImXU1/QLcKZzS/ng324bjEayGtEEmzO,iv:0fzxrsGadODa83WCjlhlDW6Xvg/bGwFhBszAXq+tksg=,tag:rkULrWmwM7EVKOTIObTqgg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:A0BhUchFUIiZOOGimHh3mBkm7TE=,iv:IOpT5aBsAEnV+HHjbJ2zLg0j2dz67+CJfDc1sS1AFpA=,tag:ngGpkuwTuoQDkg8vZsUTEQ==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:5nphvQ==,iv:nXbKycqhx/kU+DDyGBzhlxAzUqNCZsAW2OB+rqFFPw8=,tag:qnKx6Twl5klNdYIJDR4JoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINjIvMS9NS2ltUExsZVVm
            S1c0TWx6L3BXMy9OaDF1WHlTWGpkeGFiYTNnCk9JOVZiYzhuQ0tFOWRiaWx4MTdL
            S28zcU1lNUpwZXpCMG15ZDJQUEJjdlkKLS0tIEcyM1NmOUxhcENVUXl0STZTNGpF
            ekIyN0FHd0J2a21IUldxZllUT21ycXcKgzNFQpbduyd6AumXxnkQVsvH1z1dr8Jy
            OaXL6Qa+9AwjO5xWkh5Bg2SldM60Hp5OZJIZiFV1e5gj3dWoEoU6UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T16:54:00Z"
    mac: ENC[AES256_GCM,data:c5/atLBiLhKugSP5vuHw1nMYfSGGnn6uY7YIX9qTI5GjhG+XlBOCi76y+P4TUV//TK0yxyJYthNiU0XmpXGfdzO1i2X5LRxp+M+Eoz1PT+E7mwbCFMSCgS0Ed2uspoXtaCZwTOhgW+uOjDtsJnoTM7WMHRgEcGS3ngGoT3gzDZ4=,iv:4u0JQnXY2UJKuCPX3Yy6T0Qo5/n+bSlmSvCwxHA3vSk=,tag:7L0wTMQHBXomGAqzxNS7MQ==,type:str]
    version: 3.13.3
