apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:rxIlDpwPKL8Z4MX0bFVAw1IS17Tuf3r5,iv:hMrylxDWZA2Ipns1inDIjCtMC9149e4KUQP1W5EpBps=,tag:e5iqKLgsCyoPQo0l/NViiQ==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:BfwCQuyW+9WsMLjR+aI1v4SRGoaaEEkK/MFdBQ==,iv:9jh3ZAbPmZlpE8j0L005506teG/aq3fyNqhHsW4AR9c=,tag:0HaDFesovIsaGh+IGxMZJA==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:6nXavNmcozDrjo/V7AhVpjgg6fI=,iv:9nDQxlH2GrXxVznnc7tu1KYXrZ+2LRsS5wNRr1sdOgY=,tag:xn4D9AxkQlGNmvLceo/1lg==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:UhthLA==,iv:/0hR4ARUoynTHUbQY4MlX0gHDHtUkinF6IvGFkpXs0g=,tag:RIXX96HKMK4Lwohysy5VwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMkRwK3RmVDRmQWZZd1h3
            TUt1VklPa2l4dlkxUUdHS1RweG55MHVGUEV3CkFPWjRrTDgzaDVyZ0JRL25Kd1Jy
            RmRTNFE3ZVV0Rnc1a0NTcG9mLzJVbzgKLS0tIGF0OVlYaVFLeGVrbmVmUEJRaVVZ
            RWp3Uy9EUjdrb0lMa1ZVbEFER1RxclkKU/9Lq71r+uzqQTHO8R2hR2ZzXbJvKSV1
            EqTLfHsUmAaMN0zwOkhRpOwnypiOaGjW1xTdy9kBgKbufIiwCkM9Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T15:03:46Z"
    mac: ENC[AES256_GCM,data:8rh10aXKrbnh/BXQdpdBqp7L4c0LJPaA5bZDsMAMM0qO/SqG/YLbT3w/IxQ81HSyZ5dDUFk+Rba1yHUuXr0BX17blZUlfS3r8ZHYtOXkbkkCDfywStd5xVUTjt65WW8LR0M+3WG41TaB/12j2eGtv6stafHBjw1fbZl8yBz+n+0=,iv:U+KzWB8IZtFZpm8noo6zYyZGdfXvl4jcHA1YeE/pDNc=,tag:uOmurOYj7ZSu6nFsnDLtjA==,type:str]
    version: 3.13.3
