apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets-default
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:a4F8rvVdLfxbwIjm08QtAN2mQNbUUO55,iv:Kfe4I89/SBNAp0U2UgJxxWUq7PSB8CICb3LQbCDj6CY=,tag:8akVRI2K0ZnPvrg7uLILLA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:XkuoJ7DcgURE01LtgfSkfWFHHetieiruPcoYkQ==,iv:jAadh6EjuRTvKICJoyLBon7Gw8v1QQbJfqYwYPS/UhA=,tag:oOyfJgIxzpppb6Qbsra6lg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:dvQ2a+4VQt5iQx12evBsgXrn5Nc=,iv:TvHj6gc6LV6Lffln0rz61paJ3nYnosbkHQ5SWjKcjts=,tag:2H12bttM+RrIfXNlMxMiiQ==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:ZFbhmQ==,iv:FuYnfFjvdc1DMgOkYDydwv7PTMgmUpQzBvyWATr5enM=,tag:g93VMOyC34IdB41TkY1hfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK3RlV3NwVlRZcERKNExB
            aGxKdzlEU0VXSy9PYnU3YlRUQ3ljaitDU0FFCitYalk3bkhOOXY0Mm44L1VvcGFy
            V2NDT3RIWDhiQ2p1Z3dQUVBhdm1qbkEKLS0tIDlOZkpHWXpERzVIc1I0TVFxbmVl
            ZEVWL2ZUK2ltU0wyd1ZBWnhWK05LM0EK1txyrl/S7lwF10PmEcnnXaF7dnUJ5+Xu
            m1yz1TIicjOtiPPeB2fhpMM0nk+fjcg9cXQE+FfvL8H2FYm1cgiSgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T15:26:45Z"
    mac: ENC[AES256_GCM,data:jafzo3MuALbPKGC3SJb+GgVU9VMY0ow3n1v7n93kKCmO281dvi06meG++SnURSiVgRYuOkAbUo8UBrsBeikwc1lOTy7LrQdY50DnGEDNWekxCVQLqtbdaKvku/7NYELKbo+G9HggOApXjJEA1qScwhN6HIyM0+7LTGAddzr6+iE=,iv:BPhtXsSPUsZUMvXtTsm4KrfDf3GnRsbWbZitY+TD0ow=,tag:Ddz8UNglV5AMliooRPv/7A==,type:str]
    version: 3.13.3
