apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:A6VdSlpGeFPLB/YayCALSW9/MLSYgBMA,iv:Ixo0sdG7HTLCS+dzVQpyn/QX6DrCDDv6u7px2+f8KUE=,tag:baSR2LqWB6cvk0Gy36Pt0w==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:BRmtsG/qzdqJE92Qxieh2oH2IBRIdLbBnbBdNg==,iv:KBY7Y04RjoSRjGMGOTcszS5BQvT6CFvgT91lF3Pe+aE=,tag:HoJSmf06pdBKjlBR1l2RKQ==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:S9G/M4Bpj8md1RPuK+5rYlRmCgcS5OGoL+i2CgPpTJ6zpA4N,iv:MT3agmTiC2G03BhmBLQDxRAh6aCnZZGnJXpM9NoicMs=,tag:vwmb5daZHj3QEatMyiebJw==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:11wHLrroVRL7vg==,iv:zQS5ryseJgSn//ODKmtM6fFEX0UkbJAeVkMzmhRApw4=,tag:nmKYkoJCBRhQ/9vGjyWI7w==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:8VX+5kU7gKg=,iv:tSV4KUiMqLZZZMCiUxG8K1k6xtdL3A+1LIiHxXJFSWg=,tag:0W2S8OwcT7RnjP//EtqU3Q==,type:str]
    MATRIX_RECOVERY_KEY_OUTPUT_FILE: ENC[AES256_GCM,data:1fR57zeOy45cDVw9N3VDtWl41e5JmKpJdfr9SOkOeeTqijeWk4ashYVWmAjgo6cABw==,iv:xMT4EN7sHus1v+JkHszfRlfxt1tazTVwosaNCZ6ITQw=,tag:Ov1gc/8zqBNfsL1TIcDhsA==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:i9auHxS4sgf7kndcTAn3YFSme70=,iv:aJbeJrODtCqxrADA8hhuJVAblL9fFop1M/15YDUe/eU=,tag:3dB0a5OCZuMTG7tpBN1ihA==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:YFpRdQ==,iv:8YVnlHIHsWQeNQvUT4R5qw64DxUPD//5XQKDEehBm3g=,tag:loZZab2rZJMPQJ+cE1FVyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VmI5V0J1QVNNdG9vbWxu
            VGljaVdZY3F1Y2VwRkRZUm5pQzVpTytlNmgwCjRjd3hZLy91akxaZ3lFblFHSHlL
            NDhNbTF1U0o1NmhJaU1FYld6bjVmbFEKLS0tIElySDNtQWVnaTcyRjhJNGF0YjR2
            Sk5WejdxNlhRNUl0VzNlcDdjbzRQMFkK6w89QBGvjWdNK5W5B3VQ+xXR36BBhLoT
            JmkZW7nCIDvmQQJdPxcL4W9/EYOGrPMFrOCuUFsvaO+8A6sb9uXnEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T16:18:52Z"
    mac: ENC[AES256_GCM,data:A9Vgmm+Xgzjf9x81/I6d459QiKEJpLe3Y4LRc3GT08qnyqsCtZVpyg8jtwQ5Y7iUvzSkjwzR8G1jxYF2znNu87ZDZ7pMNQK1eDAAUuf28gi0GvZTm2UsYGvfYYhGH4aOFYhiZnwd4lNHWc9jfAOiLKaDPGAOVOI1IojeSGHBcEA=,iv:6cwqB11voA59l7rEuWrC58PCo77sKAZMZbqVz+rFFmc=,tag:soi8J0PqB+ZWx37+iS0stA==,type:str]
    version: 3.13.3
