apiVersion: ENC[AES256_GCM,data:gos=,iv:WJ7p5A4ycxtT2DGpOGjMJDsy5ixNZ0oM86yb8UEILU0=,tag:/lZv77lgUqiKP+DsuaP44A==,type:str]
kind: ENC[AES256_GCM,data:2Qj49wAI,iv:sKH+cCns464gMCGEi2LCm3kgy0sGzn74CBKZ9kovtN0=,tag:p8ka9Ov6e14Ud76WveWIag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HhINeWs4MDjAhkwqujldA1RBSH0iTA==,iv:TxoisMtYzM+V24cwCGz+maNrkmjnUkwbp5VTGawqAS0=,tag:NfjQSQ+uFKrKZqDinDpP4g==,type:str]
    namespace: ENC[AES256_GCM,data:8wSSXQF1,iv:TbQbOc3ASE2KgEQNRGj2GoVm06YecgzKEfrRdK/ILKQ=,tag:3W0iJZfrwvqgNyjRZvMOMw==,type:str]
type: ENC[AES256_GCM,data:L55WvwJN,iv:bCP/silZvr125gNWgEuRLStpj56rOPau9Q2nUsyh8a4=,tag:4g6xZ7/1o83NZwA3U2jV2w==,type:str]
stringData:
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:mU86dLniQVbyZQvaadP7iajtJoTH/0tfXyc9IqH1fQxlCYLvUaQ++uog6iSomK+GtV9F9nm3z/FH+rI=,iv:7DX3nYFHxUIfB41KR1llv2us1A46Iv5VKY/Y6V6OBvU=,tag:wFlMwhmRWyn7iS34Wa8CYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU1dDb2kyclBvbGgvWHlM
            bHJaN1NmNTRFWnk4ZklOUjlhWE41RFZ4VkM4CkcvcTdBMzgwZFptYVJRQ2ROcUN5
            YW54K3YvaWc2Z1l0Y2E2VjNFWGZZdjgKLS0tIFlkTk9PMDBxQjFCUW1oN0hQMDdO
            U0szSXg0RHVDaEtMcnRDK3didCszSVEKYj/G7kZu881UpllNz/n8U/reMrtL+zVm
            SkNg2J9zGOkG9GLOLlEqaxzFFYSZ9hd5sGeRf3svIRA/ZuNyt3VtNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T22:17:40Z"
    mac: ENC[AES256_GCM,data:j9Q/SbYBdO7ksRTow52OdUehQ0u6uB5lIb7+YZFyCJBv7GGIh2KIqOkFC6HqlMdRkSR57kYjOpOm4Y72RFgUZyq3ij6NObHmt2yh4eNdyzt0oGkT15d+kQFkrG0poUACZkrGfBFP+MWsU9Lisdktf0mCW2s06FcPMaTAU52TtRM=,iv:uh2kRZMsdX9ewBsfgDlvfXJKKolQeoNy06nieQnrzh8=,tag:t11EZcfMBhSx0rlFhqdPfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
