apiVersion: ENC[AES256_GCM,data:gn8=,iv:wAocxAIGfYnZddm7r1nIR9KrtKZeWNC7mE238yYpotk=,tag:yzEUoUd3+TTimqQpagVx5Q==,type:str]
kind: ENC[AES256_GCM,data:kZUJap/s,iv:MfnpyxhetIb4Ufbph2BnCiLQ5YsUQZJ8iOOSEJnINIg=,tag:jf+i1Vk/aOT02eLig4rWeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ngw5bFmz6IIevJyvw6bYdvY7Eg==,iv:RCLJz2PlO11z/mNCDqjc6u/THtozDJ+UzIHulGikgTk=,tag:KrF5eW2jQ6dS0wmEH99YhQ==,type:str]
    namespace: ENC[AES256_GCM,data:Y6552P9m,iv:PWw339eZBEC9WnnnICOzPpOUD7otYMMQtxY4EUJwJqY=,tag:MS63Hea6Wunv2vwpOlPKJQ==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:+fb86RiNhqoTJQ==,iv:0ZVYoLnXaG/2nYEB3Lz/oS9k509ukOxyak1o2ZnCn4k=,tag:zv/pF9g/m7Va7ls/33uXwA==,type:str]
    clientSecret: ENC[AES256_GCM,data:wfFBW5WwThvtWA==,iv:/1aI3Cxvj31sazDPH3jpI6BcKh3aRqilW3eGrGYbeGE=,tag:rSKoUbfO85ZVNhkB7Tg7mg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:Ff0dVvI76b2k8w==,iv:gzx6KzZR9EzMwbCtmLimc7LmaiaQupEwHaZDwLHMdLA=,tag:afoAyotyHCCeljtbi6haLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaklZakwxVjdDK0VUWndV
            UDQyWHVwdi9Yd1BmSzBOOWZDREgrNVJRQW44CkhSU2dpRUVUeGZTNVhHZjFxVVRK
            TFI3LzNjR2xkTTd5TjZ6NEM5VkE5WmsKLS0tICsya01tS0RaazNqNFhqY3FidmVv
            Q0Eydk44Q1VSODhpU0FFeGpvdTZ5RnMKw8xlslZnKR00RSW5f8sPUH/vkiB+NPu4
            NU1f2gMLszWPgPQOimOdxM0K/ipCzIyLjsukucifkYncR22BFPBD3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-30T12:41:58Z"
    mac: ENC[AES256_GCM,data:FeQcE5S6GqNG0HkAyQQf7wPP/8B90B364hgHKrJxdah6Bs8pETKiK1wIXGhcv+Qk8fFIMX7dV4SfMHDxLU3g9KQfQheFpQKd1XIMm46q4HK/NJJIXx8jTSwGhsjtFsQCEZjeHEKxBqBuET7gn/PfWNejE02+nSjoKr+aoZmITlc=,iv:krDUNt3BNNznUF9BxiFG+1cThKF5a/mMDpN54A/n8F0=,tag:dJN2E8Kb3prQcovdDtaA1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
