apiVersion: ENC[AES256_GCM,data:gn8=,iv:wAocxAIGfYnZddm7r1nIR9KrtKZeWNC7mE238yYpotk=,tag:yzEUoUd3+TTimqQpagVx5Q==,type:str]
kind: ENC[AES256_GCM,data:kZUJap/s,iv:MfnpyxhetIb4Ufbph2BnCiLQ5YsUQZJ8iOOSEJnINIg=,tag:jf+i1Vk/aOT02eLig4rWeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ngw5bFmz6IIevJyvw6bYdvY7Eg==,iv:RCLJz2PlO11z/mNCDqjc6u/THtozDJ+UzIHulGikgTk=,tag:KrF5eW2jQ6dS0wmEH99YhQ==,type:str]
    namespace: ENC[AES256_GCM,data:Y6552P9m,iv:PWw339eZBEC9WnnnICOzPpOUD7otYMMQtxY4EUJwJqY=,tag:MS63Hea6Wunv2vwpOlPKJQ==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:BZLKcmCQSVJpCjYZzQCRipxHxEa6cTykfmE7bYk1VyLOZe48,iv:kBk0GNwtyRyfbgofz0TXZReH+Acj5vC7MXVdxzOmlGo=,tag:TBtDbnw8DOR79Et2dXgVHQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:roRlPAquhB7wKuIv2efbk6c+zXoAEjwog1h3/27rgGw=,iv:JaTojDLeq0vHQauMqoKO/Tgurr9i4+SnEH+Zv7CnZgg=,tag:FlPNS/txyULtD9Kir9eVdg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:d82V2iOPyaRF2qE35Ju/GGhrUG5Cz0Lu4kHktRFpPz3f63HbeHbARPrWVng=,iv:7DSG87w3kOwE5OAvej/uUN/yLZbMyxjLLDdEKCXeLME=,tag:bkz6Uep2U/dEo7ZLnwcWVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaklZakwxVjdDK0VUWndV
            UDQyWHVwdi9Yd1BmSzBOOWZDREgrNVJRQW44CkhSU2dpRUVUeGZTNVhHZjFxVVRK
            TFI3LzNjR2xkTTd5TjZ6NEM5VkE5WmsKLS0tICsya01tS0RaazNqNFhqY3FidmVv
            Q0Eydk44Q1VSODhpU0FFeGpvdTZ5RnMKw8xlslZnKR00RSW5f8sPUH/vkiB+NPu4
            NU1f2gMLszWPgPQOimOdxM0K/ipCzIyLjsukucifkYncR22BFPBD3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-09-12T20:35:09Z"
    mac: ENC[AES256_GCM,data:nGTIOv6f5A18zqPUOeRidIcUhPRHkguAqyGMz9mCbrpuh82r+VzMj20cepg3++vAXYIx6aSp0IjktDhY87HhQlLjtYwBRiewMJhCewsRS6C9hHHgfthhNk5MClSxajMTr55tbtPAZQt8uEEJVPwN42SSUD6q/y5FZtkTq6KKSd0=,iv:cZs0YTsmyQy4kx3ld2ALO1BWkHTNAs8Do00FrJgr18w=,tag:fYMPUIbSu/BEJLR1Bb7huA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
