apiVersion: ENC[AES256_GCM,data:0O8=,iv:rRBHj5SrWV3Pr0ogweeW3PbJ8uDdyi0wZXyTMT2l1GE=,tag:nmHigYGNjQccWF4mXHLj4A==,type:str]
data:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:ok4Kyju8BDhezkGvlh0epiggyP3TvmLfRhgsq7RgKre46SWffgkQ21do8njbdoBJQdwj6HNL+vnSxneTCaV/riZWaBWC4HW9whu7DECL1NAJ3Y+USI6NuoH9altvx/9p9ugI4neSYHzR3BQdf1J5v/j0jv+9KrO5VdNlka6l+/5AfM1LMFQPPOBj8Zzj2Izb,iv:xzJ6MoX9VW6v6oTWdtcGBh1+3P0QG0Qk1dKTSqy2wgU=,tag:ke7EQXrHXYfJw8LC8xL3Vw==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:W4s6I/LydUyOVI9loxUpqIMTNT5JbrMkhaKwV5JaHl0dhmAfS8dUPsLOksflklFM0WyBlhmnZe1q6m6BK/3JGiGnPnhNNg+t,iv:uF74reM0gQGrylj8HwB6suGRfWIkRpsltgir1vxgaIw=,tag:zAfwZz7FgZJgfSYdFQpoJw==,type:str]
kind: ENC[AES256_GCM,data:55xW5F3d,iv:0z/uod/kofGQcPpYrh2qgx6GAG5c3Dhuh5esK306q/c=,tag:YngFuKnt3QPr7nQk+wTGRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zIeeHEOy2/wYo+nKoUM=,iv:JSCraOW97ASeHOWLh2T9xfXxK1rGJpP7+6rPpOB1VJI=,tag:HtCnK3hF4K3jOHnADwjm6w==,type:str]
    namespace: ENC[AES256_GCM,data:BpwLp0q7,iv:boPy7Qbuw2nTfl5+Zlsj5Y4n6tYKR+9EJZwHAOlrrSs=,tag:1zy/+32GI4uq1P/SvQJxwg==,type:str]
type: ENC[AES256_GCM,data:04pPIguZ,iv:CX/WqLLo3Y+phFjhsntX0Mtxii7sjzc/5gxlsVHsl4g=,tag:ckaUaV13bmjAnFNxaqJwkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZzdsOVEwOExIWlEvbmJv
            STZONGZhVEdRYXVKZGZSMDJiMVZzZFMyVlRZCnlweTkrNUZCQ0hiZFNaeml4NGxG
            Z2tBZDdPazBIYTNJZUlkNHRTVWZsTUUKLS0tIDFBT3p5TlRJSDlKcUNlQ2FGd3dy
            dlRXU1FoRG1xWUZNRitPcG1Pc0xsSUEKxfgmbnFb+WLNpY3Cv4W48efsR9QW555J
            KPR4QArZVlQoBgrU0Fz4jhaq6Z+vUkDt0+1VHcRzTb2Vf+LkqpCEeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-29T10:53:50Z"
    mac: ENC[AES256_GCM,data:353xXr/Qm4clDpgOQINIYb7nMYqWSjrJIIgjl2JlRU3OAMJwMA1CaKRq8Si7tYnse458gNLrnOpjMgCuZ2xszKW3SyY8m5BSX05d+lKXBhfnUBvt3VrBWV16zj3oWqzIcbX0TT4v4hRGl38b8fjy7Izp0kWzXcCgIyscRMfwZDw=,iv:3MNmtI9l0Zk1azfu2oyks/ipFsrPgtvasQEEYG1K/AQ=,tag:GqprZUS/Gb9V81OUjLCskA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
