apiVersion: ENC[AES256_GCM,data:Nd8=,iv:TsLHLGt/hSBuQZahHVfhtz98a1EcvJ0WmMtl2Pxajuc=,tag:SQLX7Z1/sD1tvC5Ok7KVYg==,type:str]
kind: ENC[AES256_GCM,data:HPs+Nrk6,iv:yEk4LKqW+aT5BFg/bnGml95o8Xt6eoHxP4G9/jO5aDg=,tag:BdKmSEkB5bE04t2nHENo+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1w2AWwkbOaaJfhKIyQ==,iv:Q3QVE9Jt6huZNBit91DSudv4M8RWO6dqGWGFOD0pRMA=,tag:RHMntBf58YGl+kzqsVXHNw==,type:str]
    namespace: ENC[AES256_GCM,data:+LOQaUuD,iv:1KTjjcsfwh26fX2dSSkyhnzVpQzMrZ60MsWywLTYa+k=,tag:NbT+lAbB+SIWKE+fK//Vsw==,type:str]
stringData:
    HONCHO_API_KEY: ENC[AES256_GCM,data:+yirWsWSzu3LUsuzX2/UG1WJ1SRoOvVA2LudXHj771fDQvNibPzo0stUjbEL4KvymmCJVkGCPt7jDpbhIw2DWY0zIRGF1XvW9DPjQDmNAcWXB7RGtVvQF3SafCw14KG1uwpH9rj9wWA/,iv:oDin17pfGxfsMTNsfmrF+KJN6XUe144LkHiS0CfnyY4=,tag:2OaG0DBe+6WRybx1RTnP8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVG1nYjR3aUkwRHNVcHZn
            NWtWQUhtd1ZSeVo4UHhtT1ZSdTFscmorZlNFCndJV3Q5UXV0ekFRQ01VM2FOR1k2
            c0puRG1wbS9ic3VtSFRBV3Q5bDl4KzQKLS0tIDl2VWRZRUZUVms2NTJUZWp0dmlP
            RFdIL1BqOVAyRmtJdVRyZnZPY01zWG8KImlRWrsSEaUq3PSbVdc9WyGwjEzoC5u9
            zQ7vnYkfIGg4l0qBz1RnZS6hIHIHVg4nLHkTjnxjMREYKn/FZRfMHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-09-12T20:35:47Z"
    mac: ENC[AES256_GCM,data:OHwITAmlO+EaG2U3Rp1s9KBj1vTV+bmJDTGZYw0doZQ4c+EEYaEBP9AwyxG6Fkq52MxK3bdioar3kiqhRjRCNb/iaQl1pe4ZExnijuuw8fo7QmHxvbcj0fcU9ctIZ8cy7GAxfDMghhmqTDz/9nBBBJMUUuCjjclIGCRPXavd/B0=,iv:/bv4KXZKalbkraN7bDoIqOI71O5kcptTkfql7KHRB3c=,tag:icKQpcTecXhDTWyHiTE5hA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
