apiVersion: ENC[AES256_GCM,data:0O8=,iv:rRBHj5SrWV3Pr0ogweeW3PbJ8uDdyi0wZXyTMT2l1GE=,tag:nmHigYGNjQccWF4mXHLj4A==,type:str]
kind: ENC[AES256_GCM,data:55xW5F3d,iv:0z/uod/kofGQcPpYrh2qgx6GAG5c3Dhuh5esK306q/c=,tag:YngFuKnt3QPr7nQk+wTGRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zIeeHEOy2/wYo+nKoUM=,iv:JSCraOW97ASeHOWLh2T9xfXxK1rGJpP7+6rPpOB1VJI=,tag:HtCnK3hF4K3jOHnADwjm6w==,type:str]
    namespace: ENC[AES256_GCM,data:BpwLp0q7,iv:boPy7Qbuw2nTfl5+Zlsj5Y4n6tYKR+9EJZwHAOlrrSs=,tag:1zy/+32GI4uq1P/SvQJxwg==,type:str]
type: ENC[AES256_GCM,data:04pPIguZ,iv:CX/WqLLo3Y+phFjhsntX0Mtxii7sjzc/5gxlsVHsl4g=,tag:ckaUaV13bmjAnFNxaqJwkA==,type:str]
stringData:
    #ENC[AES256_GCM,data:B0EJgnwF,iv:bQ1mwLlkhU9DV/+SAvYWXLIjS9ka5EzRPHoYKwMhvAM=,tag:Te/qaZywQLDqyiQR3e38Ow==,type:comment]
    HASS_TOKEN: ENC[AES256_GCM,data:RlFo7nGeV0mYS3WrnMVrIDK5hvWSCuOOnmOEtJhq7QiX72V1gqAAB1iafYRE2ohPwjXv96eAKkRjdRsPdC7eGWoglu2nGv0vpwHozPLdvhVydzos9lX57S/eVPy7wbE1E+fPtp5ILWZoInAV/16jjgEbyufBmewwMw9KoGf2J3jMGgjD5SGMRGJjiHub8CLmmFnfF0Sl3DmsfGu4xO4rGBo0l4BxxLrNLXr5ZKLx4A6Z01aLxh3Z,iv:f0eXeYQCjiSTLh/+MAbJ/vXZquAKaY6NPYiTvzKWbhA=,tag:ALfM0bNOWTfzNVS6lALa5g==,type:str]
    #ENC[AES256_GCM,data:i/DKEL3YvVyCMg==,iv:IxcppaVRaXDMTE0E58o4icMNc2KKac328uM2OERl1lQ=,tag:318JYzkPLJFhYCTOHc5Gww==,type:comment]
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:2WiVjadbieZfS5mNvzqACpbQTeUJA0C9mjA5upa5mdCDG506CrkXWjZ5+kHtxrvQV9k5XydqP2gQH0O84DVoL/ACwoRoxHLBuGe2+kGE9+hBttjJ0M2kXKMLmMKkjh1JP65q0s+2RL9FbgcO,iv:fPxKtihv4AbjyMP5vaInFO/t6aWiJzUObvxgecJstw8=,tag:9CsGUjdTJyBFKSBL6+ZU7g==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:jed187NjP5f9g1JFCvIRybFFB81WqDcS7GC0+nqq5UzCCEyfRv36MRyN/o6oGTRDPblmvhs=,iv:/oSqyGPGO/l2mFPrqgjQ5bV3M/Y9uC4E/Z3InbNB7kU=,tag:KPnpOOdEiKDNp5fhJgL+yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZzdsOVEwOExIWlEvbmJv
            STZONGZhVEdRYXVKZGZSMDJiMVZzZFMyVlRZCnlweTkrNUZCQ0hiZFNaeml4NGxG
            Z2tBZDdPazBIYTNJZUlkNHRTVWZsTUUKLS0tIDFBT3p5TlRJSDlKcUNlQ2FGd3dy
            dlRXU1FoRG1xWUZNRitPcG1Pc0xsSUEKxfgmbnFb+WLNpY3Cv4W48efsR9QW555J
            KPR4QArZVlQoBgrU0Fz4jhaq6Z+vUkDt0+1VHcRzTb2Vf+LkqpCEeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    lastmodified: "2026-08-31T14:59:44Z"
    mac: ENC[AES256_GCM,data:H289jFrYuLh1CzGsDEKTZFELlNN3TkYpevWMj/Wc5wEMn0F6lZXK7Kxb7f6ClISzw9gE8h2J84VidjjMzbwrABbsLvBKfI8/frKEIPLrdnTx6HvqIoyE0uhW6hNqg+RyStGjDg8OPS/l4CeniP/p4PTrvVGYouttMee48HJv5s4=,iv:n3JzmrqgnqQ77YL8SDCbTDYnUXbvmBdOKyAuupVqorI=,tag:OoZvKWmmIRAhlfJ/p8dOaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
