apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - httproute.yaml
  - oidc-secret.yaml
  - hookshot-secret.yaml
  - homepage.yaml
  - httproute-livekit.yaml
  - httproute-hookshot.yaml
  - hookshot-legacy-svc.yaml
