apiVersion: ENC[AES256_GCM,data:Gmw=,iv:oVvkptiJUB2eBrhSxGXHsf8XhQ3ULWsqo6TJ4py0Wts=,tag:HkvKMTbQjf8SFXqeYGrscQ==,type:str]
data:
    config.yaml: ENC[AES256_GCM,data:KcGC7gihYLtd7XJDzcGcXqnl/9lXNOZSem37xusil4D7WxOds7KXUbdk/lwoZTaazAkjtG7segMqg/QEe5phB8zVsc3MdWWxPfzE/JVfcJOjhdWh9BydzBHQOPx9nn8bWKASXAgpX0QypMn8T9GzkDmLsbRUiqC/TqM1YHk4duck8AZjXsFkAPDSqb3LlR7laUZ4S4TuNTF7tueH+eWB84I4HEIDVObHEmsHYQ==,iv:5wFPX2kIrq0jvhrA6Bn80OY2gAIQGAlix+JUwvrKXbM=,tag:Kf94pOa1CYPXrhb2hK3ufw==,type:str]
kind: ENC[AES256_GCM,data:xVcXZxEG,iv:7XHKy0ZCDJeFh898ZVRl4oDRTeEGTlGhKOdOjKaXwdk=,tag:QLIH6ONvMSoIs45eJrVxpw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mj8uSyION+yxmA==,iv:KsbaV0l+/RgykvnIKpaMtAAbquQ/8Vpah/erVquIJXs=,tag:mmqYyGcFcCpgrwarsLK5sw==,type:str]
    namespace: ENC[AES256_GCM,data:4f9PlYfM,iv:cCRSxL9/BWE+4la6tbefqjcW/1JYshfMtHPUrcYLhC0=,tag:oGV0a0dcrmFavz2XEIHyCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdHZLMUs0enZtb2JjUlFH
            aGNHTjBEcVluazVXR0ZNU09qWmxKTnk4RkdRCm9ZWFd5WmgzUFZRTlNXa3VpWXpm
            RFg2ejBqaVkrbWk1eGRXbVFCSEVqSzgKLS0tIFpxQUJPMXhzUHAxQ0ZoYldtVHBa
            aG1XMWl0YldKYTRYeXJUOTd6d1pvbjgKi64lCJ5kCBaI+4UHQAf83b8kdFAfSTnh
            VjtA+BB1RtWCdMBfXduvjlnasxvjlk/53Ay6XZufhBP8yQ79fQgbJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T22:56:27Z"
    mac: ENC[AES256_GCM,data:t2UmAmB69lzE7dFtEbO4kltSt0kLXr7Za6lyR55L/g8ybfI6sSLsb6Cftqa8OGaFAv8iSsUaeo/mp55PFk+ZyD1RNDuTX1JhEOzAPJmnLOX+xTKvVFC6IL/altpfQsY3bExxl5XfeIQc8OwFdzK9Q6PPK8g9YQXBDxhZ1aTI2Mw=,iv:4P1rIaTJDbgaaW3pLkyRh3YMSscU81fv1ycbzUcbF/I=,tag:ddSsNpiJjzDFZppT1mcgTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
