apiVersion: ENC[AES256_GCM,data:WgM=,iv:1TkOIMp0ttxixK97i1FAEK3+JNxs4YXMPUN5TJUsY/0=,tag:eaUAkE1HiACGNzGSc9zqAg==,type:str]
data:
    config.yaml: ENC[AES256_GCM,data:vD3pPWj25TcM+ZGlDJOcIXAp9LeyGVsH7pCMj1iSzWKpvyd7xh3jf+ndSY8a4gePq1FlReqmyuWSETeQ7ZqwfByJFp7Ayb+taQLl9XL3hv9+DhUamVLZzWPMANSK6NR4Ym34FmB+JtTnYs/aIF3Vs3QUY3//uF7+UCYYmnanUuABABR4IHvwby0Gh4Oz7i84PG3aWRdeIlnJbVO5cINoDl4UbGAXA2sAC/kCxzvXeZpCsf8olJnW8Qp/+nPL1qAMGQtUr05Aylo9ICftC09Gw0nWQp6qFyb3p7dFldjspdRSkYVE9kJMPjMshwc8zAgoAFfNhw4Vi8M=,iv:sVsPnsIZMusX9ZPYWgHXPetruKPGJS4daHXlg82hCs8=,tag:1SzZNpBoDs16uWIfE0I//A==,type:str]
kind: ENC[AES256_GCM,data:wyYrvYp1,iv:FnQgshDXHiM4BsdWSXIi8XAm/W6Ot6LDdmyFEqjGKao=,tag:7ILHDkmM+v/97dG+XALTzg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nkWcS2jSmVHIMQ==,iv:Ykag5GK7JSLwmHHvJH2TWiAXq0VwHQFLPuBkkRCF4RM=,tag:8bP084WzRUJFNzmlsgoVTQ==,type:str]
    namespace: ENC[AES256_GCM,data:LhjI4xxA,iv:UqfphG3h/f47loCRU0bRl2oRWDvJyW2trCUJFREZb3s=,tag:lEg8JT0fuBW5FFFPgGEdeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RXRlUDN1cm5EVnBDN1lu
            SnlkY3RxYk93aCtJTUJnT3JSZElObHNnc1NVCkpXcjV3RmQxQkRiUlRtYm5jSlpt
            NmxzQ3h0azVKUGpjbTY4dkkyZmNXWlUKLS0tIFRCTXFpa083TFdQOVR3c1NaY05m
            UHpHbVU1QTh4MUkvK1p3SWp1eDJiZVkKx4SU50UzkIYXGM3DeDQCn0QznFRRWun3
            yhkGR3PJ5hrZnEr7fUHgRbSlICfEyhsKqOV6p1BGRH2WpFtM7cuP0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T23:04:48Z"
    mac: ENC[AES256_GCM,data:tASnxYO0ApMfNPUxEyvRm/yzmDgBX5bc5yPlk8TnZPQkxO8EzrGnWsld6jy11ztTBM52heOUPSQUUJ5g8BFqhRsVazt3ox1sYmB70MUo1P8YQJ7zlfFzUbW4xUegeVSy0JbSjLWjuPoJroJFPaDVg6ATKlgMXEaWqVxPtu084fY=,iv:4ZJQO2QdGNE9kuM+Un0dN60xJSEc2/8kbMuitPK4wgs=,tag:mgGekme1pDT/2tHM+7AutQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
