apiVersion: ENC[AES256_GCM,data:3XI=,iv:FVluUejjNLGe5+lNqnNqM6GOhcX5kT6HUG0DQqgIOJQ=,tag:ilzouZkcF+0XDiNoat68Fw==,type:str]
kind: ENC[AES256_GCM,data:k+VwIY8A,iv:ZXzpWSDGrWzJoRBW0WjCwZWGBP/U7s8HRcTKSQjEuTM=,tag:W1bcDUm4/cSSOL8heUJeZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZJ9xKc8qwihhkRTqJF6ui0o=,iv:B5YKgsa0rXhItTUgHZ7BWRzAoSvyTDBlMqqdin8/xOo=,tag:98sVef9MxBa1fVR1Qbm3kQ==,type:str]
    namespace: ENC[AES256_GCM,data:uZ5KRJk9,iv:hcw6FWrZKbpOijf0kYrbFelhQi8fDXIVenFLB5xBqzg=,tag:3v4tCjp8u9gbDK4orjVv/Q==,type:str]
type: ENC[AES256_GCM,data:t2SwLwnq,iv:vaXEvvKiTNRGcH8tgc12wV51rgXJO6cjiSDCI0+maGA=,tag:gKW347lAFp7vLAlP15Fk0w==,type:str]
stringData:
    upstream-oidc.yaml: ENC[AES256_GCM,data:xFA247qmt4ZFUottJq5t3VHFIAu7fH5GTwv3efgS/VCESWvImdaCfFpXHlWU59tt+0IY9pUwp64eMRBEsNCSWkpzjqB3pIutX/ZE3Rx74qYJPV9hhVYz4gzC4wCg2bxfZH4n/0lcfwYljEuKaiB2xjh5cv9ZJFTTDP871nDuY9cJcr114dmAIdZMk9qdYR3jw6jPdfynQ4bAvMtchPCSEGcN65vJz/dPNN6ndXdonZ4z9t/fpfXsVXnbf8+ka2FK1+7/Sesm3kR+CTbdp1GQcQ6Jz28vUlok82GvSm4iwDCjnYx8HIW45aUJ5MeXNLuqq3C+XBCP+FSJBPAaZ+mZbxdJxuk8DdysOfZ1G+TvOk1crctoV1SIGK3Oy/tQ0JjCRqBpEIE5nidHtK3PDreJTZc01qp2RJJPkpCuUfVgFPsok8ANxHZRz9yq6lWhcvZyrOKWaM0x8L3iZOTsqsP6HrLa6BxQ5vOfRTE5VNlxTgWFoVt3nNparaO3hwgb5ayGunqNUfSJaue23uOHv8OpAxQEf78PopsjPG27miFhA8kWZr4W315pjz8zFTFp4+Du7bhjrJ8DHc5fK7VK1zWph4cVxLeWXtAliDYQba0Jn44kRaaIbfcZhd6G+UziXUvcQ0wnypMbBctNf3bI/FWXLFywd/3Bswx/9S5l4Gyo4hFvy8RzSLp47SFfdo2uNHf4bOFTNwBEBe5+IXb2Vl+bC1mmRzCv2ZrwYIqN0LbuNNCq,iv:EE/DEh3rYjeMR0eV5bWRZlCqG42c8UQiQmx78geswzU=,tag:NH0c4rZOoHn386f1pKmQrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM2tVb012U0lOUTRwY3BJ
            SGRsY1R6TGt3bFdZa3hoSE5sSTZ1d2VQSmxNCjluOWRRQmozU2NZcXRPM1hMR0ox
            OUZDbzcyanJTR2dnbWlQVE8rNjRwMmcKLS0tIE43clJ3KzFZNlFwbVUzeWxNQUho
            UFhkbFJEMjB3dXNRRTV0QmF3MnkwK0kKH0FyRQdISRIT0HchJFFjj6di0Et3kdOZ
            CYdCYn2YHEvUqXiR7sf45vP7YZ3sEfQAb3jqXOCDmwDetnVzPRsG5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T20:30:15Z"
    mac: ENC[AES256_GCM,data:JjT5CfmEReFV8naYPgGMt6m9yqL0kHGvDrHFgnW1jkNyCnkeaxOyQNXXsGX28t/Gle4LZYCkmj1S+6TGhofOf7n33XQwC9TGigWEhrIXQnyTUGuzzoFtoQ9D1znO++n2UkiZ0lqYfX1RDtW9xQI+u0t2p64mYE0pWUxwPiYq1NM=,iv:ig4ON9aJ6sdAk+B7SOkQ5WL89vu0fxED8JI2tUYsJG0=,tag:V1yHCHgaijCoYA6bkXlVFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
