apiVersion: ENC[AES256_GCM,data:hAY=,iv:3027Eg98D0onOMyo9Rcc8uLWzcYWSBzo30fkQwFyQ+g=,tag:VQ9C0dBzk/kD2WvTXh9O+Q==,type:str]
kind: ENC[AES256_GCM,data:pXlDaiZh,iv:BEnwEySDwx63IRA7MM2SkktRRt0d7lC7nC1KzOql8lc=,tag:a4hSQHYoRmWVUXYIhivUEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cwHxWE5HwWgieqnV9yYcuKE=,iv:jvktQRw/n4LmQbBfkAURQJ7GuwlJ2ohtRqcpOxKqiyQ=,tag:xpZGq88/2+76wQZQ+DNpAA==,type:str]
    namespace: ENC[AES256_GCM,data:C+5kKTNj,iv:zwA4na9YTV9pUAEX6QJISGMn5alIqqdeGGkC37v0tVM=,tag:uyR9L/VufSZb5cTMIfZ83w==,type:str]
type: ENC[AES256_GCM,data:TgCHwjz1,iv:i7nwyjICv8in8/XWdD4F2AfsFJvAOBZVvwY/lRH80qA=,tag:XV8DLrnPB4M3a1CxqPKKYg==,type:str]
stringData:
    client_secret: ENC[AES256_GCM,data:iIr+3P9Kg41/ilRUohC8tjZtrDJF3yCCffEw8Yp+eDI=,iv:dNSdK169YMck03WLUY753vFnymrvT0J4o5earRzjl3k=,tag:QhEkZt0g/XK5MGPlaMSOjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T1dsU2pZV0lOU0Q4U3p3
            M2gvbWFudHJuTGsrcmtMRWdVS2I1TXhlZERjCitsWURHOGUxcml2VHlKTjE4Y0ho
            SWcxK3VFVDRGSzRFR1hFU2JvZkFFVlUKLS0tIGxnQVdZdVRqdEs2bHI0dWErbG1K
            elZBNW5zVXJsRmQwdUhWVUh5dDUvZ3cKraSdHv/WU02mvkOtsgJoai+Q7yY0jiIE
            Ne6+LjyFmu9YQiooqEjzRSiLDOUAJ2EzDQboR9z792IPhAuBE8kEKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T22:22:26Z"
    mac: ENC[AES256_GCM,data:KDzQRMtsQIFPY+Qgp+Eu0O6F0Mi0bc8iBM7Obg1VSnMA6sbrKir2bIx8VE3hSATKq0WiwdAmpHneKNdVa7KYjKo3PA9GnYJEW/0VM7BHG0wKqv0uvdDBtkEaIP7W1rgjkk0ipTHEPOCv7alvrsxJmhJPh18itghMwNMr1/d9xJk=,iv:XzuUgKgHDHIHtVKvSsf6F96OXX1dtd+nC3x8kHx5nto=,tag:EpvbylrbpJIIpdBq5UCM6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
