apiVersion: ENC[AES256_GCM,data:Ju4=,iv:MS3DsBEALNDzg6FzWpEV8yOwHLetoU/FInEJPHou4F4=,tag:Umyv+heAiobwNpz6z5+ILg==,type:str]
kind: ENC[AES256_GCM,data:bim+i7gA,iv:vEjDWDR1k7Y7AyKC+UltU81zw/DqiXnlAaYRPwckymQ=,tag:3yyVFsVh19d3yqhehrYjqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZjC1IP9OXKuXd8GGgM3PCrE=,iv:BnAL6ZuGu7I+Kbfj6x9aOBt2zg6zRV8cRRi2ZMAEu88=,tag:xXTdjeOy763zfc04hjGuMA==,type:str]
    namespace: ENC[AES256_GCM,data:bmwAkRHh,iv:khgTSgjetlN1gHs+mKP6lpGNP0+MTjCZNZZtOyXeRkQ=,tag:2A0yGEnRLi14g/NthD8RvQ==,type:str]
type: ENC[AES256_GCM,data:Ku6jq+iB,iv:peLAV3DmGSOJXpO4EEPF7sSW7Sd/hquWHWxa+NGlnJ0=,tag:1F4ccoW+k0Uxg0mGJ5vBug==,type:str]
stringData:
    upstream-oidc.yaml: ENC[AES256_GCM,data:HboJvi3nw89LvLnL125bfyR5u2CS8LULEuVT6obUbdAyzaxvO08sMKJtTYN2CreM4rKN9eFN2J0zySTp8MwvRH8M4wgwdQ7jwzYNS3f/JzI60yBm9wd14tBVd+Kn34PP5CESZTOlIc4ZUMsC6UHPexge0/bd/lHXgv+BNXKEv0NWZ9E9e8AK2z4pkZMwrVoSWujiiv39paSt62iPz8ILSk1koZrYahGQ16oHpiFuk2vdfib2jFfhIzDPefrmiTYerLxGNRY+ibVztm4tmIk2GXs84hOX9M/bFy+QqkoVgZNc0iTiIqHBztVZtVdjzXfuRcbJemDAKu+0ZkKXVfunGLXhUKqpakd56n4i57rhZezkl28VM404yRjN+R+s1pFOuog6fwqiOJGlHZZpSWI3jAvxKQzcsyoIR/XPKmKOe9YglbMHw9GINuR/Xm2nJtgb4dtnQ911oIEoXHtVpRgPKTwMRR2mMPWJpKNXisOn6vlGt+D71Q1pxwlIBbHsKvDLxdMNbtJhKEwWQkhZkfXCLNOaTNQq/G6R1RL3XHekl7cpGjOkIvLtJ/0HpRLAlGttwVXkpDc3c7Svivio36ggMcGHAaFnNSbTBd6vAvyrttC1EI0SaFLJubxWDKVavbs0+7yAq0eh3mnRdxWKfxedUHpqHynjiTXFQLSbucpeSYhU6/aRgCD+KtsoJHDPetr5VKasNtl25NiK0fbCVxU3dvXwqNpEOsclgO4kOxa2zPs=,iv:kUQxhTQcvEloSSEsCCN+FrFrQ3erlyHQJa5+uXGBcYY=,tag:DBuEnB54ZkLxZz1ya8SzqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYczNGT3VCcWhNbXNoZmQ4
            TGZReWdVOWtBVXBCaGF4Y1BYVERlNUJ5TTBZCkFLTWFkQnR2VkZrRFhYRzVCQTZN
            d1puUHlXUGdPbUNCbXg5Rm1QOVBwMU0KLS0tIFBTNW1yZ2NOU0J4MkRSWCtCdVhH
            Um9zRlZPTkZhSnFvZGdEOSsrOU82S2MKz/hKIpR4bHcApi6oZoLfOaWo3/Z/VuT4
            1mUfOFEWkbzAupdmFJYeXrBalXpTTO7PKQa2aEpJqdCo5LplNVruvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-17T21:55:43Z"
    mac: ENC[AES256_GCM,data:5c7hqxBssuStCu4rHPiGw1l557CIUSA1G8U165ZXucpBghK/0E/lYObuNE/hKhfk5j3eVshbCT8iTr93ihAfDpNcnx0ID1Kdl8ATzsFBfj+Nrdlpj7unvumMidZCfIZjJQL9JDDjGWBkGvnTKcjRhtZsrUjiJwuRg7U+zp3v540=,iv:sizORYcJEF+J/5NjPGbU5azWYhdCULSBp3eFF+r+unE=,tag:3eWy6g8GCKyuww+T8yq9zg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
