apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit-1
spec:
  template:
    spec:
      containers:
        - name: gluetun
          env:
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
