apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit-1
  namespace: netbird
spec:
  template:
    spec:
      containers:
        - name: gluetun
          env:
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.96.0.0/12,10.244.0.0/16,192.168.1.0/24"
