apiVersion: ENC[AES256_GCM,data:9eg=,iv:xJeM9YlcqTsV4L9mKuUxENUGCY7vF/nN3U/45PO+c7c=,tag:6paAFrw7V++eG1LMESjiyA==,type:str]
kind: ENC[AES256_GCM,data:ZCV+ErvO,iv:+qrjZ8p4jyniw+/9iWNiL4AkgUP1GNa/w8S0YFwzN1Q=,tag:PS8HrGYeav94p5oYgdXJYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XYkv6Cu5kVrSFYP8V1DBKUc=,iv:l2/g0vmyCFtSQy9kgL7114KVI/r4qL8OXCPOCWSSDgQ=,tag:BhWUES/MPha2+eziOO7N9A==,type:str]
    namespace: ENC[AES256_GCM,data:ZPwBlPSlow==,iv:I4Tt1B7ibfdLLdnrTqhTktm2CjoNx9fIi1uh0EqNqdo=,tag:HIhMNtfSb4lc6tUaq9UzVA==,type:str]
type: ENC[AES256_GCM,data:ha4xd4UV,iv:qPy9Viq1JUehEFly6chuE4wix/RFWJqJ0MMGQshD8sQ=,tag:O9zKeIGjsuN2OORSbasFEg==,type:str]
stringData:
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:TxBz6gL0kQ==,iv:uzamdAXchXTdsmdqmn8h8Aetm/mcBXXUq+xNB+1H13Y=,tag:fZZk5isfA3pKWQpKzcK90w==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:uaUxwPc=,iv:7DTsULX2YtdJB6+B2wF6G+kZDUvShqcl6WERDsNEZT4=,tag:ITMAaKpslCRu60Nwr1Thew==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:QdNX6iE=,iv:d+zjAQMP3epQzthZm9ic7b//pcCMjzI037gZg2b45xc=,tag:gBsUdaFWmaCJkHKgvdsPQA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:YCrSnmk=,iv:1jF6U6/I/0wSVMMwD/rqr0KtoY7chZ52O17Np/FQvW8=,tag:Qf//4M+2UC7Ozh+jbso5yw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:G0e0Dg2youcQ3h8=,iv:gfIbfjVhNgj5Tt6gBaynb+Gwa7AZjjJekm2K36ZL3gg=,tag:na2DOSXkaN9LUBU/KGsnYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaTRzODVQWkNCVkV1d3Bj
            NllMT2Z2OFBRZ1lzV1M3ZElPZzdIY2g4Q1VBCm1xY2ZvYkY3a2xSK3RsMW1IaVVN
            V0lIUDRKczlseFNiaTdLekFTa2pNRncKLS0tIERxUnFZRDJpS0tpUTRUZUFIdFBR
            bDZuQjhwQytldHA2a2x3bGpLMTVHcGMKrKu5N4lwQx6i8BGT+mEqvJiyOYtW8/n2
            Tdx9mH3oWtxfKCDmdJct6MpoJjd8pA5KTR64c5sV4MeeBowhqNU42g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T13:34:46Z"
    mac: ENC[AES256_GCM,data:T0hyqtYgQEKRe3AJM60hHfu6aKPBXWtL7mi10j840CU9oYVbbOOoQyFwurozcYNJJKjqgav+/Yqq9lQe2YSAb6wyIuF3dmLFAdyNgUQvsGxp48ivvD0aJqBxmqGyA5nvIxCaUaOIA2TofvE8JhVfHRNrMEzJOpz/ITnaEtgVqqo=,iv:P/0dAn9AznZCDajiuvbjmaZ139GK2ISCZFy8qf8pJoM=,tag:2uVhFff9g5FZHy/XdCNYCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
