apiVersion: ENC[AES256_GCM,data:FX0=,iv:z+08TP4MGaPxvSHFT6oF+JYw4Yby4yu5wJNusn1wMRA=,tag:LkYZ+FnCfS97Sgcmvjiv8g==,type:str]
kind: ENC[AES256_GCM,data:7Gt2dQCc,iv:gkildj1vd4qAzrXq3XFPCr0wmc0J/XG5T2hwGQEJCcc=,tag:f07aemYjzeK53y0vg1iyzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E79p2+xsMncKayOBO9aLqK0CbI1O,iv:+stq7XyjuFph33fuAUVo7rFm1bIoJOsllubNtdTdjgo=,tag:AfuWPWRcvVUpPqdMBbnMsg==,type:str]
    namespace: ENC[AES256_GCM,data:reuUgValeg==,iv:wSqUYmwPRTYrMxVa65aM25z/BiwCWA27ofe57U0Uu50=,tag:wOFMpNP1o7pRNI59a0ZIlQ==,type:str]
type: ENC[AES256_GCM,data:U9X5V6+D,iv:7JEB0qE+iFqY2pi61XGr2kNsrIdTWJlpZkzd0jXq90U=,tag:hxr6aeUen1mqGydmlQLpGQ==,type:str]
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:2kqCZx+PWHe3C3BoxEaHZ1slukc/DpbshS8=,iv:3bSpemWuy89HZ+ywGlaKuZR8L3rtr3iiVvPPTe1+Zwk=,tag:7yB6lWqHTCFNDHmR057wPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPajFpNmEzSGw5ZFF0aXBG
            OExzYlQvV0MzRHJNVllTSS9wLzMvNnN4NVI4Ckl5RFBZbkdubkZLZm1UUEltblMw
            b0xRTmVuOGpVM1FPMEF2ZFBTYTZYNUkKLS0tIE45RnNBR2UxanM0alZLUTE3S0FK
            M2ZDZkliOHZ1bVAzWThTYm9FWU1UMmsKK2CJVaRjEHiwB2hSEp079ezY9Noob/o1
            nqg/P/iTij4bAuYddRaCV4KzXQlbg0YpKrM1vPInGNncOhPjXcGQ6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T13:34:46Z"
    mac: ENC[AES256_GCM,data:fprLgrq1xaNXgllDLoShRj8J2CHQp9jd/X116Ofg6yeoyhGbqxa873Ctig7oGleAxxUhoP26GVrPtEg5O9X2Oih5FlTOLRIG783tMqUnjACTgrSupQmLe54IUBOU+EeE9EA4rFlSW1h1bwRsCzNV49BKp8oF+D/yzNw3caotdbk=,iv:gPIlsXJJtYNE5zZju0w1oUwO6k5Q4y70zY//QveHupc=,tag:Pvnm/632ABnPK2w4dxF6tA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
