apiVersion: ENC[AES256_GCM,data:HxQ=,iv:pSindgickvr2Fb7skNNL63M/uvif30liOLva7/Jcgpk=,tag:ndm0ln/nrf7l9xih6v9dUA==,type:str]
kind: ENC[AES256_GCM,data:1Ns2R+vP,iv:IpHv68ezo7mQUUsRmaH6HI1GCUi6mEVprxMpJaLyspM=,tag:D+n07aK999GjRWb5CPHHvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XfIHnApzKX8CW/ghD1oV3L57Jw==,iv:0p8llNrCqleMKqgMFc+mAx8+67nizNwJNKSr/f9jktg=,tag:sfIWgkaRNgVBQgVVAAesxw==,type:str]
    namespace: ENC[AES256_GCM,data:u4jatQ4=,iv:4F8oZjcK5+CfKzDjdlGDpc7pC72nwbJtGmiSJkVSym8=,tag:N2jaLc1opJG0RwbpI83cwg==,type:str]
type: ENC[AES256_GCM,data:aB4knWMN,iv:vYIyg9DXD86JYxo30V3bXfywMrHrWFMYHlecSQOxeLE=,tag:luBP1na1q8BoJg3X+PZ+8A==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:xHLVgPU/C6+D37ndIdYk+nqnFH2HRXoed0BaIPQ9DC5BDQvO,iv:XjDBma0aOG5Wx41FB52oxSGQ40M7+tR6Cao7PN1SbkA=,tag:4hYdWeH+F4IKmcsyArqpew==,type:str]
    clientSecret: ENC[AES256_GCM,data:R6SB0+dqJL6zJksBtx4DWUQf3JMrrVrXq/7xzvuS9HI=,iv:LTGhUE0yUKaH97FuYHeih79Bst+5GZ3AHxzR2LMne3g=,tag:abSBew2ZRJQZVwhn8msMSg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:PbPGok5x0qrx6BztdqDwa4CrXDr1COxZevSHPIKfT2k=,iv:qYfrc/r2uh1F3Wn+PVBOgQYzMCNVFz22kVPklukPc7s=,tag:5Gn5pZocf77qF6L1eW/xjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dndaQzBoN3orMGJWOHZ0
            VDhIZzl2RkhKTVNpRXY1OE5BbGY0R21jUG1jCnM5VERENkQ3MURwSTFuaHZNaE1t
            Q0xzeFBhVm8xQU9oSkN1R0lZaVQzYWsKLS0tIHpOOHU3bk5UVUtIb2E5aStWQ0ww
            M1psdXFudm91MUFTa1VLVjRTL3FwWG8KolRognV81EoqKw2k5rEl5fkz8oimaVAA
            myXThJavy74nP6EoAEWBnk5IQCGg37kJvEQTHHG3/lPvVkpzQj8VHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T14:23:17Z"
    mac: ENC[AES256_GCM,data:tfbP5qAwbHqLQarnjmfnQqbpv1jzQEZ5pZSKMwH55ElSZxbcY+J9Lx4KMdAGgxGkN7PFVQrMpUwn6xBjtreB1S7m27Zj94oSrpFBZPh7aW5THbDykt13t0lgMNOt9V3FJ0WeCW91d70tcxmpYacQDf+aW1bKXXG7NcY98k7ORNc=,iv:ascKXVNVeEH1LqVFK6Uqh+cRNfHGoPcpWvZ+RSKas24=,tag:jaVC+RhiIs2EzrGAxhBL6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
