apiVersion: ENC[AES256_GCM,data:BkY=,iv:KDtrNqTs5HNnXBD1qfZwtI8HKhFCJ3p/+Bg3aEb4jnc=,tag:dGA6upBZGl8Mr8hfhaAQzw==,type:str]
kind: ENC[AES256_GCM,data:hY7vnXRt,iv:0hrmZ8DSSwXZ4A0JLduiSWq48hb7MlGRVkAXDjTp+Co=,tag:zlIxpXHXj51v7PQCx6UylA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZB8QQRFMh0dJtUr68mwtIhdP,iv:XodCmq3CgBvraMuKUb7Ba0gFN2/mNSHqgO/nZ2Mpkao=,tag:GwMvV+uezAoVQ23abO7/ag==,type:str]
    namespace: ENC[AES256_GCM,data:BkSLsPVR,iv:JtBayQ03CGxmBhvt3/dmFikktMiOF09EXp5j4R6+ZQ0=,tag:rD6/3dGASJ8x0358nQlGew==,type:str]
type: ENC[AES256_GCM,data:uBGTQyqM,iv:cb6Rd2Vj1C7Sqss5qVXtBTKUBMb83kZeAQG5W3wx6LA=,tag:IfSqshW9L5tyESAcEfdQgQ==,type:str]
stringData:
    A2A_PEER_TOKENS: ENC[AES256_GCM,data:Z92Ss+fXYFZXnsgyT7y//2G9ci8nFKeb6HXSd1SbAWN7WQNdsawcPcepVoVke/eoQAc=,iv:TUjRIR69RWEN9ygdvK1yI4UbTTpq4pzOyJZYXUW+m4k=,tag:35J8f7uFXpoD3/0VhtxrYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VzFJWnE5Q2lzNmtLSHFr
            NnRMeXBQeDE0WDZZdXJMY1d0elJkUHBkdWdBCkI0ZzJicUtWa1R3Y1FieDhQWmZ6
            WFRJSUpFY1NWdmU5Vi9YQ2o4b2lyK2sKLS0tIG1IbktKSitsQ0RLS3dseElEZ0tH
            TURwckRkdnp5cUwyWGRQOUlIWkY0bEEKWkqnXNjAV48+ysyVmBur+7E6muxticRQ
            wjvZrSxycJ8OiC/SPP0uI7TRimyPtHwOho+V+QNJ7ZLk0fECN0tK3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T10:30:36Z"
    mac: ENC[AES256_GCM,data:7BO9XUyERwIB8N5/KgeJOP4cFfSelX4s1g1FzjmL3xOXz7vinaUf3G08itrHc0d8sjbTI3ljIRdoFI+FWCibo3HwetCDbKcHE00zWDqzIWcltyA2/IV4ITt3Ls5J0+IAmhKqz3/Q3Sazm2yrnjyHXdXI1yijSgLnv1mTCUdYedw=,iv:UebEjcCSps5qRr/IW2Oni4tXuyRjCSnWWWsO3JNPUgI=,tag:9zjVVsrxiAnFv4Ff0uQGCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
