apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../secret.yaml
  - secret.yaml
  - matrix-secret.yaml
  - matrix-recovery-secret.yaml
  - a2a-secret.yaml
  - helmrelease.yaml
  - httproute.yaml
