apiVersion: ENC[AES256_GCM,data:K+g=,iv:mzpoYfXjlgvAQup5Wh42dVzCaZdF+eJOzxK31zXXf2s=,tag:6WF1nFv89pU3jcYyP10WSA==,type:str]
kind: ENC[AES256_GCM,data:2Hx36d3N,iv:6D959Jn9m080VMxf5iP59gy5cq2Zd6BTok1SoFoYaro=,tag:c3cr6vdxROcb+BfwWxvXYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TGuc8tiEsOea4EIN/K7Ycd6yKd02as5oqJAZ5kKv,iv:Dimhi694PSG007t7FDcR9eH5ZDnZe4iRduJf2YPhnU0=,tag:U9oSEfENeHV4mvVh/fqhZw==,type:str]
    namespace: ENC[AES256_GCM,data:YF8qSKcE,iv:458Ai8mIf/TzbgiK9MVrdnYazmwNYpfyDJ9ITnPu53M=,tag:5ASDt/pmvbWO2ss7sqPMfw==,type:str]
type: ENC[AES256_GCM,data:owuKnA68,iv:XPbhcFNcExxyqCBTPpabOXc5nqcoj6MZzVNxgM4dW90=,tag:YEqncDCyEj1fmDmGiJUTdg==,type:str]
stringData:
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:CML9hpdqKxsSDYe8n4HkICoTHElionRF+BRq3T9WCjgppUSButdVj3cZhEVlcWju+b7+F/b5vNYR/us=,iv:Rlt8kGHnhEhwjhM6KyZcZWj5l9UHeTGqHttrsvDUDOk=,tag:K6gSKeGgBS5eAcSzJoDLow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQWNzTHA2bTZGZWVjQmY0
            RDN0cTMxK1hlRzA4aDcraU8wK3pHY3QwTVdRClJBanBOMDJPOTQxaXY4V2s3clIx
            RE50SnB6ZGhacURXUEJ4NE1PS2I3QXMKLS0tIGlKRTFWTTYwcEhDN3ZsYytjLzJ2
            WUpHZ0NzRnlqU0tLOHFaQXZCUzVxTWcKMGlhElduwfX2m8jKZ3Tcb2ALNhCAjb7T
            Z3BrGpRPJIk636tQgzitQqdSV9WaYPUJHjE1uQytkEUypbhUc489Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T22:17:40Z"
    mac: ENC[AES256_GCM,data:2esYzI4Ulf9Q3OL6aqwUlMM7t3V0/OYBVNmZleID3r831De7JwRenYC44ZRwH8kO2BDIDBEiBl6pZXQBqDBhCDtM9RUhYP84R/yjxPKlekeoCpHq2powlAN8NFDykXGuftGUiWN9NwDjqYXAZNvK4OB+fPmOFMTX9kBOVR6GeV4=,iv:W4J4DW+QccxpS0JOOJOVZZBIBS3JFWfTHplA4hy1lHU=,tag:VnvPz1aJibMYGWkthsD7Uw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
