apiVersion: v1
kind: Secret
metadata:
    name: homelab-expert-matrix-secrets
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:MJzLk5GZYeu7nnZkkWojFPPqsF42N3/r,iv:ES6XUdb2RTGbXPCyPYTpeZvNJfjRP06lnph8diqjRxw=,tag:qRvDbJ5HJExpC8WgqyZYjA==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:miqU+C9yAJ78rP7Cnm0r5PIi5Mh+8iWUrcreug==,iv:K5Sww4KwbD9ZwBXpnGidc28BfUGyn9nha3cukwbe8lo=,tag:5xQ0pWNXWEMK75vGi2dZpQ==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:CTZzLE0GX1Bp0s+3v5jvZOYolDEGkVfPLWWlkNvxfvRkvtwr,iv:6wWkaZLqk0u1RZOGqp0hZhVwbrXyp9yuCm+Rbde2Ops=,tag:JBESbcIBwfCXKQLDxirDtw==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:nnZZFxOJe0s=,iv:+VXO+tbELMYV3/HIWLukyfC7YYKTQZWUtVVmRKqEHY0=,tag:PxfiON+XR14nnBUX9/pzhA==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:yu+I3COqrSb7vg==,iv:kDsw0uyoEybVgi+G5u5GuEErjjIKdi7c3UQhTpDYGYg=,tag:R0LmTpzHaTN0idgg3vEg+Q==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:d61rfyIjdFxEXj8SOsac61YdH9MgDM/O,iv:ftbv1ZVCN5b+K2wjio/cg2PzerqswPhF5lRGgQEDbGg=,tag:ggK3Ws25XzbplJPnBzHCkg==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:0nY7fc00eQPzFCf/mzr+gPaswt8=,iv:Umd5Uj7CTvJJWtfjgf1YJzHJuQxG2iwrqvV8HbpH5N4=,tag:a66quruFp1c3SYoxZFU1Vw==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:Q3SDeQ==,iv:crjfgzyIuMXAqPqko4i0VpcfhxhVvgLyxlBnTQ1zKV0=,tag:wJSDkkec3rnZS5Ieq+HVjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR2k0NXVkWUl4Y0t6Ym5M
            dW5xUldJZGtyRER1Y2RRcVQvbmJuVHhRTlFrCllJbktPUlI2akhBSThVK3UwRlJx
            ZFNSN251WmlrYUlyTXhHTUhGRkVOcm8KLS0tIHN6Ujc3czlyL0lMV1B2ZkExTzdk
            NFdzcThZa1NrSVpOaG5PL0FjTmlhcU0Kd0h2fBh16+84SYPFnOemtDKcxpj0g45W
            X6Y+evVWuGRAr1q6KZRYjPmIir3gS1AEuOHS6rfCBaw/EYI2aHKYhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T10:54:18Z"
    mac: ENC[AES256_GCM,data:nIoGJ4BaaTh6T8KKRCzYPjdSWAyF0o/hrDWX9GBMaPDCf9a411gS3wPnuzSOVLEysCW980pGHdLedAXOzan9xx84mHEbO9yy7mCCpmTPpV4cXkxS9zY80Chd4/u3Lsak2YRdIdUneDia1M334RejaI/DfUNv9V3rwhMVwxdIkAg=,iv:F9K2gWwYzYJmrvKafo/yHUrcLgoikJ4yDjhSmbLpoKI=,tag:T4RsDKR0aPtH9ZO7wg/T3g==,type:str]
    version: 3.13.3
