apiVersion: v1
kind: Secret
metadata:
    name: homelab-expert-matrix-secrets
    namespace: hermes
type: Opaque
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:oA5GnF5FZnB1Ilx+Hy+L6cpvLDIb4L41,iv:25sbjZ+V7uHr6KqRO35bUBNwm+urbtoqPWTzUHuf9/k=,tag:BB1zyYKiq8tuMQwYE39VCw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data://740eAGXq7akPAaN9EQWamTYW2JuWD5ErxJow==,iv:e8W79dqa2l/essyZfKsZChw7ohl5P/pm28OuyhpZVwg=,tag:7Jwap0w4KAIuTbBc/R6I2A==,type:str]
    MATRIX_USER_ID: ENC[AES256_GCM,data:N1UJAJRcZrrjrZy8k4BAtZlj77rIQDp18h7HmqvVSDIXJy+L,iv:+B9hm8j9MPLxZWg+QqCXuQaGKUZAGtWQuTFulgKdPNs=,tag:Q+aSlQusbHikjoFKxNIrRQ==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:Tm8432M9sXyhEA==,iv:xQmDQx0WVijJQzFxwVxqCgHgnV6oBUThPUbtrpVsHLY=,tag:7I+4GUMLuKMP5pyc8QDY0w==,type:str]
    MATRIX_E2EE_MODE: ENC[AES256_GCM,data:mEuoMdEsUjo=,iv:iwXyPuX6iOo2IAis2xWSJsuQpPha3AxALDGnZktYmX4=,tag:DgoAZQFfY96bokI+UgW4bQ==,type:str]
    MATRIX_IGNORE_USER_PATTERNS: ENC[AES256_GCM,data:wrcr8zh+A9uQA96RV/Y5o87mUSAMmM6c,iv:5tKwlneYZxV2LHiwVIQPnB/2FhB+37LfDi5vG/3g2pE=,tag:FZhHzuKXuLI2a1RfJWWDFQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:VkvJWVBIP6sGu1LUS0Zog8dRHVg=,iv:2lS+6ZOdaWmjoGkctVmWD4Y8/5sQl7kovab20KjRO2w=,tag:v03JgIfNNGLZhxwh8mWs9A==,type:str]
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:cPSWTg==,iv:CmNUC+cbeOrhdV77cmWwwJuWCBFoNM8U/dnUpdpZKuQ=,tag:OnZnH4OnqAxF6qcRg1234g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ0F2cHpWckVpS09jamVP
            OFA3Zzd5YXJCYXFBYW91ekdQNU9LUXMvUkNzClFrbkduV0gzYlFFaElvMVMwRWo4
            V1FkK0dkTlNrbTB0bFkxYS9Jc3BHU00KLS0tIGVTNVZQaTVZWlpCQUlQaFdTT29t
            Y0d2UGVLZUdYazkxREpsczBPdUR6SGsKMva6aokeGtGaepbpDMus5TIo/urCOkb0
            qTxgrxVtSMJAcVXTXQcVjGYTrGjNezNdn5TnhyOndxCerj7OScuQzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T17:00:55Z"
    mac: ENC[AES256_GCM,data:9eeTk1WTv06JiPcp7brr0B5CTp9LsMfg7nR+riURGyw2BFBRkj2HhkkiH/5xIRVw+UunTIAhWWeWEJerWh5U9YLyIbD1n7I6YxxkPJ+vM6sUAuszjW//XOCs6A0akPzuia6rAexrUA1jayqc/FgE5PHtz/7z+JQbfi4zyuiQ57E=,iv:4nMY/wekK5Hdm4nYM49IPc4qXx+zfesDGggeVhHm8eU=,tag:7NopRudBGVvvFK+OIlmr3g==,type:str]
    version: 3.13.3
