apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-oidc
    namespace: matrix
type: Opaque
stringData:
    CONTINUWUITY_OAUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:TXqdpIYTxe6cHTDEsG993d94rAFOh7n+4sFfubWDri3NgqVY,iv:fkdOAM7rS4OSAFjUHolAiXob6Eeh+q8smiCCXQbtoBQ=,tag:1UKhw00jb4993b8SqpK03g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVFF2QzZGTFZmMVc4cFps
            dnhBcmVNZElYcmFwWkcrUmVONjVXcE1Ra1RzCnRERVJYcFcyNk9CVmNDREwvZjlm
            RUp5SENBUW14RC9TTnR4bHdSTXo5YzQKLS0tIGkxY3JpckVRYXJIR1VQK3U0Vjgr
            WXZ0NktzaHlhaHdLUzdZa1lvZE1PZUEKkxYM4FjEcxEpr+nzhXUjkBvy0JrOoRhT
            Mzdjj+ZU4gf1TQM4yne6+okftvCnnCm20Z5hvnZI6j1N0MHynV9g4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T20:15:36Z"
    mac: ENC[AES256_GCM,data:HKJEQC/h63r6GhiU1m2t+Cde9BOw79UkQubEJSHCp+aUz1rlbRL9xtz+5rce+yklkzhhd8Jye5pq0gtG17hQasBaNZ/+TWW6Uda2ygaZQMFuK0+h8x8nvGTvvofgF+hLWdJKhiU4Hn+Iz3pPM2v0oZ7TfkfUj/+98TRufjy1wdU=,iv:oDz1lEHIfbC9tWSrs7bS6GeWUoIMDZ/pESyS3iJ58IA=,tag:nNFyA5edKmurjfq6HXOT+w==,type:str]
    version: 3.13.3
