apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-oidc
    namespace: matrix
type: Opaque
stringData:
    CONTINUWUITY_OAUTH__OIDC__CLIENT_ID: ENC[AES256_GCM,data:Ksx+/qc6xqCoqg3jFjWf4Jt8qBZLJCBQVePvRE2VPmzZTL3o,iv:ixCjJth/FSpANlU94hSpEz6rVrHVCjeL1JaFEUYJd7Q=,tag:M50ZSCRvRkvmX0FraVWxrQ==,type:str]
    CONTINUWUITY_OAUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:e/f+OuBML1h1e5DqqgzyTQN+rHorH+cMzvaR834ZE2Y=,iv:b3qQJ+LGbWOYE9cN1jnekuZGR1rrthgQ7ecmRJvTN2g=,tag:fM/t6bg7y8ifGZKyWHh57Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVFF2QzZGTFZmMVc4cFps
            dnhBcmVNZElYcmFwWkcrUmVONjVXcE1Ra1RzCnRERVJYcFcyNk9CVmNDREwvZjlm
            RUp5SENBUW14RC9TTnR4bHdSTXo5YzQKLS0tIGkxY3JpckVRYXJIR1VQK3U0Vjgr
            WXZ0NktzaHlhaHdLUzdZa1lvZE1PZUEKkxYM4FjEcxEpr+nzhXUjkBvy0JrOoRhT
            Mzdjj+ZU4gf1TQM4yne6+okftvCnnCm20Z5hvnZI6j1N0MHynV9g4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T13:25:54Z"
    mac: ENC[AES256_GCM,data:p6ed7WEIbS/n+dyqlgDEBvZ3FPyPMjxb9CrSq6IBDUhVFM1z7ng7LuFSd74/s7/xv/CnwAZGLPoLdYfnyraW1WmAzrJMuzjib7+VpwOUuu2+atqLkNeyFwkGa58dUPULhGDh3iMj2N/xvKnWNkxPgmI5pZZ3SDPvTxWlnlLK7+U=,iv:pH1bOrqiuyvp8OA9lAQ3EN+miaSBGJ6xLAx0pHdZHoA=,tag:UNOY+Qm7olA+pMPIpQ5F7g==,type:str]
    version: 3.13.3
