apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-secrets
    namespace: matrix
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jlvXEJ5viWOWgKSm2mp4DgMobUF4medjIsQocrI9vKNd4/BGh6zkDwXjgeIQdZ6+s5oxAZJ8VB7fRNbLoyBw8ecL+Xvu,iv:zswJGX4Dzy6PZ0LJj7UEy0sF/LchhdH+/VL71/gxR2c=,tag:lNQ7nw35ydnDquo2QE+bPQ==,type:comment]
    #ENC[AES256_GCM,data:1sGyx7bF+eQs2TZv53pzc044CHwNBiXZfbO+Y3ouQxumw8daHgjDDaLjFrrFsnjoi8ZfZTfE6AhT0gjfswhyHPCdpUM=,iv:vwfXAwouhf+00V+GxOTMjDbJwAZW09lmkDLamz++AGQ=,tag:s1Ev3wlqFwRmPTB+raTz1w==,type:comment]
    #ENC[AES256_GCM,data:stIAg5tTIki/jQpzkcgiQjxTH1Vaecm4/qxEVcIDccw3oKInFBJ+o11cWwexU3cedNc0xy3k87fsVaxfewhrZohiYHKK,iv:SMk73JZLQNNf0f6OdLE07WhMUpFwAhND0rNB4PNyv+k=,tag:HUq+/uSku9EULCQ06VfQ/Q==,type:comment]
    #
    #ENC[AES256_GCM,data:IRJdDoOjpJjbWBcwKPrVRU48YyWQ4aK+tT7WiUyWZptXAUnX+GxRLzzkcgWyNDtegHMeoewWhHryqNgt+z/2vKfJ,iv:FMXJHVV1ErCRI8d8JrmYD/uqE0XZAvb15wiiwvO79gg=,tag:ZzxeH46glvSIJmVXEqNAGA==,type:comment]
    #ENC[AES256_GCM,data:09Nsy9wdrGYtNytwK1ie4F20xFKi8hc=,iv:vQBI/VrEZoPGpsHF9NcX26VPJdi0gSrZf4o8PgMGuAY=,tag:k96NmIFhQxQisuNz/nViLQ==,type:comment]
    CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:+5q+QNiQnm75P9AMMI1D09FMYzxkemADyFm95aGpFK8=,iv:08XBQe9vDT6Vc6a3pUcGqBUvuNkvG6ww7Nx9G4+xRyU=,tag:TTm8Z1bzOGq3WtbJ8gk7/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVGtFNGJaUnZERTIvUHF5
            bC9xMHIzMDQ3RDdVbDFWcGNqaXE0dzJESWhFCjZkeGROMGhpcUVxUHpHaGhkRDl2
            OER2MTcvT2UzWndJdU1RVUJyWGQyYjgKLS0tIEdZNHlRVXhnWUhKTy90dEI2MVN5
            c0lNb3ZRQk1yWW5uWFBkbHVkTEJEQlUK/+79zaHlKHmT7NshxcQvY6PQuQEE+TeP
            Bem71CYQs/yc3yGoyhFr4fdNS4NPCOoHGOMjPuqAqq9rw/JzIHZZ5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z6zvvtswe44922cg7xwzk5q2rtk5x3qrwg6w0pttl8l88q4ggaqswngurh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T21:12:46Z"
    mac: ENC[AES256_GCM,data:MFF0VugLzTqzSreFwSu92YfSOOvZACy+R6o/6ceIIFr8yiHnd0QYKi/2K23P5yOjVV+q1HjrUFi33Er38iLBa743sq/K+XgvimzMXoxeVyCB0l88tNMJc42KbxTsKPHZp4W9uEqDpKNMCwZUeS+3Y1AVu+mHHJQk4PEdhWECgUQ=,iv:MR+HAqVZFm+JxTh4ku6ZOXqybZ+QQVri2xoWntP2RcI=,tag:AL9ch/uWurBMu3lvunWjsg==,type:str]
    version: 3.13.3
